### ISSUE TITLE
Out of sync responses

### ISSUE THREAD

**Issue by stockholmux** [RedisLabsModules/RediSearch#102]
Redis 4.0 stable / RediSearch 0.19.1

I'm getting some strange results in redis-cli:
```
127.0.0.1:6379> FT.SEARCH search-test "one"
1) (integer) 1
127.0.0.1:6379> FT.SEARCH search-test "one"
(error) WRONGTYPE Operation against a key holding the wrong kind of value
127.0.0.1:6379> FT.SEARCH search-test "one" NOCONTENT
1) (integer) 1
127.0.0.1:6379> FT.SEARCH search-test "one" NOCONTENT
(error) WRONGTYPE Operation against a key holding the wrong kind of value
127.0.0.1:6379> FT.CREATE search2 SCHEMA myfield text
1) (integer) 1
2) "test"
127.0.0.1:6379> FT.ADD search2 doc1 1 NOSAVE FIELDS field1 "one two three"
1) (integer) 1
2) "test"
127.0.0.1:6379> FT.SEARCH search2 "one"
OK
127.0.0.1:6379> FT.SEARCH search2 "one"
OK
127.0.0.1:6379> FT.SEARCH search2 "one"
1) (integer) 0
```

It's like the the responses are out of sync - note the `FT.CREATE` responding with something to do with "test" (not referenced in that command) and then later running the same command three times (`FT.SEARCH`) and the differing response type.

Apologies if this is redis-cli bug, but I'm only seeing this with RediSearch.

**Comment by dvirsky** [comment]
This is indeed a case where the responses are out of sync with the queries, but the first query you're sending is already out of sync. I need a full log of commands that gets you in this state to check this.

**Comment by dvirsky** [comment]
(the cause of this is usually a declaration of the size of an array response which is smaller than the actual size of the array)

**Comment by dvirsky** [comment]
Any chance you played with SUGADD/SUGDE?

**Comment by stockholmux** [comment]
No - not working with SUGADD/SUGDE but I think I've got the conditions in which this is happening (and why).

(initial set / get to show sync)
```
127.0.0.1:6379> flushdb
OK
127.0.0.1:6379> set xyz 456
OK
127.0.0.1:6379> get xyz
"456"
127.0.0.1:6379> ft.create search9 schema payload text
OK
127.0.0.1:6379> ft.add search9 test 1 nosave fields payload "one two three"
OK
127.0.0.1:6379> ft.search search9 "one" nocontent
1) (integer) 1
2) "test"
127.0.0.1:6379> ft.search search9 "one"
1) (integer) 1
127.0.0.1:6379> get xyz
"456"
127.0.0.1:6379> set test kyle
OK
127.0.0.1:6379> ft.search search9 "one"
1) (integer) 1
127.0.0.1:6379> ft.search search9 "one"
(error) WRONGTYPE Operation against a key holding the wrong kind of value
```

If the `docId` is set to something other than a hash and the FT.SEARCH is called without NOCONTENT, the internal module HGETALL errors out and redis-cli can't handle it. From MONITOR:

```
1500309806.562895 [0 127.0.0.1:52956] "set" "xyz" "456"
1500309810.786624 [0 127.0.0.1:52956] "get" "xyz"
1500309830.358894 [0 127.0.0.1:52956] "ft.create" "search9" "schema" "payload" "text"
1500309845.490833 [0 127.0.0.1:52956] "ft.add" "search9" "test" "1" "nosave" "fields" "payload" "one two three"
1500309857.501324 [0 127.0.0.1:52956] "ft.search" "search9" "one" "nocontent"
1500309874.809200 [0 127.0.0.1:52959] "AUTH" "redisiscool"
1500309874.809478 [0 127.0.0.1:52959] "COMMAND"
1500309876.266706 [0 127.0.0.1:52959] "flushdb"
1500309879.742700 [0 127.0.0.1:52959] "set" "xyz" "456"
1500309885.450634 [0 127.0.0.1:52959] "get" "xyz"
1500309891.324555 [0 127.0.0.1:52959] "ft.create" "search9" "schema" "payload" "text"
1500309895.065403 [0 127.0.0.1:52959] "ft.add" "search9" "test" "1" "nosave" "fields" "payload" "one two three"
1500309907.970758 [0 127.0.0.1:52959] "ft.search" "search9" "one" "nocontent"
1500309925.548863 [0 127.0.0.1:52959] "ft.search" "search9" "one"
1500309925.549057 [0 ?:0] "HGETALL" "test"
1500309936.451177 [0 127.0.0.1:52959] "get" "xyz"
1500309949.933092 [0 127.0.0.1:52959] "set" "test" "kyle"
1500309963.631056 [0 127.0.0.1:52959] "ft.search" "search9" "one"
1500309963.631252 [0 ?:0] "HGETALL" "test"
```
Causing out of sync responses.

Obviously, you shouldn't try to `FT.SEARCH` with a `docId` that has a key is set to a non-hash type. But I would assume the expected behaviour would be to error out the whole command rather than causing this sync issue.

**Comment by dvirsky** [comment]
@mnunberg mind fixing that? Thanks

**Comment by mnunberg** [comment]
I haven't managed to replicate this behavior unfortunately. Let me try with a newer redis..

**Comment by dvirsky** [comment]
@mnunberg  The problem is that LoadDocument uses the RMUTIL_ASSERT_NOERROR macro which replies with error under the hood. We should just return and do nothing in this case.

**Comment by dvirsky** [comment]
Ok, I just fixed it and pushed to master. Nice catch @stockholmux! That's what happens when you don't test for every possible error path...

**Comment by stockholmux** [comment]
Glad I can help. I'll continue to drunken monkey test this thing for the next week or so.

**Comment by itamarhaber** [comment]
If any booze is left after the 🐒 is done, please pass it on.
