### ISSUE TITLE
missing modules.h under libstemmer while doing make

### ISSUE THREAD

**Issue by snakepoon** [RedisLabsModules/RediSearch#104]
make -C trie
which: no lemon in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/java/jdk1.7.0_80/bin:/usr/java/jdk1.7.0_80/jre/bin:/opt/soft/mysql/bin:/root/bin)
make[1]: Entering directory `/opt/soft/RediSearch/src/trie'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/opt/soft/RediSearch/src/trie'
make -C dep/triemap
which: no lemon in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/java/jdk1.7.0_80/bin:/usr/java/jdk1.7.0_80/jre/bin:/opt/soft/mysql/bin:/root/bin)
make[1]: Entering directory `/opt/soft/RediSearch/src/dep/triemap'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/opt/soft/RediSearch/src/dep/triemap'
make -C rmutil
which: no lemon in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/java/jdk1.7.0_80/bin:/usr/java/jdk1.7.0_80/jre/bin:/opt/soft/mysql/bin:/root/bin)
make[1]: Entering directory `/opt/soft/RediSearch/src/rmutil'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/opt/soft/RediSearch/src/rmutil'
make -C dep/libnu
which: no lemon in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/java/jdk1.7.0_80/bin:/usr/java/jdk1.7.0_80/jre/bin:/opt/soft/mysql/bin:/root/bin)
make[1]: Entering directory `/opt/soft/RediSearch/src/dep/libnu'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/opt/soft/RediSearch/src/dep/libnu'
make -C dep/snowball libstemmer.o
which: no lemon in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/java/jdk1.7.0_80/bin:/usr/java/jdk1.7.0_80/jre/bin:/opt/soft/mysql/bin:/root/bin)
make[1]: Entering directory `/opt/soft/RediSearch/src/dep/snowball'
libstemmer/mkmodules.pl libstemmer/modules.h src_c libstemmer/modules.txt libstemmer/mkinc.mak
: No such file or directory
make[1]: *** [libstemmer/modules.h] Error 127
make[1]: Leaving directory `/opt/soft/RediSearch/src/dep/snowball'
make: *** [dep/snowball/libstemmer.o] Error 2

**Comment by dvirsky** [comment]
That is weird, try downloading the latest version again. What os is this?

**Comment by dvirsky** [comment]
@snakepoon did you figure it out? It doesn't seem to be an inherent problem with RediSearch, just some issue with your unzipping the archive or cloning the repo.

**Comment by snakepoon** [comment]
@dvirsky you are right, I think it is the zip file's issue. I download from GIT on windows firstly and then sent to my linux machine followed by the make instructions, turned out failed. Now I download the whole thing from linux machine and it works. Thx
