### ISSUE TITLE
FT.SEARCH with multiple Modifiers.

### ISSUE THREAD

**Issue by nreddipalle** [RedisLabsModules/RediSearch#106]
The intersect results suppose to be same (in my case 7) but it is changing based on the first modifier result.
My assumption is that the results will be same irrespective of the modifier order.
![image](https://user-images.githubusercontent.com/28302399/28473619-659be9b4-6e13-11e7-864b-e78941e9d27c.png)

**Comment by dvirsky** [comment]
you are not quoting the query so the second argument is discarded. in the explain you are doing it. If you quote correctly and still see an issue, please reopen, but the example above is expected considering you forgot the quotes.
