### ISSUE TITLE
Compile fails on Mac OS

### ISSUE THREAD

**Issue by girishso** [RedisLabsModules/RediSearch#107]
`make all` fails with following error:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ./src all
cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -D_GNU_SOURCE -std=gnu99 -I"RediSearch/src" -DREDIS_MODULE_TARGET -DREDISMODULE_EXPERIMENTAL_API  -g -ggdb -O2  -mmacosx-version-min=10.6   -c -o RediSearch/src/buffer.o RediSearch/src/buffer.c
cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -D_GNU_SOURCE -std=gnu99 -I"RediSearch/src" -DREDIS_MODULE_TARGET -DREDISMODULE_EXPERIMENTAL_API  -g -ggdb -O2  -mmacosx-version-min=10.6   -c -o RediSearch/src/concurrent_ctx.o RediSearch/src/concurrent_ctx.c
RediSearch/src/concurrent_ctx.c:21:3: warning: implicit declaration of function 'clock_gettime' is invalid in
      C99 [-Wimplicit-function-declaration]
  clock_gettime(CLOCK_MONOTONIC_RAW, &now);
  ^
RediSearch/src/concurrent_ctx.c:21:17: error: use of undeclared identifier 'CLOCK_MONOTONIC_RAW'
  clock_gettime(CLOCK_MONOTONIC_RAW, &now);
                ^
RediSearch/src/concurrent_ctx.c:38:19: error: use of undeclared identifier 'CLOCK_MONOTONIC_RAW'
    clock_gettime(CLOCK_MONOTONIC_RAW, &ctx->lastTime);
                  ^
RediSearch/src/concurrent_ctx.c:50:17: error: use of undeclared identifier 'CLOCK_MONOTONIC_RAW'
  clock_gettime(CLOCK_MONOTONIC_RAW, &ctx->lastTime);
```

**Comment by dvirsky** [comment]
What version of Mac OS / XCode is this? I'm compiling it on Mac OS Sierra with the latest XCode without issue.

**Comment by girishso** [comment]
El Capitan - 10.11.6 (15G1217)
X Code - Version 8.2.1 (8C1002)

May be that's the issue.

**Comment by dvirsky** [comment]
Yeah, seems like they introduced this back in Sierra after it's been deprecated for a few years. I wasn't aware of that.

**Comment by dvirsky** [comment]
I'm not sure I'm going to change that, to be honest. It's not like people will be running RediSearch on Mac for production usage, Mac is supported as a development platform, I'm not sure supporting old versions of Mac OS is worth the code complication. I'm open to differing opinions though.

**Comment by girishso** [comment]
You're right, nobody will running production on Macs.  I also don't see any point in supporting old Mac OS versions.  I got around it by using docker.

**Comment by dvirsky** [comment]
Alright then, I'm closing this. I will make a note in the docs about supported Mac versions.
