### ISSUE TITLE
Question - Reduce Memory Footprint of the records..

### ISSUE THREAD

**Issue by nreddipalle** [RedisLabsModules/RediSearch#114]
Currently this is my index info. For **101988** records the memory footprint is around **1.06GB**. allowed users field is a big field with comma seperated values comprising of userIds. (usually it will be around in thousands for each record).  Would like to know if there is any way to compress this data further as my goal is to load millions of records in future.
If i skip AllowedUsers field, the memory footprint for the same records is around 70MB. any suggestions to get around this??

ft.info Ticket
 1)  "index_name"
 2)  "Ticket"
 3)  "fields"
 4)    1)      1)    "TicketID"
   2)    "type"
   3)    "NUMERIC"
   4)    "SORTABLE"

  2)      1)    "TickID"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "35"

  3)      1)    "Title"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "30"

  4)      1)    "Description"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "20"

  5)      1)    "ProjectID"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "1"

  6)      1)    "Tag"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "10"

  7)      1)    "Comment"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "2"

  8)      1)    "AllowedUsers"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "4"

  9)      1)    "AssignedToUser"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "10"

 5)  "num_docs"
 6)  "101988"
 7)  "max_doc_id"
 8)  "101988"
 9)  "num_terms"
 10)  "284032"
 11)  "num_records"
 12)  "157036826"
 13)  "inverted_sz_mb"
 14)  "1061.8469619750977"
 15)  "inverted_cap_mb"
 16)  "0"
 17)  "inverted_cap_ovh"
 18)  "0"
 19)  "offset_vectors_sz_mb"
 20)  "309.68061447143555"
 21)  "skip_index_size_mb"
 22)  "0"
 23)  "score_index_size_mb"
 24)  "0"
 25)  "doc_table_size_mb"
 26)  "4.4741134643554688"
 27)  "key_table_size_mb"
 28)  "2.4865322113037109"
 29)  "records_per_doc_avg"
 30)  "1539.7579323057614"
 31)  "bytes_per_record_avg"
 32)  "7.0902296347903908"
 33)  "offsets_per_term_avg"
 34)  "1.1164102953885366"
 35)  "offset_bits_per_record_avg"
 36)  "14.817623172618624"

**Comment by dvirsky** [comment]
The main problem: `"records_per_doc_avg: 1539.7579323057614"`. That's a lot of allowed users!
Two things you can do:

1. In the application level, use groups instead of individual users. If you can reduce 1500 users to say 10 groups it's a huge win. It will also make user management easier because you will not need to update redisearch with added/removed users. 

2. If you do not require exact phrase matching (IIRC you don't) and you don't need frequency calculations for relevance ranking - you can add `NOOFFSETS NOFREQS` (or any of them) to the index creation command. This will reduce memory consumption by probably 50-60%. The bigger gain is from NOOFFSETS. 

But the better approach IMO is groups, but it's a matter of your app's preferences.

**Comment by dvirsky** [comment]
BTW in the near future I intend to add a "tag field" with much more compact encoding, that would make this problem go away. It will only use about 1 byte per user per document, instead of 6 it uses today, because you will not need data like frequencies or offsets.

**Comment by nreddipalle** [comment]
Thanks. For now, If I create index with NOOFFSETS, and search for @AllowedUsers:10363 (which is similar to exact match search), it wont give me proper results??

**Comment by nreddipalle** [comment]
I created the index by setting NOOFFSETS and NOFREQS to my index. the memory used is now around 450MB. When I search for a term (like redis|redis*), the results look same as before. could you provide me an example on the implications of using NOOFFSETS and NOFREQS. thanks.

**Comment by dvirsky** [comment]
exact phrase - meaning that if I search like `FT.SEARCH idx "\"hello world\"", this retrieves only documents where hello appears right after world. Without the offsets we cannot do that filtering. the frequencies mean that documents where a word repeats many times will not get priority over documents where it appears only once. If you're using SORTBY it has zero meaning.

**Comment by nreddipalle** [comment]
Thanks.

**Comment by nreddipalle** [comment]
In near future as an enhancement request, Is it possible to set OFFSET & FREQS flags - field specific during Index creation??
