### ISSUE TITLE
Bad directive or wrong number of arguments,How can i deal with this problem?

### ISSUE THREAD

**Issue by sunny5156** [RedisLabsModules/RediSearch#115]
[root@10-9-124-228 src]# /usr/bin/redis-server --loadmodule ./redisearch.so 

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'loadmodule "./redisearch.so"'
Bad directive or wrong number of arguments

os:centos 7
redis 3.2

**Comment by dvirsky** [comment]
RediSearch works with redis 4.0 only. Please install [redis 4.0.1](http://download.redis.io/releases/redis-4.0.1.tar.gz).
