### ISSUE TITLE
Problem with ciryllic symbols

### ISSUE THREAD

**Issue by yyyyeeeeesss** [RedisLabsModules/RediSearch#118]
Hello!

I used rediSearch with ciryllic symbols and get error like:
 
127.0.0.1:6379> FT.SEARCH testRediSearch "Мойки BOSCH AQUATAK 1500 X"
(error) Syntax error at offset 0 near '�'

How to solve this problem?

P.S.: redis version - 4.0

**Comment by dvirsky** [comment]
Hi Pavel. The Cyrillic text must be encoded as utf-8. If it is, there is no problem:

```
127.0.0.1:6379> ft.create idx schema foo text
OK
127.0.0.1:6379> ft.add idx 1 1 fields foo "Мойки BOSCH AQUATAK 1500 X"
OK
127.0.0.1:6379> ft.search idx "Мойки"
1) (integer) 1
2) "1"
3) 1) "foo"
   2) "\xd0\x9c\xd0\xbe\xd0\xb9\xd0\xba\xd0\xb8 BOSCH AQUATAK 1500 X"
127.0.0.1:6379>
```

**Comment by dvirsky** [comment]
Make sure that your terminal's encoding is utf-8, or try it via a client that works with utf-8 and not 32-bit unicode or another encoding.

**Comment by yyyyeeeeesss** [comment]
Thank you! This was the problem.
