### ISSUE TITLE
HyperLogLog support

### ISSUE THREAD

**Issue by refaelos** [RedisLabsModules/RediSearch#121]
Hey,

Does Redis search supports saving HyperLogLogs for cardinality estimation over search?

**Comment by dvirsky** [comment]
No, there isn't. I don't see how it would help much compared to the memory cost of maintaining HLL indexes on each term. How do you figure it would help?

**Comment by refaelos** [comment]
@dvirsky what do you mean by "help"?
I just thought it'll be good to have this support HLLs so we can maybe use this instead of our current key-value HLLs and save space on keys names.

**Comment by dvirsky** [comment]
Can you explain how you would like this to work?

**Comment by dvirsky** [comment]
(I mean from the user's perspective, not how it would work technically). You search for something and then what?

**Comment by dvirsky** [comment]
@refaelosaybe there's something in this idea. If you can explain what you were imagining ee cam discuss, and perhaps there's a way to achieve something similar with redisearch

**Comment by refaelos** [comment]
Can we talk on phone?
If yes, send me email to refael (at) soom.la
