### ISSUE TITLE
support chinese now?

### ISSUE THREAD

**Issue by yansuihehe** [RedisLabsModules/RediSearch#122]

**Comment by dvirsky** [comment]
I'd really like to add it but I need help from someone fluent in Chinese. Can you point me at good Chinese toeknization libraries?

**Comment by blm-fu** [comment]
Do you mean  this?
[https://raw.githubusercontent.com/fxsjy/jieba/master/extra_dict/dict.txt.big](url)

@dvirsky

**Comment by dvirsky** [comment]
@blm-fu that would be a good start, but you also need a tokenizer that will work on the text with it.

**Comment by lufeng4828** [comment]
nice project !!! but waiting for Chinese support also

**Comment by dvirsky** [comment]
We now have issue #206 so I'm closing this. 

@lufeng4828 @blm-fu @yansuihehe once this is implemented we'd really appreciate your feedback in trying this out and making sure it works as expected.
