### ISSUE TITLE
Question - FT.ADD REPLACE option doesnt seem to work as expected.

### ISSUE THREAD

**Issue by nreddipalle** [RedisLabsModules/RediSearch#124]
![image](https://user-images.githubusercontent.com/28302399/28896099-1ff2f05c-77a9-11e7-8c58-7fb9c80b09cb.png)

Adding one record...

![image](https://user-images.githubusercontent.com/28302399/28896138-3f9f6e26-77a9-11e7-8292-73f549f48784.png)

![image](https://user-images.githubusercontent.com/28302399/28896166-53fc03b6-77a9-11e7-8e86-9b6e45d49e42.png)

Adding the same record again,,,,

![image](https://user-images.githubusercontent.com/28302399/28896191-6ed977e0-77a9-11e7-93a6-5b627cf4a682.png)

![image](https://user-images.githubusercontent.com/28302399/28896230-9385cd3c-77a9-11e7-87fa-b66c386792f2.png)

My expectation is that it would replace the same record "REPLACE" option is included while adding  (which means the num_docs, num_records,inverted_size_mb stays the same) but it is not the case..... If my requirement is to re-index the tickets regularly I dont want the size to get increased. Please clarify.....

**Comment by dvirsky** [comment]
Hi. 
I won't go into how it works internally, but in inverted indexes updating a document internally deletes it from the index and creates a new instance of it. This does not affect anything externally - but creates "garbage" in the index, and indeed what you are seeing is not desired behavior.

The index has a garbage collector that optimizes this memory in the background without interrupting normal operation. At the current release it needs to be worked manually, but in the next release it will work out of the box. You can try the gc_threading branch and see it in action. It will be released in a day or two. 

Here's an example of what happens after this change:

```
127.0.0.1:6379> ft.create idx schema foo text
OK
127.0.0.1:6379> ft.add idx 1 1 replace fields foo "hello world" bar "foo bar"
OK
127.0.0.1:6379> ft.info idx
 1) index_name
 2) idx
....
 7) num_docs
 8) "1"
 9) max_doc_id
10) "1"
11) num_terms
12) "2"
13) num_records
14) "2"
15) inverted_sz_mb
16) "1.1444091796875e-05"
17) offset_vectors_sz_mb
18) "1.9073486328125e-06"
19) doc_table_size_mb
20) "3.910064697265625e-05"
21) key_table_size_mb
22) "3.4332275390625e-05"
23) records_per_doc_avg
24) "2"
25) bytes_per_record_avg
26) "6"
27) offsets_per_term_avg
28) "1"
29) offset_bits_per_record_avg
30) "8"
31) gc_stats
32) 1) current_hz
    2) "7.6234259605407715"
    3) bytes_collected
    4) "0"
    5) effectiv_cycles_rate
    6) "0"

// now let's insert the document again with REPLACE
127.0.0.1:6379> ft.add idx 1 1 replace fields foo "hello world"
OK
// wait a bit for GC to collect the garbage...

127.0.0.1:6379> ft.info idx
 1) index_name
 2) idx
 ....
7) num_docs
 8) "1"
 9) max_doc_id
10) "2"
11) num_terms
12) "2"
13) num_records
14) "2"
15) inverted_sz_mb
16) "1.1444091796875e-05"
....
31) gc_stats
32) 1) current_hz
    2) "6.2385492324829102"
    3) bytes_collected
    4) "12"
    5) effectiv_cycles_rate
    6) "0.020202020202020204"
```

Notice the GC stats showing that it collected 12 bytes, which are the "hello" and "world" records from the internally deleted document 1.

**Comment by dvirsky** [comment]
You can read more about how it works in the design document: https://github.com/RedisLabsModules/RediSearch/blob/gc_threading/docs/design/gc.md

Again, it still needs some testing but it's working and will get into master very soon.

**Comment by nreddipalle** [comment]
ok thanks for the clarification.

**Comment by nreddipalle** [comment]
what is the command to run if I want to manually run the GC in the meanwhile??

**Comment by nreddipalle** [comment]
can you provide the command to manually run the GC till the fix is provided.
