### ISSUE TITLE
Query on Numeric fields is not working properly. 

### ISSUE THREAD

**Issue by anshul-uninstall** [RedisLabsModules/RediSearch#127]
I use the following query- 
FT.SEARCH myidx  "@numericColumn: [0 100]"
and it returns a proper set of records. 

But when I set the min value to 70 or above i.e. 
FT.SEARCH myidx  "@numericColumn: [70 100]"
It doesn't return any records even when records  exist in  my database which satisfy the given range. 
Similar issue happens with other numeric columns as well with different numeric range.

**Comment by dvirsky** [comment]
can you give a proper example that we can recreate? There are numerous tests for this exact scenario, but there might be something missing. Please provide a way to recreate.

**Comment by anshul-uninstall** [comment]
Hey so you can download the dump from this link.
https://drive.google.com/file/d/0BySCDAZdfpHAWHFqTTdyV1NmMXM/view?usp=sharing

Name of the index is patient_info_list. bpDiastolic and BSL_2HPP are two numeric fields.  Numeric filter is not working at all on BSL_2HPP.  For bpDiastolic filter is not working when I set the min value of range to 70 or above. 

Now in both columns '-1' value  has major proportion(almost 90%). Query works fine when I set min value less then or equal to -1.  So data distribution could be a possible reason for this issue.

**Comment by dvirsky** [comment]
@anshul-uninstall thank you very much, this is very valuable. I'll research the problem and hopefully find a quick fix for it.

**Comment by dvirsky** [comment]
@anshul-uninstall regarding BSL_2HPP - looks ALL recrords have a value of -1. The number of results for [-1 -1] is 635181, same as the number of documents in the index. I can verify it by printing out all the values in it, but at first glance it seems that this is the case.

Regarding the other index - I can indeed see the bug. I will investigate promptly. Thank you very much!

**Comment by anshul-uninstall** [comment]
Hi dvirsky , so there are three records with non -1 values in BSL_2HPP.
p_id values are - [12406, 3416, 7013]

you can search these values on "p_id" field in patient_info_list.

FT.SEARCH patient_info_list @p_id:12406

Please check,
Thanks

**Comment by dvirsky** [comment]
yeah I found them, the numeric values are 14,15 and 9. For the second field there are about 15 records with other values. I found the bug and hopefully will have a fix shortly.

**Comment by anshul-uninstall** [comment]
Great! Thanks.

**Comment by dvirsky** [comment]
@anshul-uninstall I've found the bug and fixed it. Thanks for this, it's a great catch! I'm closing the issue, please pull master, recompile and verify that it indeed works for you. It does for me on your dataset :)

```
127.0.0.1:6379> ft.search patient_info_list "@bpDiastolic:[77 180]" return 1 bpDiastolic
 1) (integer) 8
 2) "1:8451:1"
 3) 1) "bpDiastolic"
    2) "77"
 4) "1:8639:None"
 5) 1) "bpDiastolic"
    2) "92"
 6) "1:4096:1"
 7) 1) "bpDiastolic"
    2) "77"
 8) "1:6108:1"
 9) 1) "bpDiastolic"
    2) "82"
10) "1:13654:1"
11) 1) "bpDiastolic"
    2) "78"
12) "1:590:None"
13) 1) "bpDiastolic"
    2) "90"
14) "1:8722:None"
15) 1) "bpDiastolic"
    2) "86"
16) "1:3501:None"
17) 1) "bpDiastolic"
    2) "81"
```

**Comment by anshul-uninstall** [comment]
Great @dvirsky. It's working now. You saved me from migrating to elasticsearch. 
Thanks
