### ISSUE TITLE
search queries failling with "Internal error processing query"

### ISSUE THREAD

**Issue by coolmeen** [RedisLabsModules/RediSearch#13]
i tried out the main example from the wiki.
```
`27.0.0.1:6379>` FT.CREATE myIdx title 5.0 body 1.0 url 1.0
OK
127.0.0.1:6379> FT.ADD myIdx doc1 1.0 fields title "hello world" body "lorem ipsum" url "http://redis.io" 
OK
`127.0.0.1:6379> FT.SEARCH myIdx "http://re"
1) (integer) 0
127.0.0.1:6379> FT.SEARCH myIdx "hell"
(error) Internal error processing query
127.0.0.1:6379> FT.SEARCH myIdx "wor"
(error) Internal error processing query
```

i am using the latest redis (4.0-rc2)

**Comment by dvirsky** [comment]
the engine does not support incomplete word searches, there is a bug in reporting empty results, but the behavior for this search is indeed that no results are found. search for actual words in the corpus and you get proper results. anyway I'll fix this as well.

**Comment by dvirsky** [comment]
fixed in latest push to master. 
BTW if you want to search for prefixes, use the SUGADD/SUGGET commands instead. The full-text index doesn't support prefix searches.

**Comment by dvirsky** [comment]
@coolmeen can you confirm the fix please? Also, I've fixed the other issue you've reported, regarding 50 results.

**Comment by coolmeen** [comment]
works great
