### ISSUE TITLE
Save index formed by docs with tag NOSAVE to disk

### ISSUE THREAD

**Issue by abhijitiitr** [RedisLabsModules/RediSearch#130]
I created an index using the command 
```bash
FT.CREATE 'test_idx' NOSCOREIDX NOFREQS SCHEMA a NUMERIC ....
```

I then added 29M docs using
```
FT.ADD 'test_idx' docId NOSAVE FIELDS a 1....
```

The RSS is around 4.1GB after adding all the docs. I want to save the index to disk, so that it can be reused on a different machine. So far I don't think RediSearch is saving the index to a disk.

Is there an explicit command which needs to be used or is the index already being saved on the disk?

**Comment by dvirsky** [comment]
Please read the documentation on redis persistence and replication to get an understanding of how it works. In short, after issuing the BGSAVE or SAVE command will dump the data to disk.

**Comment by abhijitiitr** [comment]
Thanks for the answer.
