### ISSUE TITLE
[FR] Update a document

### ISSUE THREAD

**Issue by itamarhaber** [RedisLabsModules/RediSearch#132]
Currently, in order to update a document `FT.ADD` is called, and the existing document is deleted (and later gced) before the updated document is stored.

In some use cases it is needed to update only a subset of the index's fields, rather than a forklift update of the entire document. This becomes even more painful when documents have multiple fields and/or big payloads and/or not stored as Hashes.

While read-merge-update logic can be implemented in the application code, the RediSearch client and/or a Lua script, it looks to me like it would be correct-er to have a new command (e.g. `FT.UPDATE`) and/or another modifier to `FT.ADD` to deal with that optimally.

**Comment by dvirsky** [comment]
You do understand that internally this will happen all the same, right? 

We are also seeing that most users don't store documents inside the index, in that case they must submit all indexable fields to the engine as we cannot retrieve the fields for update. So while it would be useful I'd say it's pretty low priority.

**Comment by dvirsky** [comment]
@jrots @itamarhaber you can check the "partial_update" branch. It also include non indexed fields for fast updates, and the PARTIAL keyword in FT.ADD. It's not documented yet but it's working (see testPartial in test.py for example usage)

**Comment by jrots** [comment]
Alright great work! I'll check this out later today

**Comment by dvirsky** [comment]
This has been merged into 0.21. closing
