### ISSUE TITLE
Logic bug for intersection

### ISSUE THREAD

**Issue by jichifly** [RedisLabsModules/RediSearch#138]
https://github.com/RedisLabsModules/RediSearch/blob/master/src/index.c#L454
Shouldn't it be !ic->atEnd?

    int II_HasNext(void *ctx) {
      IntersectContext *ic = ctx;
      // printf("%p %d\n", ic, ic->atEnd);
      return ! ic->atEnd; // prepend !
    }

For example, when a query is like "(@X=a @Y=b)|(@Z=c @W=d)", the result does not look correct, which will hit this bug.

**Comment by dvirsky** [comment]
You are right, I've fixed it. This is also probably the cause of #139 but needs to be verified.
