### ISSUE TITLE
Bug for nested intersection

### ISSUE THREAD

**Issue by jichifly** [RedisLabsModules/RediSearch#139]
Found a bug when a query is like the following when there are more than 2 intersections:

    (@A=x @B=y @C=z) 

For example, the result set is entirely different from:

    (@A=x @C=z @B=y)

btw, I tried to debug RediSearch module myself. Always with verbatim enabled.
I tried a query that is supposed to return only 1 result, but it actually returned 16 results.
In Query_Execute function, The first result is always the correct one, then the second result is wrong.
The iteration should stop after the first result is out.

**Comment by dvirsky** [comment]
Can you give a reproducible example of data insertion and query? Thanks!

_Sent from my OnePlus ONE A2001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dvirsky** [comment]
Also try pulling master and recreating that bug, it might be gone with the fix to #138

**Comment by dvirsky** [comment]
@jichifly I was able to recreate it and it was indeed fixed by fixing #138. please verify that the fix works for you as well and close the issue if it does. Thanks, this is a very good find. I'm adding a test to recreate this state.

**Comment by dvirsky** [comment]
@jichifly I'm closing this as AFAICT it's fixed. Please reopen if not.

**Comment by jichi-houzz** [comment]
Thanks so much for your quick work!
I manually fixed issue #138, but still hit the same problem.
Let me try it again and will let you know!

**Comment by dvirsky** [comment]
@jichifly there was an extra problem with the query parser precedence order, that I fixed as well.
