### ISSUE TITLE
The Module in a Redis Windows Service?

### ISSUE THREAD

**Issue by win32nipuh** [RedisLabsModules/RediSearch#14]
How to add this module to a Redis Windows Service?

**Comment by dvirsky** [comment]
That's not going to be supported in the foreseeable future. Redis for Windows is a Microsoft fork of redis, that does not support modules. If they decide to implement modules, it might be possible. As of now, it's not possible.

You can use the new Windows 10 Ubuntu shell to run a proper redis if you like.

**Comment by win32nipuh** [comment]
Thank you!
