### ISSUE TITLE
Relates to Issue #124

### ISSUE THREAD

**Issue by nreddipalle** [RedisLabsModules/RediSearch#140]
can you provide the command to manually run the GC till the fix is provided. relates to #124

**Comment by dvirsky** [comment]
We intend to ship a version with proper gc tomorrow, so there's no point IMO. You can try the gc_threading branch, and report if you see any problems. It's complete, just waiting integration with a few other things for the next release.

**Comment by dvirsky** [comment]
@nreddipalle the version with active GC is now out (0.20.0). I'm closing this.
