### ISSUE TITLE
Remove NOSCOREIDX from documentation and client libraries

### ISSUE THREAD

**Issue by jrots** [RedisLabsModules/RediSearch#149]
Not sure if it's just a superficial issue, 
but seems like the `NOSCOREIDX` is not shown when passing it to index creation and afterwards in the `index_options`

```
127.0.0.1:6379> FT.CREATE myIdx NOOFFSETS NOFIELDS NOSCOREIDX NOFREQS STOPWORDS 0 SCHEMA test NUMERIC
OK
```
```
127.0.0.1:6379> ft.info myIdx
 1) index_name
 2) myIdx
 3) index_options
 4) 1) "NOFREQS"
    2) "NOFIELDS"
    3) "NOOFFSETS"
 5) fields
 6) 1) 1) test
       2) type
       3) NUMERIC
```

**Comment by dvirsky** [comment]
Yeah it's deprecated and not in use anymore, the optimization took tons of memory and wasn't very helpful, so I removed it. I need to remove any mention of it from the docs.

**Comment by dvirsky** [comment]
@mnunberg care to take this one? besides docs, there are a few relics in the spec parsing, just run a search for it and you'll see it all. 

Also the flag needs to be deleted from the py/java clients (it's not in the Go one already).

Thanks!

**Comment by dvirsky** [comment]
@mnunberg can this be closed or are there still tasks left?

**Comment by mnunberg** [comment]
Technically I still need to merge it in the other libraries.
