### ISSUE TITLE
FT.CREATE NOSTEM index creation bug

### ISSUE THREAD

**Issue by jrots** [RedisLabsModules/RediSearch#151]
related to : https://github.com/RedisLabsModules/RediSearch/pull/129

`FT.CREATE jaymetest SCHEMA hb NUMERIC ha TEXT WEIGHT 1 NOSTEM`
results in: `(error) Could not parse field spec` 
on latest master.

`FT.CREATE jaymetest SCHEMA hb NUMERIC ha TEXT NOSTEM WEIGHT 1`
works

=> there should be no importance to the order of the arguments.

**Comment by mnunberg** [comment]
https://github.com/RedisLabsModules/RediSearch/commit/7d54c6eebb3edb83b2e99b82e0cdd5dad5ef525a
