### ISSUE TITLE
redisearch - searches in the cluster

### ISSUE THREAD

**Issue by jrots** [RedisLabsModules/RediSearch#153]
Hi, just a more general question - 
Is the packet provided by redislabs that does redisearch able to do searches in the cluster,
so index that is split up automatically? 
I tried redis pack yesterday but that is still an older version of redis that doesn't support modules. Will the clustered search version be something that will be open source too in the future? 
Thx!

**Comment by dvirsky** [comment]
Yes, we are starting the rollout of the enterprise version that supports cluster mode. You can see some details here https://www.slideshare.net/dvirsky/searching-billions-of-documents-with-redis and a video demo here https://www.youtube.com/watch?v=MDnHFWTxDPQ

Please email me personally and I'll explain further. dvir at redislabs dot com.  I was wondering when you'll ask about it when you said you have 150M objects :)

Thanks!

**Comment by dvirsky** [comment]
:)
