### ISSUE TITLE
Query on hypen (-) is not working.

### ISSUE THREAD

**Issue by anshulkgupta93** [RedisLabsModules/RediSearch#155]
127.0.0.1:9393> FT.SEARCH patient_info_list "@nric:xvyc-*"
(error) Syntax error at offset 11 near 'xyvc'

**Comment by dvirsky** [comment]
Hi @anshulkgupta93. Hyphens get split during tokenization and are considered a stop character. Thus they have no meaning and cannot be used for such queries. You can replace the hyphen with an underscore if you want to retain it.

**Comment by anshulkgupta93** [comment]
Sure. Thanks.

**Comment by dvirsky** [comment]
@anshulkgupta93 I might add escaping sometime soon, I'll let you know if and when.
