### ISSUE TITLE
How score works - Custom scoring function

### ISSUE THREAD

**Issue by deivarezserve** [RedisLabsModules/RediSearch#157]
Hello,

I am having some problems trying to use scores in my index.

I am using FT.CREATE to create an index with sortable text (all weighted 1.0), sortable numeric and geofields.

Then using FT.ADD to add documents to it, sending a specific document id and pre calculated score for each document.

When I search my index though, I get a score different than the one I set. I also noted the score changes accordingly to the search params. Is that the intended behavior? Is there any way for me to consider only the preset score? I am considering adding it as a field and just sorting by it...

Please advise.

`FT.ADD 'restaurant-index' '12605054' 0.3333333333333333 'FIELDS' 'name' 'Bombay Garden' 'city' 'Nashville' 'state' '3967'  'country'  '225'  'user_id'  ''  'business_name'  ''  'description'  'test'  'image'  ''  'address'  '4858 Nolensville Pike '  'phone'  '615-781-1999'  'cost_for_two'  ''  'tags'  '[]'  'menus'  '[]'  'reviews'  '[]'  'associations'  '[]'  'status'  1  'verified'  0  'location'  '-86.71707 36.06425' `

`127.0.0.1:6379> ft.search restaurant-index '"bombay garden" @city:Nashville @state:3967 @country:225' limit 0 10 withscores nocontent`
` 1) (integer) 5`
` 2) "12605054"`
` 3) "0.36111112187306088"`

`127.0.0.1:6379> ft.search restaurant-index '@city:Nashville @state:3967 @country:225' limit 0 10 withscores nocontent`
` 1) (integer) 526`
` 2) "12605244"`
` 3) "1.3333333730697632"`
` 4) "12605054"`
` 5) "1.3333333730697632"`

**Comment by dvirsky** [comment]
The default scorer works by factoring the pre-set score, a weighted [TF-IDF](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) for each term in the query, and factoring the distance between the terms as a score reducing parameter. 

A simpler scorer is the DISMAX one, which can be invoked by adding `SCORER DISMAX` to your request (not inside the query of course). It basically factors the frequency of the terms in the documents with the pre-set score. If all terms have the same frequency (you can use the NOFREQS flags when creating the index to achieve that), the result will be the score.

**Comment by dvirsky** [comment]
I can easily add a special scorer of raw scores, and you can also use a sortable field for that - or even write your own scorer! What is most missing though is proper documentation on the scoring algorithms and alternative scorers.

**Comment by deivarezserve** [comment]
Thank you for your prompt reply!

**Comment by deivarezserve** [comment]
Basically what we are trying to achieve is for some search results to be ranked higher based on some property values (not empty and/or actual values).

Do you think a custom scoring function is the best way to go? Can you please provide some guidance or documentation on where to put (in ext folder maybe?) and how to compile the relevant files? I do have C coding experience, but honestly, it's been a while.

**Comment by dvirsky** [comment]
Sounds like what you need is optional clauses (marked with `~`) and the DISMAX scorer. 

If you want to write your own function, here's how to do it: http://redisearch.io/Extensions/

You can take the example extension from the tests folder and its makefile and play with that.

**Comment by deivarezserve** [comment]
Is this still the case:

> Right now, it is necessary to call these init functions explicitly in module.c, but in the future this will be automated.

**Comment by deivarezserve** [comment]
My understanding is this is not the case anymore, because of:
http://redisearch.io/Configuring/#extload-file_name

Can you please confirm?

**Comment by deivarezserve** [comment]
So... I'm getting this when I try to use my scorer:

`127.0.0.1:6379> ft.search menu-api_local:restaurant-index '@city:Nashville @state:3967 @country:225' limit 0 10 withscores nocontent scorer REZSERVE_RESTAURANT_SCORER`
`(error) Invalid scorer name`

What I did:
1. Created a folder inside ext with 3 files: 

rezserve.h 
`#ifndef __EXT_REZSERVE_H__`
`#define __EXT_REZSERVE_H__`
`#include "redisearch.h"`
``
`#define SCORER_NAME "REZSERVE_RESTAURANT_SCORER"`
``
`int RS_ExtensionInit(RSExtensionCtx *ctx);`
``
`#endif`

rezserve.c
`#include <string.h>`
`#include <stdio.h>`
`#include <sys/param.h>`
`#include <redisearch.h>`
`#include "rezserve.h"`
``
`/* Calculate document score for each result */`
`double myScorer(RSScoringFunctionCtx *ctx, RSIndexResult *h, RSDocumentMetadata *dmd,
                double minScore) {`
`  printf("score for %d: %f\n", h->docId, dmd->score);`
`  printf("user_id for %d: %d\n", h->docId, h->user_id);`
`  return 3.141;`
`}`
``
`/* Register the default extension */`
`int RS_ExtensionInit(RSExtensionCtx *ctx) {`
``
`  if (ctx->RegisterScoringFunction(SCORER_NAME, myScorer, NULL, NULL) == REDISEARCH_ERR) {`
`    return REDISEARCH_ERR;`
`  }`
``
`  return REDISEARCH_OK;`
`}`

Makefile copied from tests/ext-example/Makefile, replacing "example" by "rezserve"

2. Compiled it running make all 

3. Updated my .conf file replacing
`loadmodule /home/ubuntu/redis_modules/RediSearch/src/redisearch.so'

by
`loadmodule /home/ubuntu/redis_modules/RediSearch/src/redisearch.so EXTLOAD /home/ubuntu/redis_modules/RediSearch/src/ext/ext-rezserve/rezserve.so`

4. Restarted redis service

Anything I'm missing?

Thank you!

**Comment by deivarezserve** [comment]
I figured it out, had an error in my Makefile, because of the different path. All good now!

**Comment by deivarezserve** [comment]
Now I just need to figure out how to access field values from RSDocumentMetadata.
Any help you could provide would be much appreciated. 😄

**Comment by dvirsky** [comment]
@deivarezserve you cannot access field values from the document metadata. That is on purpose as accessing them is extremely slow (in terms of tight loops - a few microseconds can add up if you you're doing it for each result). The payloads are there as fast accessible data for scorers, with tens of nanoseconds order access time.

**Comment by deivarezserve** [comment]
I was afraid you were gonna answer that. 😄 

Already working on my C string parsing logic. 

Thank you!

**Comment by dvirsky** [comment]
How about I just add a scorer that just sorts on the pre-set score of the documents? It would take me 20 minutes including tests and if it works for you - great!

**Comment by deivarezserve** [comment]
Hi Dvir, 

thanks so much for offering, I got it to work last Friday already! 

If you could just update the documentation where it says it is necessary to call the init functions explicitly in module.c, that would be great, as it may make it easier for others. 

Very best regards,

**Comment by dvirsky** [comment]
@deivarezserve cool! do you still need a scorer that sorts by raw score?

**Comment by deivarezserve** [comment]
No, I'm good, that was an alternative solution, but the scoring function is exactly what I need. Thank you!

**Comment by dvirsky** [comment]
@deivarezserve I've update the documentation on how to work with extensions. thanks for noticing.

**Comment by deivarezserve** [comment]
Hi Dvir, thank you for updating it.
I noticed a typo in the example, by the way:
sh $ redis-server --**loadmoulde** ./redisearch.so EXTLOAD ./ext/my_extension.so

Regards,

**Comment by dvirsky** [comment]
@deivarezserve cheers, that was actually a bit of copypasta that propagated to many places in the docs :) fixed them all.

**Comment by deivarezserve** [comment]
Nice, thanks! 😄
