### ISSUE TITLE
Crash when using nonsense LIMIT

### ISSUE THREAD

**Issue by salt4pommes** [RedisLabsModules/RediSearch#160]
Command: ft.search seo "@base:[1 1]" NOCONTENT LIMIT 0 -1

I've tried to find a way to set LIMIT to unlimited :)

=== REDIS BUG REPORT START: Cut & paste starting from here ===
18757:M 12 Sep 11:15:30.974 # Redis 4.0.1 crashed by signal: 11
18757:M 12 Sep 11:15:30.974 # Crashed running the instuction at: 0x7f997af9d840
18757:M 12 Sep 11:15:30.974 # Accessing address: 0x10
18757:M 12 Sep 11:15:30.974 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/home/willi/.redis/redisearch.so(heap_init+0x0)[0x7f997af9d840]

Backtrace:
redis-server 127.0.0.1:6381(logStackTrace+0x45)[0x469645]
redis-server 127.0.0.1:6381(sigsegvHandler+0xb9)[0x469db9]
/usr/lib/libpthread.so.0(+0x11080)[0x7f997d79b080]
/home/willi/.redis/redisearch.so(heap_init+0x0)[0x7f997af9d840]

------ INFO OUTPUT ------
# Server
redis_version:4.0.1
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:665e3207d804ba15
redis_mode:standalone
os:Linux 4.10.17-1-ARCH x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:6.2.1
process_id:18757
run_id:f79f369e64c05d6979cb43e7a4061a1e80019d03
tcp_port:6381
uptime_in_seconds:5
uptime_in_days:0
hz:10
lru_clock:12035506
executable:/home/willi/.redis/redis-server
config_file:/home/willi/.redis/redis_search.conf

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:1

# Memory
used_memory:40755496
used_memory_human:38.87M
used_memory_rss:63201280
used_memory_rss_human:60.27M
used_memory_peak:40755496
used_memory_peak_human:38.87M
used_memory_peak_perc:100.11%
used_memory_overhead:2427558
used_memory_startup:487128
used_memory_dataset:38327938
used_memory_dataset_perc:95.18%
total_system_memory:16730136576
total_system_memory_human:15.58G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:256000000
maxmemory_human:244.14M
maxmemory_policy:volatile-lru
mem_fragmentation_ratio:1.55
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1505207725
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:1
total_commands_processed:3
instantaneous_ops_per_sec:0
total_net_input_bytes:104
total_net_output_bytes:11028
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:47
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:891a86a6593c1200af2e2904fa5362657bdd4a93
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.02
used_cpu_user:0.20
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats
cmdstat_info:calls=1,usec=44,usec_per_call=44.00
cmdstat_command:calls=1,usec=284,usec_per_call=284.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=34162,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=34 addr=127.0.0.1:47050 fd=7 name= age=1 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=FT.SEARCH

------ REGISTERS ------
18757:M 12 Sep 11:15:30.974 # 
RAX:0000000000000000 RBX:00007f9941628050
RCX:00000000ffffffff RDX:0000000000000000
RDI:0000000000000000 RSI:00007f997af976d0
RBP:0000000000000000 RSP:00007f997af5cc98
R8 :ffffffffffffffff R9 :0000000000000000
R10:00000000013ba000 R11:0000000000000001
R12:00000000ffffffff R13:00007f99340008c0
R14:0000000000000000 R15:00007f9934000908
RIP:00007f997af9d840 EFL:0000000000010246
CSGSFS:002b000000000033
18757:M 12 Sep 11:15:30.974 # (00007f997af5cca7) -> 0000000001030138
18757:M 12 Sep 11:15:30.974 # (00007f997af5cca6) -> 00007f994160d000
18757:M 12 Sep 11:15:30.974 # (00007f997af5cca5) -> 0000000001030110
18757:M 12 Sep 11:15:30.974 # (00007f997af5cca4) -> 00007f99340008c0
18757:M 12 Sep 11:15:30.975 # (00007f997af5cca3) -> 000000000103ae30
18757:M 12 Sep 11:15:30.975 # (00007f997af5cca2) -> 0000000000000001
18757:M 12 Sep 11:15:30.975 # (00007f997af5cca1) -> 0000000000000000
18757:M 12 Sep 11:15:30.975 # (00007f997af5cca0) -> 0000000000000000
18757:M 12 Sep 11:15:30.975 # (00007f997af5cc9f) -> 0000000000000001
18757:M 12 Sep 11:15:30.975 # (00007f997af5cc9e) -> 00007f9934001a20
18757:M 12 Sep 11:15:30.975 # (00007f997af5cc9d) -> 00007f99340008c0
18757:M 12 Sep 11:15:30.975 # (00007f997af5cc9c) -> 00007f9934000a50
18757:M 12 Sep 11:15:30.975 # (00007f997af5cc9b) -> 0000000000000000
18757:M 12 Sep 11:15:30.975 # (00007f997af5cc9a) -> 0000000a00000001
18757:M 12 Sep 11:15:30.975 # (00007f997af5cc99) -> 0000000000000000
18757:M 12 Sep 11:15:30.975 # (00007f997af5cc98) -> 00007f997af9a197

------ FAST MEMORY TEST ------
18757:M 12 Sep 11:15:30.975 # Bio thread for job type #0 terminated
18757:M 12 Sep 11:15:30.975 # Bio thread for job type #1 terminated
18757:M 12 Sep 11:15:30.976 # Bio thread for job type #2 terminated
*** Preparing to test memory region 74b000 (98304 bytes)
*** Preparing to test memory region 1022000 (3768320 bytes)
*** Preparing to test memory region 7f9934000000 (135168 bytes)
*** Preparing to test memory region 7f993c000000 (135168 bytes)
*** Preparing to test memory region 7f9941600000 (37748736 bytes)
*** Preparing to test memory region 7f9943c00000 (18874368 bytes)
*** Preparing to test memory region 7f9944ef3000 (8388608 bytes)
*** Preparing to test memory region 7f99456f4000 (8388608 bytes)
*** Preparing to test memory region 7f9945ef5000 (8388608 bytes)
*** Preparing to test memory region 7f99466f6000 (8388608 bytes)
*** Preparing to test memory region 7f9946ef7000 (8388608 bytes)
*** Preparing to test memory region 7f99476f8000 (8388608 bytes)
*** Preparing to test memory region 7f9947ef9000 (8388608 bytes)
*** Preparing to test memory region 7f99486fa000 (8388608 bytes)
*** Preparing to test memory region 7f9948efb000 (8388608 bytes)
*** Preparing to test memory region 7f99496fc000 (8388608 bytes)
*** Preparing to test memory region 7f9949efd000 (8388608 bytes)
*** Preparing to test memory region 7f994a6fe000 (8388608 bytes)
*** Preparing to test memory region 7f994aeff000 (8388608 bytes)
*** Preparing to test memory region 7f994b700000 (8388608 bytes)
*** Preparing to test memory region 7f994bf01000 (8388608 bytes)
*** Preparing to test memory region 7f994c702000 (8388608 bytes)
*** Preparing to test memory region 7f994cf03000 (8388608 bytes)
*** Preparing to test memory region 7f994d704000 (8388608 bytes)
*** Preparing to test memory region 7f994df05000 (8388608 bytes)
*** Preparing to test memory region 7f994e706000 (8388608 bytes)
*** Preparing to test memory region 7f994ef07000 (8388608 bytes)
*** Preparing to test memory region 7f994f708000 (8388608 bytes)
*** Preparing to test memory region 7f994ff09000 (8388608 bytes)
*** Preparing to test memory region 7f995070a000 (8388608 bytes)
*** Preparing to test memory region 7f9950f0b000 (8388608 bytes)
*** Preparing to test memory region 7f995170c000 (8388608 bytes)
*** Preparing to test memory region 7f9951f0d000 (8388608 bytes)
*** Preparing to test memory region 7f995270e000 (8388608 bytes)
*** Preparing to test memory region 7f9952f0f000 (8388608 bytes)
*** Preparing to test memory region 7f9953710000 (8388608 bytes)
*** Preparing to test memory region 7f9953f11000 (8388608 bytes)
*** Preparing to test memory region 7f9954712000 (8388608 bytes)
*** Preparing to test memory region 7f9954f13000 (8388608 bytes)
*** Preparing to test memory region 7f9955714000 (8388608 bytes)
*** Preparing to test memory region 7f9955f15000 (8388608 bytes)
*** Preparing to test memory region 7f9956716000 (8388608 bytes)
*** Preparing to test memory region 7f9956f17000 (8388608 bytes)
*** Preparing to test memory region 7f9957718000 (8388608 bytes)
*** Preparing to test memory region 7f9957f19000 (8388608 bytes)
*** Preparing to test memory region 7f995871a000 (8388608 bytes)
*** Preparing to test memory region 7f9958f1b000 (8388608 bytes)
*** Preparing to test memory region 7f995971c000 (8388608 bytes)
*** Preparing to test memory region 7f9959f1d000 (8388608 bytes)
*** Preparing to test memory region 7f995a71e000 (8388608 bytes)
*** Preparing to test memory region 7f995af1f000 (8388608 bytes)
*** Preparing to test memory region 7f995b720000 (8388608 bytes)
*** Preparing to test memory region 7f995bf21000 (8388608 bytes)
*** Preparing to test memory region 7f995c722000 (8388608 bytes)
*** Preparing to test memory region 7f995cf23000 (8388608 bytes)
*** Preparing to test memory region 7f995d724000 (8388608 bytes)
*** Preparing to test memory region 7f995df25000 (8388608 bytes)
*** Preparing to test memory region 7f995e726000 (8388608 bytes)
*** Preparing to test memory region 7f995ef27000 (8388608 bytes)
*** Preparing to test memory region 7f995f728000 (8388608 bytes)
*** Preparing to test memory region 7f995ff29000 (8388608 bytes)
*** Preparing to test memory region 7f996072a000 (8388608 bytes)
*** Preparing to test memory region 7f9960f2b000 (8388608 bytes)
*** Preparing to test memory region 7f996172c000 (8388608 bytes)
*** Preparing to test memory region 7f9961f2d000 (8388608 bytes)
*** Preparing to test memory region 7f996272e000 (8388608 bytes)
*** Preparing to test memory region 7f9962f2f000 (8388608 bytes)
*** Preparing to test memory region 7f9963730000 (8388608 bytes)
*** Preparing to test memory region 7f9963f31000 (8388608 bytes)
*** Preparing to test memory region 7f9964732000 (8388608 bytes)
*** Preparing to test memory region 7f9964f33000 (8388608 bytes)
*** Preparing to test memory region 7f9965734000 (8388608 bytes)
*** Preparing to test memory region 7f9965f35000 (8388608 bytes)
*** Preparing to test memory region 7f9966736000 (8388608 bytes)
*** Preparing to test memory region 7f9966f37000 (8388608 bytes)
*** Preparing to test memory region 7f9967738000 (8388608 bytes)
*** Preparing to test memory region 7f9967f39000 (8388608 bytes)
*** Preparing to test memory region 7f996873a000 (8388608 bytes)
*** Preparing to test memory region 7f9968f3b000 (8388608 bytes)
*** Preparing to test memory region 7f996973c000 (8388608 bytes)
*** Preparing to test memory region 7f9969f3d000 (8388608 bytes)
*** Preparing to test memory region 7f996a73e000 (8388608 bytes)
*** Preparing to test memory region 7f996af3f000 (8388608 bytes)
*** Preparing to test memory region 7f996b740000 (8388608 bytes)
*** Preparing to test memory region 7f996bf41000 (8388608 bytes)
*** Preparing to test memory region 7f996c742000 (8388608 bytes)
*** Preparing to test memory region 7f996cf43000 (8388608 bytes)
*** Preparing to test memory region 7f996d744000 (8388608 bytes)
*** Preparing to test memory region 7f996df45000 (8388608 bytes)
*** Preparing to test memory region 7f996e746000 (8388608 bytes)
*** Preparing to test memory region 7f996ef47000 (8388608 bytes)
*** Preparing to test memory region 7f996f748000 (8388608 bytes)
*** Preparing to test memory region 7f996ff49000 (8388608 bytes)
*** Preparing to test memory region 7f997074a000 (8388608 bytes)
*** Preparing to test memory region 7f9970f4b000 (8388608 bytes)
*** Preparing to test memory region 7f997174c000 (8388608 bytes)
*** Preparing to test memory region 7f9971f4d000 (8388608 bytes)
*** Preparing to test memory region 7f997274e000 (8388608 bytes)
*** Preparing to test memory region 7f9972f4f000 (8388608 bytes)
*** Preparing to test memory region 7f9973750000 (8388608 bytes)
*** Preparing to test memory region 7f9973f51000 (8388608 bytes)
*** Preparing to test memory region 7f9974752000 (8388608 bytes)
*** Preparing to test memory region 7f9974f53000 (8388608 bytes)
*** Preparing to test memory region 7f9975754000 (8388608 bytes)
*** Preparing to test memory region 7f9975f55000 (8388608 bytes)
*** Preparing to test memory region 7f9976756000 (8388608 bytes)
*** Preparing to test memory region 7f9976f57000 (8388608 bytes)
*** Preparing to test memory region 7f9977758000 (8388608 bytes)
*** Preparing to test memory region 7f9977f59000 (8388608 bytes)
*** Preparing to test memory region 7f997875a000 (8388608 bytes)
*** Preparing to test memory region 7f9978f5b000 (8388608 bytes)
*** Preparing to test memory region 7f997975c000 (8388608 bytes)
*** Preparing to test memory region 7f9979f5d000 (8388608 bytes)
*** Preparing to test memory region 7f997a75e000 (8388608 bytes)
*** Preparing to test memory region 7f997b1fc000 (4096 bytes)
*** Preparing to test memory region 7f997b1fe000 (8388608 bytes)
*** Preparing to test memory region 7f997b9ff000 (8388608 bytes)
*** Preparing to test memory region 7f997c200000 (10485760 bytes)
*** Preparing to test memory region 7f997d000000 (2097152 bytes)
*** Preparing to test memory region 7f997d786000 (16384 bytes)
*** Preparing to test memory region 7f997d9a3000 (16384 bytes)
*** Preparing to test memory region 7f997e070000 (16384 bytes)
*** Preparing to test memory region 7f997e0d3000 (4096 bytes)
.O.O.O.O.O.[1]    18757 segmentation fault (core dumped)  redis-server redis_search.conf

**Comment by dvirsky** [comment]
Thanks, this is actually a recent regression. I've added a test to avoid that. 

Re what you tried to achieve - ATM the results are limited to 1M, but it makes no sense to run a limitless result as we sort the results by a scoring funcion. In the future we will add an iterative scan request that just returns unordered results (or ordered by insertion actually), and lets you iterate over them. this will be used for aggregations.
