### ISSUE TITLE
Incorrect result on AND condition with exact search

### ISSUE THREAD

**Issue by arora-kushal** [RedisLabsModules/RediSearch#162]
Hi,

We are facing an issue in RediSearch 0.21.0. The command is giving wrong output.

Could anyone please help me on this. The reproduction steps are mentioned below.

Thanks !

## **Commands to setup**:

`
"FT.CREATE" "HomeStat" "SCHEMA" "FirstName" "TEXT" "SORTABLE" "CaseStatusName" "TEXT" "SORTABLE"

"FT.ADD" "HomeStat" "ss:d:{#ClientList}60" "1" "FIELDS" "FirstName" "JIMMY ASCETTA" "CaseStatusName" "Closed" 
"FT.ADD" "HomeStat" "ss:d:{#ClientList}90" "1" "FIELDS" "FirstName" "JAMES SHAW" "CaseStatusName" "Open" 
"FT.ADD" "HomeStat" "ss:d:{#ClientList}100" "1" "FIELDS" "FirstName" "CAMILLE WALTON" "CaseStatusName" "Open" 
"FT.ADD" "HomeStat" "ss:d:{#ClientList}250" "1" "FIELDS" "FirstName" "JOSEPH CASTRO" "CaseStatusName" "Open" 
"FT.ADD" "HomeStat" "ss:d:{#ClientList}5170" "1" "FIELDS" "FirstName" "JOSEPH BARR" "CaseStatusName" "Open"
 `

**Search Command 1**: "FT.SEARCH" "HomeStat" "@FirstName:(\"JOSEPH BARR\")"
**Expected output** : "ss:d:{#ClientList}5170" 
**Actual Output (CORRECT)**: 
1) (integer) 1
2) "ss:d:{#ClientList}5170"
3) 1) "FirstName"
   2) "JOSEPH BARR"
   3) "CaseStatusName"
   4) "Open"

**Search Command 2** : "FT.SEARCH" "HomeStat" "open @FirstName:(\"JOSEPH BARR\")"
**Explaination:** Search for record with word "open" AND FirstName = "JOSEPH BARR"
**Expected Output**: "ss:d:{#ClientList}5170" 
**Actual Output (INCORRECT)** : The below output should not give us the second result. i.e. "ss:d:{#ClientList}250"
Output:
1) (integer) 2
2) "ss:d:{#ClientList}5170"
3) 1) "FirstName"
   2) "JOSEPH BARR"
   3) "CaseStatusName"
   4) "Open"
4) "ss:d:{#ClientList}250"
5) 1) "FirstName"
   2) "JOSEPH CASTRO"
   3) "CaseStatusName"
   4) "Open"

[RedisIssue_Info.txt](https://github.com/RedisLabsModules/RediSearch/files/1302727/RedisIssue_Info.txt)

**Comment by dvirsky** [comment]
Thanks for reporting and providing a reproducible scenario. I'll check it and have a fix soon.

**Comment by dvirsky** [comment]
@arora-kushal Thanks for this, it affected not only exact searches, very good find. Fixed now.

**Comment by dvirsky** [comment]
(pull from master)

**Comment by arora-kushal** [comment]
Thank you for fixing it. Its working now.

**Comment by dvirsky** [comment]
cool. thanks again for this report. I need to make more fuzzer like tests to validate edge cases of the engine like this one
