### ISSUE TITLE
Question about scoring function

### ISSUE THREAD

**Issue by deivarezserve** [RedisLabsModules/RediSearch#167]
Hi Dvir,

I am still fighting my custom scoring function here, as I am coding blindly because I was not able to get my GDB to work with my VM yet.

What I am trying to achieve now is to give a higher score for results that have a specific field in the payload matching the searched string.

For instance, if the search is:
```
FT.SEARCH stores shirt @city:Chicago @state:Illinois SCORER CUSTOM_SCORER
```

I would want a store with a shirt product (products is a field in the index) to have a higher score.

So what I have in the scoring function is:
```
/* Calculate document score for each result */
double customScorer(RSScoringFunctionCtx *ctx, RSIndexResult *h, RSDocumentMetadata *dmd,
                double minScore) {
  double score = 0;
  // Matching products.
  char needle[] = ",\"products";
  char* pos = strstr(dmd->payload->data, needle);
  if (pos) {
    char* next = strstr(dmd->payload->data, ",\"address");
    if (next) {
      char* products = NULL;
      strncpy(products, pos + strlen(needle), next - (pos + strlen(needle)));
      if (strstr(products, h->term.term->str)) {
        score += 7;
      }
    }
  }
  // Other criteria
  ...
  return score/10;
}
``` 

Am I using h->term correctly? In this case, would it be equal to "shirt"? Any tips or advice you can provide? Any help would be much appreciated... 

Also, I've noticed some printf in your default.c, which leads me to believe you once used them to debug your scoring functions, can you tell me how?

Best regards,

**Comment by deivarezserve** [comment]
Got the function to work by doing some small changes to strncopy:

```
/* Calculate document score for each result */
double customScorer(RSScoringFunctionCtx *ctx, RSIndexResult *h, RSDocumentMetadata *dmd,
                double minScore) {
  double score = 0;
  // Matching products.
  char needle[] = ",\"products";
  char* pos = strstr(dmd->payload->data, needle);
  if (pos) {
    char* next = strstr(dmd->payload->data, ",\"address");
    if (next) {
      char products[next -pos];
      strncpy(products, pos, next - pos);
      if (strstr(products, h->term.term->str)) {
        score += 7;
      }
    }
  }
  // Other criteria
  ...
  return score/10;
}
```

**Comment by deivarezserve** [comment]
Now I have a new issue... anytime I execute it together with a numeric filter, it kills my Redis. Any ideas? Any reason why a numeric filter would not work with a custom scoring function?

**Comment by deivarezserve** [comment]
My function was missing this:
```
if (h->type == RSResultType_Term && h->term.term != NULL && strlen(h->term.term->str) > 0) {
```

**Comment by dvirsky** [comment]
@deivarezserve Might be a good idea to make this check accessible and more self evident maybe. i.e. 

```c
int RSIndexResult_IsValidTerm(RSIndexResult *r);
```

WDYT?

**Comment by deivarezserve** [comment]
I'm not sure if it's needed, to be honest.

I have one more question though. When I run my query like this:
```
FT.SEARCH stores shirt @city:Chicago @state:Illinois SCORER CUSTOM_SCORER
```

I want to just give a higher score to results that have "shirt" in the payload. But h->term.term->str returns me all terms (shirt, Chicago and Illinois). Is there any way to differentiate a term that is not coming from a @ query?

Regards,

**Comment by deivarezserve** [comment]
My way out of this dilemma was to look for a match in the payload just for the first term in RSIndexResult.

```
int _matchingProductsRecursive(RSIndexResult *r, RSDocumentMetadata *dmd) {
  if (r->type == RSResultType_Term && r->term.term && strlen(r->term.term->str) > 0) {
    // Matching products.
    char needle[] = ",\"products";
    char* pos = strstr(dmd->payload->data, needle);
    if (pos) {
      char* next = strstr(dmd->payload->data, ",\"address");
      if (next) {
        char products[next -pos];
        strncpy(products, pos, next - pos);
        if (strstr(products, h->term.term->str)) {
          return 1;
        }
      }
    }
  }
  if (r->type & (RSResultType_Intersection | RSResultType_Union)) {
    // Only check for matching products in the first term (search keyword).
    if (_matchingProductsRecursive(r->agg.children[0], dmd)) {
      return 1;
    }
  }
  return 0;
}

double _defaultScorer(RSScoringFunctionCtx *ctx, RSIndexResult *h, RSDocumentMetadata *dmd,
                double minScore, int withKeyword) {
  double score = 0;
  // Matching products
  score += 7 * _matchingProductsRecursive(h, dmd);
  // Other criteria
  ...
  return score/10;
}
```

**Comment by dvirsky** [comment]
Putting the field name in a result is possible, I'll look into that.

**Comment by deivarezserve** [comment]
Thank you!
