### ISSUE TITLE
FT.SEARCH returns an error when one of the queries in a union is a stopword

### ISSUE THREAD

**Issue by vruizext** [RedisLabsModules/RediSearch#169]
I don't know if this is an expected behaviour, I find strange to get an error in these queries. To avoid the error I would need to clean up the query in the client filtering out the stopwords, which IMO it's something that should be transparent for the client.

I'm using last version in master.

```
127.0.0.1:6380> FT.SEARCH beatz "foo|bar" limit 0 1
1) (integer) 0

127.0.0.1:6380> FT.SEARCH beatz "for|bar" limit 0 1
(error) Syntax error at offset 3 near 'for'

127.0.0.1:6380> FT.SEARCH beatz "the|bar" limit 0 1
(error) Syntax error at offset 3 near 'the'

127.0.0.1:6380> FT.SEARCH beatz "for|bar" NOSTOPWORDS limit 0 1
1) (integer) 0
```

**Comment by dvirsky** [comment]
Fidxed in #b01ecba0827df782c6996719e27c1bcdc1675f2f
