### ISSUE TITLE
Complex queries of OR and AND doesn't work as expected 

### ISSUE THREAD

**Issue by eitanshapiro** [RedisLabsModules/RediSearch#17]
I see that AND queries work and OR queries work.
However AND and OR together doesn't work as expected.
Please advise !

"FT.SEARCH" "vc" "(7F647D08|7F647D08)" "NOCONTENT" "VERBATIM" "NOSTOPWORDS" "LIMIT" "0" "1000000"
25,246 results

"FT.SEARCH" "vc" "(7E765B38|7E765B38)" "NOCONTENT" "VERBATIM" "NOSTOPWORDS" "LIMIT" "0" "1000000"
11,468 results

"FT.SEARCH" "vc" "(7F647D08|7F647D08)(7E765B38|7E765B38)" "NOCONTENT" "VERBATIM" "NOSTOPWORDS" "LIMIT" "0" "1000000"
1) (integer) 1
2) "v:x544tok"

"FT.SEARCH" "vc" "(7F647D08)(7E765B38)" "NOCONTENT" "VERBATIM" "NOSTOPWORDS" "LIMIT" "0" "1000000"
9,555 results

**Comment by dvirsky** [comment]
Fixed it, and added a test case for this, thanks for noticing. 

Please pull the master, `make clean release` and verify.

**Comment by mheiber** [comment]
For reference, the fix was in this commit: https://github.com/RedisLabsModules/RediSearch/commit/da10bc7f319502afe108c8d38609ca3292bdf7f7
