### ISSUE TITLE
Execution Time-Out when running with large search arguements on FT.SEARCH.

### ISSUE THREAD

**Issue by nreddipalle** [RedisLabsModules/RediSearch#173]
I am testing with the latest version of redis and redisearch. 
My FT search query is something similar. It works fine when sending small no. of arguements for `ProjectID` but is throwing an error when sending around 10,000 values for ProjectID.
![image](https://user-images.githubusercontent.com/28302399/30815155-4d75ee56-a1e0-11e7-8ee7-707779221fa4.png)
Complete Input is similar to this:
((@ProjectID:(25359|25360|25611|25612|22122|22123|22141|22142|22156|22157|22171|22172|22173|22187|22188|22200|22201|22215|22216|22231|22232|25709|25710|25711|25712|25713|25714|25715|25718|25719|25722|25723|25724|25725|25726|25727|25728|25729|25730|9890|9891|9892|9893|9894|9895|9896|9897|9898|9899|9900|9901|9902|9903|9904|9905|9906|9907|9908|9909|9910|9911|9912|9913|9914|9915|9916|9917|9918|9919|9920|9921|9922|9923|10138|10139|10141|10142|10143|10144|10145|10146|10147|10148|10149|10150|10151|10152|10153|10154|10155|10156|10158|10159|10160|10161|10162|10163|10164|10166|10167|10168|10169|10170|10171|10172|10173|10174|10175|10176|10177|10319|10320|10321|10322|10323|10324|10325|10326|10327|10328|10329|10330|10331|10332|10333|10334|10335|10336|10337|10338|10339|10340|10341|10342|10343|10345|10346|10347|10348|10349|10350|10351|10352|10353|10354|10356|10357|10590|10591|10592|10593|10594|10595|10596|10597|10599|10600|10601|10602|10603|10604|10605|10606|10607|10608|10609|10610|10611|10612|10614|10615|10616|10617|10618|10619|10621|10622|10859|10860|10861)&(-@TicketType2ID:(17|18))))|(@AllowedUsers:3415)

**Comment by dvirsky** [comment]
The complexity of a union query is roughly the size of all the sets in it combined. This is not a bug, the timeout is coming from your client, you can increase it, but if I might add, sending 10k sized union is impractical and you are probably modelling it wrong.

**Comment by nreddipalle** [comment]
Thanks for the response. What is the best way if I want to search for TicketIDs as part of a list of ProjectIDs. **My requirement is to output Tickets that has (AllowedUsers =3415) OR (ProjectID in one of the IDs & TicketType2ID NOT IN (17,18)).**

**Comment by nreddipalle** [comment]
BTW - ProjecTID is just one of the field. Is there an option like INKEYS where I could pass in list of ProjectIDs.

**Comment by dvirsky** [comment]
If the project list is not completely dynamic, or can it be pre-defined as a tag or group something like that? i.e. pre-define a  project group, and index the "groups" field of a ticket as all the goups it belongs to. 

You need to narrow your space, the complexity of union (not just in redisearch) is like repeating the query for each group and concatenating those 10k queries into one result. It's really slow. 

Another option would be to implement a filtering function using the scorer API, but unless you're fluent in C I wouldn't go into that.

**Comment by nreddipalle** [comment]
I already add ProjectID as one of  the fields to each ticket. Each Ticket contains ProjectID as a field and I need to retrieve the list of TicketIDs based on UserAccessibleProjects which I need to pass. These are the fields as part of my index. 
index = new RediSearch.FieldWeights
        {
            new RediSearch.FieldWeight("TicketID", RediSearch.FieldType.NUMERIC,Sortable:true),
            new RediSearch.FieldWeight("TickID", RediSearch.FieldType.TEXT,35.0),
            new RediSearch.FieldWeight("Title", RediSearch.FieldType.TEXT,30.0),
            new RediSearch.FieldWeight("Description", RediSearch.FieldType.TEXT,20.0),
            new RediSearch.FieldWeight("ProjectID", RediSearch.FieldType.TEXT),
            new RediSearch.FieldWeight("TicketType2ID", RediSearch.FieldType.TEXT),
            new RediSearch.FieldWeight("Tag", RediSearch.FieldType.TEXT ,10.0),
            new RediSearch.FieldWeight("Comment", RediSearch.FieldType.TEXT,2.0)
           ,new RediSearch.FieldWeight("AllowedUsers", RediSearch.FieldType.TEXT,4.0)
           ,new RediSearch.FieldWeight("AssignedToUser",RediSearch.FieldType.TEXT,10.0)

**Comment by dvirsky** [comment]
Won't AllowedUsers cover that?

**Comment by nreddipalle** [comment]
Each User has access to certain Projects and each ticket is associated with a project. If I include this logic within AllowedUsers for every ticket, the memory consumption is too much as I faced in issue #114. 
So I seperated the logic so that I check for AllowedUsers and also get UserAccessibleProjects and pass it to check within ProjectID field to retrieve all the ticketIDs. Hope I am clear. The memory it took for a million rows is 500MB with this approach.

**Comment by dvirsky** [comment]
BTW what is the timeout defined in the client?

**Comment by nreddipalle** [comment]
I did not explicitly define it. This is my config file.


[redis conf.zip](https://github.com/RedisLabsModules/RediSearch/files/1330998/redis.conf.zip)

**Comment by dvirsky** [comment]
Okay, two main options besides implementing your own filter as an extension (which is basically like adding HAVING):

1. Use user-groups and not just users, and make sure the user list per ticket is small, and most permissions are managed by grops. This is how github permissions work for example. Projects are mostly managed by groups, and you can add exceptions for a user or two. That keeps the index small and fast. 

2. I intend to implement "tag fields" (I think we discussed that), which will be very compact in memory, requiring roughly one byte per user per ticket, so it will probably be efficient enough for you. This will allow you to just index all user ids. I can make it a higher priority and have it out in about a week. 

WDYT?

Re timeout - it's defined in the client, not in redis. Redis has no timeouts for queries.

**Comment by nreddipalle** [comment]
Thanks for the response. I will look forward for the No.2 enhancement. Meanwhile I will see whether I could build something to work like No.1. Thanks again.

**Comment by dvirsky** [comment]
Cool. 1 is just like having much less users, basically. You assume that most users need similar perimssions. It does require a change in business logic however.

**Comment by nreddipalle** [comment]
Unfortunately No.1 is not working out great for me. I created multiple user-groups but eventually the number of groups I need to pass for a user comes around 200-250 (combined)  in some cases which is causing latency in execution.

**Comment by dvirsky** [comment]
Okay, I will implement tag or property fields that will consume far less
memory and will allow filtering by user ids.

**Comment by nreddipalle** [comment]
Thanks.

**Comment by nreddipalle** [comment]
please notify once No.2 is pushed to master. Thanks for looking.

**Comment by nreddipalle** [comment]
Hello @dvirsky any ETA on release of No.2 stated above?? Thanks.

**Comment by dvirsky** [comment]
hopefully next week.

**Comment by nreddipalle** [comment]
@dvirsky Is this enhancement coming this week??

**Comment by dvirsky** [comment]
@nreddipalle no, sadly I'm stuck on another thing that is taking longer than I expected.

**Comment by nreddipalle** [comment]
@dvirsky any ETA on when this could come out??

**Comment by nreddipalle** [comment]
@dvirsky any ETA on this enhancement??

**Comment by dvirsky** [comment]
Hi, sorry, I was away travelling for the past week or so. I hope to finally
finish it this coming week.

**Comment by nreddipalle** [comment]
NP. @dvirsky does the current release 0.90 contains this enhancement??

**Comment by dvirsky** [comment]
@nreddipalle you can now try the `attr_index` branch, it includes this.
