### ISSUE TITLE
Different Results on FT.SEARCH for same input set...

### ISSUE THREAD

**Issue by nreddipalle** [RedisLabsModules/RediSearch#174]
![image](https://user-images.githubusercontent.com/28302399/30817014-a319fdb6-a1e5-11e7-8c40-df79b371dee6.png)
ft.Explain for both the inputs:

ft.explain Ticket ((@ProjectID:(9891|9892|9893|9894|9895))&(-@TicketType2ID:(17|18)))|(@AllowedUsers:3415) NOCONTENT
"@ProjectID|AllowedUsers:UNION {
  @ProjectID:INTERSECT {
    @ProjectID:UNION {
      9891
      9892
      9893
      9894
      9895
    }
    @ProjectID:NOT{
      @TicketType2ID:UNION {
        17
        18
      }
    }
  }
  @AllowedUsers:3415
}
"
ft.explain Ticket ((-@TicketType2ID:(17|18))&(@ProjectID:(9891|9892|9893|9894|9895)))|(@AllowedUsers:3415) NOCONTENT
"UNION {
  INTERSECT {
    NOT{
      @TicketType2ID:UNION {
        17
        18
      }
    }
    @ProjectID:UNION {
      9891
      9892
      9893
      9894
      9895
    }
  }
  @AllowedUsers:3415
}
"

**My expection is both to provide same results. My requirement is to output Tickets that has (AllowedUsers =3415) OR (ProjectID in one of the IDs & TicketType2ID NOT IN (17,18)).**

**Comment by dvirsky** [comment]
Should be fixed now in master (as long as EXPLAIN shows logically identical trees)
