### ISSUE TITLE
data created by redisearch  can not synchronize from master to slave

### ISSUE THREAD

**Issue by spongeliu** [RedisLabsModules/RediSearch#176]

**Comment by dvirsky** [comment]
Please provide an example, I cannot recreate this, the data I'm creating gets synchronized perfectly. Are you sure the module is loaded, and in the same version in both master and slave?

**Comment by dvirsky** [comment]
Ok, I found the problem, it was not in actual sync but in replicating commands in real time. works now (in master)

**Comment by dvirsky** [comment]
Also releases in 0.22.2 and pushed to docker hub
