### ISSUE TITLE
Are "a" and "of" reserved keywords?

### ISSUE THREAD

**Issue by jichifly** [RedisLabsModules/RediSearch#177]
It seems when a query containing "a" or "of", it will crash the parser.
Can we fully escape an input string during parsing? Or, maybe, can we pass in a json blob in the future to enforce sanity of the input instead of relying research's manually written parser?

```
127.0.0.1:6379> ft.search ner_topic_en '@topic_en:"a"'
(error) Syntax error at offset 12 near 'a'

127.0.0.1:6379> ft.search ner_topic_en '@topic_en:"c"'
1) (integer) 0
127.0.0.1:6379> ft.search ner_topic_en '@topic_en:"c"'
1) (integer) 0
127.0.0.1:6379> ft.search ner_topic_en '@topic_en:"of a"'
(error) Syntax error at offset 15 near 'a'

127.0.0.1:6379> ft.search ner_topic_en '@topic_en:"of"'
(error) Syntax error at offset 13 near 'of'

127.0.0.1:6379> ft.search ner_topic_en '@topic_en:"of b"'
1) (integer) 0
127.0.0.1:6379> ft.search ner_topic_en '@topic_en:"of"'
(error) Syntax error at offset 13 near 'of'
```

**Comment by dvirsky** [comment]
They are stopwords, and meaningless in the context of the search. This shouldn't be a parse error, but in any case you can just control the stopword list when creating an index. And no, there will never be json support, and the query parser is not manually written BTW. 

See the documentation for FT.CREATE on how to provide your own stopwords. http://redisearch.io/Commands/#ftcreate

**Comment by dvirsky** [comment]
The error in the parser has been fixed as well, and it now doesn't return sytnax errors in such a case even if the terms are stop words. 

Also, I've added proper documentation of how stopwords work in RediSearch: http://redisearch.io/Stopwords/
