### ISSUE TITLE
Incostante number of keys on replication

### ISSUE THREAD

**Issue by mattboban** [RedisLabsModules/RediSearch#180]
This is possibly related to https://github.com/RedisLabsModules/RediSearch/issues/176

**environment**
Redis v4.0.2
RediSearch 0.21.2
3 Redis instances (1 master, 2 slaves) on the same Ubuntu 16.04 box
Replication - disk-based

**noticed behaviour**
When index data is replicated from master to slave, data/keys appears to be missing in slaves. I did a simple test on a small data set that, when indexed, yields 2329 keys on the master, but 2270 on slaves (consistent on both slaves). A larger dataset test yields 58819 keys on master and 57784 on one slave and 57053. Doing a direct search on the slave yields a lower number of results than on master, naturally.
There also appears to be an issue of data quality as running  a search on master yields expected results:

```
ft.search menu-api_prod:restaurant-index "bei @city:Nashville" withscores return 2 name city limit 0 1

1) (integer) 1
2) "12605036"
3) "1.1666666666666665"
4) 1) "name"
   2) "Bei Jing Chinese Restaurant"
   3) "city"
   4) "Nashville"
```

yet the same search on the slave appears to reformat the data (in this case the name and the score).

```
ft.search menu-api_prod:restaurant-index "bei @city:Nashville" withscores return 2 name city limit 0 1
1) (integer) 1
2) "12605036"
3) "1.1875"
4) 1) "name"
   2) "bei\x00jing\x00chinese\x00restaurant"
   3) "city"
   4) "Nashville"
```

You can appreciate how huge an issue this is from a replication/data consistency standpoint.

**replication of the issue with base redis functions**
I did an additional test with just standard SET commands, on similarly sizes datasets and the replication is consistent and as expected, with no key number/dbsize difference across the slaves. So it appears to be contained to the RediSearch module.

**additional observation**
When forcing a master <--> slave sync by restarting the slave instances, the data returns to the consistent state across master and all slaves. This is naturally due to the slaves being synced from the masters .rdb.

@dvirsky let me know what additional data or help I can provide, as this is a high priority issue from my end.

Thanks

**Comment by dvirsky** [comment]
It actually doesn't sound like a hard thing to fix. I know what's happening here.

**Comment by dvirsky** [comment]
@mattboban it's fine now. Verify and I'll release a new version with the fix. @mnunberg this will slow down indexing a bit, as we copy each input string now, but there's no way around it. Also, we need to add replication tests to pytest

**Comment by mattboban** [comment]
@dvirsky looks good on my end, after the first extensive batch of testing. I'll do one more round, with a 1m+ indexed  keys next week (to confirm this on large data sets), but I see no reason not to merge this into a release.

Thanks for a very quick turnaround.
