### ISSUE TITLE
Exact numeric matches in query

### ISSUE THREAD

**Issue by stockholmux** [RedisLabsModules/RediSearch#181]
Say you have a field that is NUMERIC and you want to find the exact value - currently you must set bounds which seems unnatural.

Example - finding an item with a `cost` of 99:
```
@cost:[99 99]
```
Would it be possible to just be able to filter by a single value?
```
@cost:99
```

**Comment by dvirsky** [comment]
no, it would lead to complication of the parser which is already too complicated. This should be abstracted by the client libraries IMO
