### ISSUE TITLE
Accept non-UTF8 encodings

### ISSUE THREAD

**Issue by mnunberg** [RedisLabsModules/RediSearch#184]
Allow non-UTF8 encoded documents to be given to RediSearch. The document should be converted to UTF8 on the fly.

```
FT.ADD {index} {name} {score} [ENCODING {UTF16}|{UTF8}|{UTF32}]
```

Current behavior (prior to this change) is to just blindly assume utf8 encoding.

Additional considerations:

* In the future we may choose to store the document in the desired encoding (as a space/time trade-off) - _especially_ if we know that the utf16 version is more space efficient than the utf8 version. But this would require adding an encoding field to the metadata
* Currently we save the document in the main thread (in module.c). In the future it may be better to defer the conversion to the tokenizing thread, and saving in the indexer thread. This would really depend on how common this option is used.

**Comment by dvirsky** [comment]
@atris how about this one?

**Comment by atris** [comment]
@dvirsky Sure. Please let me know how to get started

**Comment by dvirsky** [comment]
Just follow the code of AddDocumentCommand, and add support for this extra argument

**Comment by dvirsky** [comment]
@atris have you looked at the code? I'd do this pretty much at the beginning of the indexing flow. Just detect the encoding if it exists, and use the built in unicode library (libnu) to convert strings to utf-8 if needed.

**Comment by mnunberg** [comment]
The goal of this issue was to optionally use non-utf8 encodings for space efficiency, but utf8 is usually quite efficient; so closing.
