### ISSUE TITLE
Seg faults on ingestion

### ISSUE THREAD

**Issue by stockholmux** [RedisLabsModules/RediSearch#188]
When trying out the benchmark, Redis keeps on throwing seg faults. 

See issue on the benchmark for further details RedisLabs/RediSearchBenchmark#2

**Comment by mnunberg** [comment]
Should be fixed with this commit:

https://github.com/RedisLabsModules/RediSearch/commit/d5de1fe52fd3e932fb3b63e75314cc20702e8ffe
