### ISSUE TITLE
Incorrect result on prefix matches

### ISSUE THREAD

**Issue by arora-kushal** [RedisLabsModules/RediSearch#197]
The document (http://redisearch.io/Query_Syntax/) contains "Common SQL Predicates to RediSearch mapping". However, we are getting different results for below condition:

SQL Condition :  WHERE name LIKE 'john lenn%'

is eqvivalent to 

RediSearch Equivalent : @name:"john lenn*"     
---------------------------------------------------------------
Test Results:

select * from [test].[dbo].[Person] 

### Output: 
john lennister
john daenerys lennister

SELECT * FROM [test].[dbo].[Person] where Name LIKE 'john lenn%'

### Output: 
john lennister

![image](https://user-images.githubusercontent.com/8510977/32092799-9bc0a2fe-bb17-11e7-952c-62d99e321dce.png)

127.0.0.1:6379>  "FT.CREATE" "VVV" "SCHEMA" "Name" "TEXT" "SORTABLE" 
OK
127.0.0.1:6379> "FT.ADD" "VVV" "ss:d:{#BuildingDetail}1" "1" "FIELDS" "Name" "john lennister"
OK
127.0.0.1:6379> "FT.ADD" "VVV" "ss:d:{#BuildingDetail}2" "1" "FIELDS" "Name" "john daenerys lennister"
OK
127.0.0.1:6379> FT.SEARCH VVV @Name:"john lenn*"
1) (integer) 2
2) "ss:d:{#BuildingDetail}1"
3) 1) "Name"
   2) "john lennister"
4) "ss:d:{#BuildingDetail}2"
5) 1) "Name"
   2) "john daenerys lennister"
127.0.0.1:6379> FT.explain VVV @Name:"john lenn*"
"@Name:INTERSECT {\n  @Name:john\n  @Name:PREFIX{lenn*}\n}\n"

Please suggest that what is the best way to achieve results equivalent to SQL query.

**Comment by arora-kushal** [comment]
And following command throws error

127.0.0.1:6379> FT.search VVV @Name:"\"john lenn*\""
(error) Syntax error at offset 16 near 'lenn'

**Comment by kilianc** [comment]
@arora-kushal why are you escaping `"` are you searching for the string `"john lenn"` quotes included?

**Comment by dvirsky** [comment]
Actually the documentation is wrong, it's not the correct mapping if you have more than one term, I will change that. 
Having exact match within a quoted query can be supported actually, but will be very slow. You can always do something like `FT.SEARCH "john len*" SLOP 0 INORDER`

**Comment by arora-kushal** [comment]
@dvirsky If we are searching/filtering in 2 different columns, Is it possible to use SLOP/INORDER with just one column (not entire search query) ?

**Comment by kilianc** [comment]
@arora-kushal #212

**Comment by itamarhaber** [comment]
This should now (v1.2.0) be doable also for sub queries as well. Closing.
