### ISSUE TITLE
Empty summary for fields that do not contain the search terms

### ISSUE THREAD

**Issue by dvirsky** [RedisLabsModules/RediSearch#201]
Let's say I have a document with 2 fields, foo and bar. I search for a term appearing only in foo but I want to summarize bar.  Right now bar returns empty. 

In such a case we should create a snippet with the given total summary length (num_frags * frag_len), but not return an empty field.

Same goes for a case where a field to be summarized contains only, let's say, 1 of 3 terms. We should return 1 frament but perhaps larger. 

BTW This is partly why I wanted to the user parameter to be the total length and not the fragment length.

**Comment by mnunberg** [comment]
Where exactly should the summary begin from? Perhaps we need two summary-like directives? the `SUMMARIZE` specifically contextualizes somethiing, and maybe it should be named that. It's designed to help the user see how the document relates to his search terms. In the case where a match is not found, the summary is different, and would be to guess what exactly the document contains

**Comment by dvirsky** [comment]
It should take the beginning of the document and trim it to be the length that a summary would be

**Comment by mnunberg** [comment]
Ok, this is done as requested.

**Comment by dvirsky** [comment]
Did you add a test case for it? (and for the case of not having offset vectors in the index)

If so, we can finally release a version with HL support

**Comment by mnunberg** [comment]
I did add a test case for it; I'm working on the NOHL stuff as well, but that's another issue

**Comment by dvirsky** [comment]
ok, waiting for NOHL and we'll release this tomorrow.
