### ISSUE TITLE
Auto-complete suggestions associate with docId

### ISSUE THREAD

**Issue by suze521** [RedisLabsModules/RediSearch#209]
Auto-complete suggestions now just returns the suggested string. How do I associate with docId?

**Comment by dvirsky** [comment]
The auto-suggest is independent from the search index and needs to be built independently, as you can see. 
You have three options:

1. suggestions can have payloads, which can be any string you want, or even whole documents as JSON (they are not searchable though). So just put whatever payload you want for a suggestion.

2. The index itself supports prefix searches disconnected from the auto-complete. You can use a prefix query (`FT.SEARCH idx "foo*"`) to search documents containing a prefix.

3. My preferred method: take the top completion suggesion and run that as a search query.
