### ISSUE TITLE
Per field SLOP and INORDER

### ISSUE THREAD

**Issue by kilianc** [RedisLabsModules/RediSearch#212]
At the moment when setting `SLOP` and `INORDER` they are applied globally to the entire query and @dvirsky mention that `SLOP` is a cumulative count.

`INORDER` plays a big role when we search for a combination of tags and phrase but I know that a new tag search is landing soon and the problem may be mitigated.

On the other end as of today, it is impossible to search `@title:foo bar @body:hello there` and apply a different `SLOP` for `title` and `body` and only apply `INORDER` for `text`.

**Comment by dvirsky** [comment]
Good idea. The problem will mainly be expressing this in the query syntax. And generalising the problem - how to express parameters for different query sub-trees. 

I came up with the following general syntax for per query clause/subquery parameters: simply adding, inside the query clause, parameters and values in the format of `${param}:{val} ... ;`

so to express slop and inorder per different clauses you would do:

```
(
   @body:(foo|bar)
   $slop: 3;
   $inorder: true;
)
(
  @title:hello world
  $slop:0;
)
```

and so forth...

Current things we'd like to support with parameters:
1. SLOP
2. INORDER
3. score boosting - i.e. make specific clauses affect the score of the results more than others. (e.g. `$weight: 5.0;`)
4. score fixing: make any hit within a given clause contribue exactly a specific score to the ranking function. (e.g. `$score: 2;`)

**Comment by salt4pommes** [comment]
Hi!

With the release of 0.99.0 you said that no new features will be added.
So this feature will not be implemented until 1.0?

Thank you for this great project :1st_place_medal:

**Comment by dvirsky** [comment]
Yes, right now we are in feature freeze for a while, but not for long...

**Comment by dvirsky** [comment]
Added in 1.2.0
