### ISSUE TITLE
Description for commands

### ISSUE THREAD

**Issue by topilski** [RedisLabsModules/RediSearch#214]
Hi, please add description and some examples for next commands:
```
FT.TERMADD
FT.SAFEADD
FT.SAFEADDHASH
FT.DTADD
FT.SETPAYLOAD
```

**Comment by dvirsky** [comment]
These are undocumented in purpose as they are intended for use by the AOF log only. At least some of them can cause damage to the index if used incorrectly. 

The only one worth mentioning in the documentation is SAFEADD which might be useful for MULTI an Lua indexing.

**Comment by topilski** [comment]
Hi @dvirsky , thank you for answer, i found that this commands not described in your docs, but COMMANDS returned it, https://github.com/fastogt/fastonosql/blob/master/src/core/db/redis/db_connection.cpp#L2460 and when add it to array supported commands, i received warnings. You can close this issue thank you.

**Comment by dvirsky** [comment]
There is no way currently to to mark redis commands as "aof only" or hidden, so we chose to simply not document them, rightfully assuming that no one looks that the output of COMMAND :) 

What are you doing with RediSearch in your project? Are you creating a UI for it? Interesting!

**Comment by topilski** [comment]
Hi @dvirsky, yes now i working with redis modules, and with support redissearch commands, displaying and handling it, writing some help description for commands,  that will help users more simply use redissearch module.

![untitled](https://user-images.githubusercontent.com/4686379/32611392-9b33b79a-c576-11e7-87a6-f26adfe9ea87.png)

**Comment by dvirsky** [comment]
Nice! Just a small comment: TYPE_FT_DOC should actually be TYPE_FT_TERM
