### ISSUE TITLE
How to drop or empty an autocomplete dictionary?

### ISSUE THREAD

**Issue by slowernet** [RedisLabsModules/RediSearch#221]
I want to rebuild my autocomplete index - adjust weights and add a payload.

It's not clear to me how I can drop the dictionary or empty it, without a dedicated command or a way to list or iterate over the strings in it. What is the recommended course here?

Thank you for your time.

**Comment by dvirsky** [comment]
`DEL myAutoComplete` :)

**Comment by dvirsky** [comment]
I'm closing this, if you encounter any problems don't hesitate to reopen or open a new issue. It's a good idea to mention this in the docs.

**Comment by slowernet** [comment]
Thanks, worked great. 

Agree, would document, or even extend FT.DROP to work on AC dictionaries 🙂.

**Comment by dvirsky** [comment]
Technically they are unrelated, you can have AC's without text indexes.
They weren't originally meant to be part of the same module, but since AC
is closely related to search, the two were bundled together initially.

**Comment by slowernet** [comment]
I think it's great that they are bundled. I'm happy with the AC => FT flow I have working on my project right now. (Thanks!)

The suggestion to extend FT.DROP was just for interface simplicity/consistency - understood that they are different under the hood.
