### ISSUE TITLE
Please remove test "v0.99.1-test" release

### ISSUE THREAD

**Issue by lamby** [RedisLabsModules/RediSearch#224]
I'm assuming this was some kind of test. However, it breaks @Debian's automatic version detection:

https://qa.debian.org/cgi-bin/watch?pkg=redisearch

("newer package available")

Please remove this tag if it was a genuine test.

**Comment by dvirsky** [comment]
Deleted, sorry. 
It was indeed a test of the CI system.

In the future if I do that, if I keep the test tag lower than the latest version will it be fine?

**Comment by lamby** [comment]
Yep. Try some prefix like "0+snapshot" :)

**Comment by dvirsky** [comment]
Cool. heads up - I'm going to release a new version soon with two critical crash fixes.
