### ISSUE TITLE
Tokenizer doesn't understand Traditional Chinese

### ISSUE THREAD

**Issue by kilianc** [RedisLabsModules/RediSearch#226]
I ran into this problem where I was normalizing Chinese strings both at indexing and search time to traditional Chinese using: https://github.com/Pleasurazy/chinese-conv.

Most of the queries started failing and after some investigation with @dvirsky it appears tokenization only works with simplified Chinese.

Since Traditional/Simplified is a 1:1 map it would be nice if the normalization was part of the tokenizer in the module itself, unless somebody that is a native Chinese speaker has a good reason not to.

🍻

**Comment by dvirsky** [comment]
@mnunberg looks like it's a pretty simple preprocessing, pretty much akin to lowercasing. Let's discuss the best way to add it, I feel a better way to represent the text processing part of the indexer and tokenizer is needed.

**Comment by mnunberg** [comment]
It seems the simplest place for the conversion to take place is in Friso itself, where the UTF-8 sequence is actually decoded.

**Comment by mnunberg** [comment]
@kilianc Can you provide some sample words (and maybe documents) in simplified and traditional Chinese that I can use for testing?

**Comment by dvirsky** [comment]
@mnunberg this SO question includes a couple of complete word examples https://chinese.stackexchange.com/questions/14082/comparison-of-tools-for-converting-traditional-to-simplified-chinese

**Comment by mnunberg** [comment]
@kilianc does this work for you? https://github.com/RedisLabsModules/RediSearch/tree/cn-simptrad

**Comment by mnunberg** [comment]
This should be fixed. Please reopen if this doesn't work.
