### ISSUE TITLE
Incorrect result on using +inf/-inf with text filter on column

### ISSUE THREAD

**Issue by arora-kushal** [RedisLabsModules/RediSearch#228]
The below 2 queries returns the same result. 

```
"FT.SEARCH" "VVV" "@StartDate:[636371424000000000, +inf] @StartDate:[-inf, (636424128000000000]" NOCONTENT
Output: 891
"FT.SEARCH" "VVV" "@StartDate:[636371424000000000, (636424128000000000]" NOCONTENT
Output: 891

```

And, If I apply another numeric filter, they also yield same results:

```
"FT.SEARCH" "VVV" "@IsActive:[1, 1] @StartDate:[636371424000000000, +inf] @StartDate:[-inf, (636424128000000000]" NOCONTENT
Output: 453
"FT.SEARCH" "VVV" "@IsActive:[1, 1] @StartDate:[636371424000000000, (636424128000000000]" NOCONTENT
Output: 453

```

However, If I apply text filter with them, below 2 queries gives different results

```
"FT.SEARCH" "VVV" "@Name:(\"Other\") @StartDate:[636371424000000000, +inf] @StartDate:[-inf, (636424128000000000]" NOCONTENT
Output: 209
"FT.SEARCH" "VVV" "@Name:(\"Other\") @StartDate:[636371424000000000, (636424128000000000]" NOCONTENT
Output: 177
```

Please suggest.

**Comment by arora-kushal** [comment]
Another example:

We are getting different results for these 2 queries:

```
"FT.SEARCH" "VVV" "@Seq_l:[6349, +inf] @Name:(\"Other\") @IsActive:[1, 1]" NOCONTENT SORTBY Seq_l LIMIT 0 1300
Output: 9
"FT.SEARCH" "VVV" "@Name:(\"Other\") @IsActive:[1, 1] @Seq_l:[6349, +inf]" NOCONTENT SORTBY Seq_l LIMIT 0 1300
Output: 10
```

**Comment by dvirsky** [comment]
Can you provide an isolated example I can run including the data?

**Comment by dvirsky** [comment]
I'm afraid I cannot recreate it. Also, I strongly recommend that you don't use numeric fields for things like IsActive. Use a tag field instead.

**Comment by arora-kushal** [comment]
@dvirsky Please find attached file for reproducing the issue.

Definitely, we would incorporate tag field change in our code.

[inf_bug_1.txt](https://github.com/RedisLabsModules/RediSearch/files/1517698/inf_bug_1.txt)

**Comment by salt4pommes** [comment]
I can confirm that I get the same results using the inf_bug_1.txt with given queries.

Redis: 4.0.3
Redisearch: 1.0.0

**Comment by dvirsky** [comment]
Thanks for the info. I'll investigate.

**Comment by dvirsky** [comment]
Ok, problem found. It was unrelated to INF but it was important nonetheless. results after the fix: 

```
127.0.0.1:6379> "FT.SEARCH" "VVV" "(@Name:Other) @StartDate:[636371424000000000, +inf] @StartDate:[-inf, (636424128000000000]" NOCONTENT
 1) (integer) 110
 2) "6386"
 3) "6384"
 4) "6382"
 5) "6326"
 6) "6325"
 7) "6321"
 8) "6318"
 9) "6316"
10) "6314"
11) "6312"
127.0.0.1:6379> "FT.SEARCH" "VVV" "(@Name:Other) @StartDate:[636371424000000000, (636424128000000000]" nocontent
 1) (integer) 110
 2) "6386"
 3) "6384"
 4) "6382"
 5) "6326"
 6) "6325"
 7) "6321"
 8) "6318"
 9) "6316"
10) "6314"
11) "6312"
```

**Comment by arora-kushal** [comment]
@dvirsky - Just out of curiosity, would there be any major performance issue if I write queries like

`"FT.SEARCH" "VVV" "@StartDate:[636371424000000000, +inf] @StartDate:[-inf, (636424128000000000]"`

instead of this

`"FT.SEARCH" "VVV" "@StartDate:[636371424000000000, (636424128000000000]"`

**Comment by dvirsky** [comment]
Yes, of course. We don't optimize the query and find the intersection of
the two yet, so you would be executing two very expensive filters and
intersecting their result.
