### ISSUE TITLE
FT.GET query error, server disconnection

### ISSUE THREAD

**Issue by 1051063313** [RedisLabsModules/RediSearch#229]
When I use the client to send FT.GET spu 784017 request to redis,  if the index associated ID does not exist, why does server redis automatically disconnect?
For example, I sent it
FT.GET spu 784017
At this point, there is no 784017 ID. The server will report the wrong Connection error:Execution timeout and then disconnect

**Comment by dvirsky** [comment]
This has already been fixed in 63f0ada, you are probably using an older version. make sure you are running 1.0 or master and if the problem persists please reopen the issue.

**Comment by 1051063313** [comment]
Thank you very much for your answer. If I used the redis version of 2.8.19, which version would be appropriate for me?

**Comment by dvirsky** [comment]
You can't use redisearch with redis versions lower than 4.0

**Comment by 1051063313** [comment]
OK, thank you very much! Because our project is used in less than 4 versions. So we try to see if we can use a less than 4 version.
