### ISSUE TITLE
I use the Redis version is 2.8.19, how do I choose the redisearch version?

### ISSUE THREAD

**Issue by 1051063313** [RedisLabsModules/RediSearch#230]
I use the Redis version is 2.8.19, how do I choose the redisearch version? Does redisearch only support the version of Redis 4+?
I use Linux version is Red Hat 4.8.2-16, but when I compile redisearch 0.8, 0.7, 0.6, 0.5, I will report the following error. What's the reason?

[root@localhost src]# make all
Make -C util
Make[1]: Entering directory `/opt/rs/0.7/RediSearch/src/util'
Make[1]: Nothing to be done for `all'.
Make[1]: Leaving directory `/opt/rs/0.7/RediSearch/src/util'
Make -C rmutil
Make[1]: Entering directory `/opt/rs/0.7/RediSearch/src/rmutil'
Make[1]: Nothing to be done for `all'.
Make[1]: Leaving directory `/opt/rs/0.7/RediSearch/src/rmutil'
Make -C dep/snowball libstemmer.o
Make[1]: Entering directory `/opt/rs/0.7/RediSearch/src/dep/snowball'
Libstemmer/mkmodules.pl libstemmer/modules.h src_c libstemmer/modules.txt libstemmer/mkinc.mak
Make[1]: execvp: libstemmer/mkmodules.pl: Permission denied
Make[1]: * * * * [libstemmer/modules.h] Error 127
Make[1]: Leaving directory `/opt/rs/0.7/RediSearch/src/dep/snowball'
Make: * * * * [snowball] Error 2

**Comment by dvirsky** [comment]
We don't support something as old as RHEL 4.8, I'd switch to 6 for this. Best way to do it is run docker or compile the [latest stable release (1.0)](https://github.com/RedisLabsModules/RediSearch/releases/tag/v1.0.0)
