### ISSUE TITLE
When I use FT.SEARCH, I need to query the condition. How should I query if I do not need to query the conditions?

### ISSUE THREAD

**Issue by 1051063313** [RedisLabsModules/RediSearch#231]
For our project requirements, I want to use FT.SEARC to get the number of all the indexes and the pagination to get the index list. This query is completely free of query conditions. How can I inquire about it.

**Comment by dvirsky** [comment]
If the query has no conditions, what documents would you like to retrieve?
Also, the right place to have this discussion is the mailing list: groups.google.com/forum/#!forum/redisearch

I'm closing this issue, feel free to continue the discussion there.
