### ISSUE TITLE
High memory usage when REPLACE is used

### ISSUE THREAD

**Issue by mnunberg** [RedisLabsModules/RediSearch#236]
`REPLACE` (in `FT.ADD`) doesn't really recover a whole lot of the old document's memory. This needs furhter investigation. It is *not* a leak, though.

**Comment by dvirsky** [comment]
The reason is that we do not delete the old document metadata from the document table when a document is assigned a new id. 
however just deleting it is not good - the dmd object can be held by a running query. it needs a refcount for proper deletion.

**Comment by dvirsky** [comment]
one option to solve this would be to make the doc table an array of pointers and not of structs, and then you can simply re-use the same pointer on the new document instance. It will increase memory consumption and probably hurt performance a bit, but it's certainly worth considering.

**Comment by mnunberg** [comment]
Will be fixed with compaction :)
