### ISSUE TITLE
FT.TAGVALS not working on fields having single character as value 

### ISSUE THREAD

**Issue by rajeshsubhankar** [RedisLabsModules/RediSearch#239]
**How to reproduce:**
ft.create TagTest schema cities TAG
ft.add TagTest user1 1.0 fields cities A
ft.add TagTest user2 1.0 fields cities B
ft.tagvals TagTest cities
**Response:** empty list

ft.add TagTest user3 1.0 fields cities AB
ft.tagvals TagTest cities
**Response:** ["ab"]

**Comment by dvirsky** [comment]
Fixed in master, thanks!
