### ISSUE TITLE
Intersection or union multiple numeric filters for the same field not working

### ISSUE THREAD

**Issue by tw-bert** [RedisLabsModules/RediSearch#250]
The [documentation](http://redisearch.io/Query_Syntax/) states (including typo btw):
> It is possible to interesect or union multiple numeric filters in the same query, be it for the same field or different ones.

If a numeric field `i` has documents for 13,16,22 , an incorrect number of results is returned

  - FT.SEARCH 'idxFoo' '@i:[13 22]'
    * Returns 3 rows, correct
  - FT.SEARCH 'idxFoo' '@i:[13 13]' '@i:[22 22]'
    * Returns 1 row, incorrect
  - FT.SEARCH 'idxFoo' '@i:[13 13]' OR '@i:[22 22]'
    * Returns 1 row, incorrect
  - FT.SEARCH 'idxFoo' '@i:[13 13]' | '@i:[22 22]'
    * Returns 1 row, incorrect
  - FT.SEARCH 'idxFoo' '@i:[13 13]|[22 22]'
    * Syntax error

**Comment by dvirsky** [comment]
neither is correct syntax.

`(@i:[13 14])|(@i:[15 16])`
