### ISSUE TITLE
Implementing groupby reducers

### ISSUE THREAD

**Issue by dvirsky** [RedisLabsModules/RediSearch#255]
Right now we have only COUNT, SUM and TOLIST (which is something like group_concat)

Here are some more reducers that the aggregation engine needs:

* Median (on numeric fields only)
* MAX (numeric only)
* MIN (numeric only)
* Count_distinct (when counting not the grouped property) - lower priority
* STDDEV

**Comment by slavaGanzin** [comment]
@dvirsky May I suggest to add Mode and Quantile functions?

**Comment by dvirsky** [comment]
@slavaGanzin good ideas, quantiles are a good call definitely.

**Comment by mnunberg** [comment]
aggregators have been implemented; now we need a data set and tests to see if they actually work as intended.
