### ISSUE TITLE
Is score index implemented?

### ISSUE THREAD

**Issue by junhe** [RedisLabsModules/RediSearch#262]
Hi,

According to an (old) document (https://github.com/RedisLabsModules/RediSearch/blob/master/docs/DESIGN.md), RediSearch seems to have score index. But from what I see, it is not implemented in the master. One evidence is that IndexStats.scoreIndexesSize is never updated. Can anyone confirm this?

Thanks,
Jun

**Comment by dvirsky** [comment]
It's been removed.
