### ISSUE TITLE
Detect Lua and MULTI clients implicitly and do not try to block them.

### ISSUE THREAD

**Issue by dvirsky** [RedisLabsModules/RediSearch#263]
Redis 4.0.6 contains my patch to detect clients running from Lua or MULTI using GetCtxFlags. In all blocking requests we should detect clients that cannot be blocked and treat their requests as synchronous, regardless of whether SAFEMODE is enabled or not.

**Comment by mnunberg** [comment]
I believe we can close this; fixed by https://github.com/RedisLabsModules/RediSearch/commit/b4e02c36f535ddf3c2ca3242a2a58b60ef734918 and https://github.com/RedisLabsModules/RediSearch/commit/db6c75a76d88e78f31a985b641596179b56ceda7#diff-a31e41a9e523fbbf9e60ba9a31f38efe

**Comment by tw-bert** [comment]
@dvirsky The fixes work good. One remark though: In my AOF file, `FT.SAFEADD` is still there. It is preferable to make that `FT.ADD` as well if possible (reason: manual scans or custom parsing of the AOF). Not if it requires a big effort of course.

**Comment by dvirsky** [comment]
It's not possible since the PR to redis to detect AOF loading is not merged
yet...

**Comment by tw-bert** [comment]
All clear
