### ISSUE TITLE
Embedded Geo Search Syntax Question

### ISSUE THREAD

**Issue by ethanhann** [RedisLabsModules/RediSearch#268]
I'm looking into adding support for the embedded geo and numeric search syntax in my PHP client. I don't see an example in the docs. What am I doing wrong here with my search query?

```
127.0.0.1:6379[15]> FT.CREATE QueryBuilderTest SCHEMA title TEXT WEIGHT 1 author TEXT WEIGHT 1 price NUMERIC stock NUMERIC location GEO
OK
127.0.0.1:6379[15]> FT.ADD QueryBuilderTest 15a64009441159 1 FIELDS title How to be awesome. author Jack price 9.99 stock 231 location 10.91905 52.05041
OK
127.0.0.1:6379[15]> FT.SEARCH QueryBuilderTest @location:[10.91905 52.05041 100 km]
(error) Syntax error at offset 11 near '10.91905'
```

P.S. I pulled the latest docker image so I believe I am using the latest version of the module. I don't know how to verify that I am running the latest version. Is there a command to do that - that lists loaded modules or something?

**Comment by dvirsky** [comment]
Hi Ethan.

First of all:

```
127.0.0.1:6379> module list
1) 1) "name"
   2) "ft"
   3) "ver"
   4) (integer) 10004
```

The convention is (major * 10000) + (minor * 100) + patch

Second the problem is that you're not quoting the query, causing redis to parse it as multiple arguments.

**Comment by ethanhann** [comment]
I knew I was just doing something dumb. Thanks.
