### ISSUE TITLE
Add document payload to FT.GET result

### ISSUE THREAD

**Issue by akir94** [RedisLabsModules/RediSearch#269]
Would it be possible to get the document's payload when using FT.GET? For example, by adding a WITHPAYLOADS parameter?
I managed to achieve the same effect by using FT.SEARCH with INKEYS and WITHPAYLOADS, but it doesn't feel right.

**Comment by dvirsky** [comment]
Let me think about it. I general, payloads are not meant to be retrieved unless for special purposes. they are there to be exposed to ranking functions. If you're doing anything else with them it's kind of an abuse :) IIRC the reason they are returned is that they can be evaluated in a distributed setup where we need to compare them during map/reduce flows.

**Comment by akir94** [comment]
In my case, I store entities with their geographic location, and the rest of their data is stored as payload. I have two services, one retrieves entities using a geographic query and another that retrieves entities by their id. Both of them need the payload.
I'd like to have both of them to use the same index. For the first service, I'm good because FT.SEARCH also gives me the payloads, and for the second service I want a way to get an entity's payload by its id.

**Comment by dvirsky** [comment]
Why not just save the metadata as a non indexed text key? You don't even need to declare it in the schema, just send it over and it will get saved and retrieved in both cases.

**Comment by dvirsky** [comment]
basically:

```
127.0.0.1:6379> FT.CREATE idx SCHEMA location GEO
OK
127.0.0.1:6379> FT.ADD idx doc1 1 FIELDS location "30 30" metadata "whatever"
OK

127.0.0.1:6379> FT.SEARCH idx "@location:[30 30 1 km]"
1) (integer) 1
2) "doc1"
3) 1) "location"
   2) "30 30"
   3) "metadata"
   4) "whatever"

127.0.0.1:6379> FT.GET idx doc1
1) "location"
2) "30 30"
3) "metadata"
4) "whatever"
```

**Comment by akir94** [comment]
I didn't think of that. Thank you very much, I'll try that.

**Comment by dvirsky** [comment]
I'm closing this. I don't think there's a reason to add it ATM.
