### ISSUE TITLE
Wildcard Search

### ISSUE THREAD

**Issue by RupertAvery** [RedisLabsModules/RediSearch#27]
Is it possible to query partial words with a wildcard query, such as "he*" for "hello"?

**Comment by dvirsky** [comment]
Currently - not directly, although it might change soon.

But you can do it in conjunction with the auto-suggestion API. What you can do is build a dictionary with `FT.SUGADD`, and get prefix suggestions with `FT.SUGGET`, and pass those to the search as an OR query. i.e.:

```
> FT.SUGADD terms hello 1.0
> FT.SUGADD terms help 1.0
...
```

and in your code (writing python/pseudo code here):

```py

terms = client.get_suggestions('terms', 'he')
result = client.search("|".join(terms))

```

But I intend to change the main index dictionary into a prefix tree, which will allow doing this automatically as you describe. 

Will the above method do for now? You can of course implement it in Lua to make things atomic.

**Comment by RupertAvery** [comment]
Unfortunately, no. I have a set of denormalized data I would like to cache in redis and I would really like to be able to query it directly without having to set it up myself, as that kind of defeats the purpose of putting it there.

**Comment by dvirsky** [comment]
Can you explain further?

**Comment by RupertAvery** [comment]
Well a full-text search is probably not the best way to achieve this, but suppose i have a list of names, and I want to do a query on a name that starts with or contains "Foo", without having to add "Foobar", "Foobaz", and "Foogle" to the suggestions for Foo, because I could search for "Foob" or "Foog" as well and I'd have to add those names as suggestions for Foob and Foot.

**Comment by dvirsky** [comment]
@RupertAvery Oh, in that case I might be able to help you after all! :)

I've also written a module called `Secondary` that allows you to do just that, with an SQL like syntax. You can use it on HASH keys or directly as a data type. Basically you can do:

```
IDX.FROM users_name WHERE "name LIKE 'foo%'" HGETALL $
```

And you can create indexes on multiple fields, etc. 

Have a look: https://github.com/RedisLabsModules/secondary

**Comment by RupertAvery** [comment]
I'll take a look at it, thanks!

**Comment by dvirsky** [comment]
@RupertAvery did you look at the other module? have you tried it?

**Comment by runningmaster** [comment]
@dvirsky, do you have a plan to add in `RediSearch` something like that:

```SQL
SELECT * FROM table WHERE Column LIKE '%foo%';
SELECT * FROM table WHERE Contains(Column, "foo");
SELECT * FROM table WHERE Column CONTAINING "foo";
... etc.
```
For example, I need to find all words containing `foo`:
```
foo
foobar
barfoo
bazfoobar
```

**Comment by runningmaster** [comment]
To be more precise, I need something similar `Simple phrase query - hello AND world`
```
hello world
```
but with "containing" feature
```
*hello* *world*
```
```
hello world
world hello
foo hello bar world
foohello barworld
hellofoo worldbar
foobarhelloworld
fooworldbarhello
...etc.
```

**Comment by dvirsky** [comment]
hi. at the moment we only support prefix queries. you can pre-split your terms if you want any suffix. indexing all suffixes of any term with the current data structure would be very costly.
