### ISSUE TITLE
Prevent creation of indexes on db num != 0

### ISSUE THREAD

**Issue by dvirsky** [RedisLabsModules/RediSearch#271]
Until we have an alternative to DUMP/RESTORE for term keys in AOF rewrite callbacks, we can't serialize them on dbs other than 0 because we don't know and can't know the db number from the io context. So until we fix that or redis removes this limitation, let's block creation of indexes when db!=0. This will prevent bugs like #267

**Comment by mnunberg** [comment]
275a4a36e79ecfab5e9430a46dce4bbab898da0a
