### ISSUE TITLE
Wrong result in AND query

### ISSUE THREAD

**Issue by amallia** [RedisLabsModules/RediSearch#28]
I created an index with a single document: `FT.ADD myIdx doc1 1.0 FIELDS title "hello world" body "lorem ipsum" url "http://redis.io"`.
From my understanding of [query syntax documentation](https://github.com/RedisLabsModules/RediSearch/blob/master/docs/Query_Syntax.md#a-few-examples) the following queries should have the same meaning:
- `FT.SEARCH myIdx test ipsum LIMIT 0 1`
- `FT.SEARCH myIdx ipsum test LIMIT 0 1`
They both should return the intersection of `test AND ipsum`.

Apparently the result set is empty for the first query (correct), while doc1 is returned for the second query (wrong).

Is this an expected behaviour?

**Comment by dvirsky** [comment]
Hey @amallia! you need to put the terms in quotes, otherwise the redis protocol interprets them as two different arguments. Basically you performed two single term queries. You should do:

```
FT.SEARCH myIdx "test ipsum" LIMIT 0 1
FT.SEARCH myIdx "ipsum test" LIMIT 0 1
```

I recommend using the Python or Java libraries for abstraction. 
https://github.com/RedisLabs/redisearch-py
https://github.com/RedisLabs/JRediSearch

**Comment by dvirsky** [comment]
PS you can see many examples in https://github.com/RedisLabsModules/RediSearch/blob/master/src/pytest/test.py

**Comment by dvirsky** [comment]
(once you've verified this is indeed not a bug, please close this issue. thanks!)

**Comment by amallia** [comment]
Yes, you are right. I thought double quotes was for exact search, but in that case I need to quote twice like `FT.SEARCH myIdx '"ipsum lorem"' LIMIT 0 1`

**Comment by dvirsky** [comment]
yes, you can also do `FT.SEARCH myIdx "\"ipsum lorem\"" LIMIT 0 1`. Of course in client libraries all this is abstracted away, and it only applies to redis-cli.
