### ISSUE TITLE
Docs not indexing in sync.

### ISSUE THREAD

**Issue by thehector** [RedisLabsModules/RediSearch#280]
I have a cron job running every 10 seconds which fetches incremental data from MySql and indexes them to RedisSearch. Sometimes(like once every 2-3 days) odd records show up in Mysql to Redis Logs, but don't get indexed immediately. The offset key used for redis incremental update from mysql is correctly updated in redis. The missing doc in RedisSearch Index appears after few hours. 
Is this a bug?

**Comment by dvirsky** [comment]
I'm not sure I understand the situation you're describing, could you demonstrate it more specifically? 

In general, in redisearch, once you get the OK after an indexing of a document, it's in the index, period. If you've encountered a situation where this is not the case, it's either a bug in your update logic or a bug in redisearch. Let's try to get to the bottom of it!

**Comment by thehector** [comment]
`def mysql_data_to_redis(self):
        # main method
        patient_off = 'mysql_patient_date_offset'
        patientclinic_off = 'mysql_patient_clinic_date_offset'

        # if offset doesn't exist then create
        self.check_offset_redis(patient_off)
        self.check_offset_redis(patientclinic_off)
        p_off = self.redis_conn.get_val(patient_off)
        pc_off = self.redis_conn.get_val(patientclinic_off)

        p_max_id, pc_max_id = self.get_mysql_max_id()
        records = self.get_records_mysql(p_off, pc_off, pc_max_id, p_max_id)

        self.create_index_in_redis()
        for row in records:
            log.debug("row in records while transfering mysql_data_to_redis : {0}".format(row))
            print row
            self.send_record_to_redis(row)

        if p_max_id is not None:
            self.redis_conn.set_val(patient_off, p_max_id)
        if pc_max_id is not None:
self.redis_conn.set_val(patientclinic_off, pc_max_id)`

**Comment by thehector** [comment]
`    def mysql_data_to_redis(self):

        # main method
        patient_off = 'mysql_patient_date_offset'
        patientclinic_off = 'mysql_patient_clinic_date_offset'

        # if offset doesn't exist then create
        self.check_offset_redis(patient_off)
        self.check_offset_redis(patientclinic_off)
        p_off = self.redis_conn.get_val(patient_off)
        pc_off = self.redis_conn.get_val(patientclinic_off)

        p_max_id, pc_max_id = self.get_mysql_max_id()
        records = self.get_records_mysql(p_off, pc_off, pc_max_id, p_max_id)

        self.create_index_in_redis()
        for row in records:
            log.debug("row in records while transfering mysql_data_to_redis : {0}".format(row))
            print row
            self.send_record_to_redis(row)

        if p_max_id is not None:
            self.redis_conn.set_val(patient_off, p_max_id)
        if pc_max_id is not None:
self.redis_conn.set_val(patientclinic_off, pc_max_id)
`
This is the main method running as cron job, this fetches incremental updates from Mysql and indexes them in redis. It then updates the date time offset keys in redis. The following method indexes records in redis

`def send_record_to_redis(self, row):

        patient_id = int(row[0])
        first_name = self.remove_special_characters(row[1])
        last_name = self.remove_special_characters(row[2])
        clinic_id = row[3]
        doctor_id = row[4]
        mrid = row[5]
        nric = self.remove_special_characters(row[6])
        phone_number = row[7]
        phone_country_code = row[8]
        email = self.remove_special_characters(row[9])
        remember_token = row[10]
        device = row[11]
        BSL_2HPP = -1 if row[12] in ('None', None) else int(float(row[12]))
        bpDiastolic = -1 if row[13] in ('None', None) else int(float(row[13]))
        chronicDiagnosis = row[14]
        user_id = row[15]

        ind = str(clinic_id) + ':' + str(patient_id) + ':' + str(doctor_id)
        self.client.add_document(ind, replace=True, patient_id=patient_id, first_name=first_name, last_name=last_name,
                                 clinic_id=clinic_id, doctor_id=doctor_id, mrid=mrid, nric=nric,
                                 phone_number=phone_number, phone_country_code=phone_country_code, email=email,
                                 remember_token=remember_token, device=device, BSL_2HPP=BSL_2HPP,
                                 bpDiastolic=bpDiastolic, chronicDiagnosis=chronicDiagnosis,
                                 user_id=user_id)
`

**Comment by dvirsky** [comment]
You wrote a couple of comments and then deleted them. Why?

**Comment by thehector** [comment]
```
def mysql_data_to_redis(self):
        # main method
        patient_off = 'mysql_patient_date_offset'
        patientclinic_off = 'mysql_patient_clinic_date_offset'

        # if offset doesn't exist then create
        self.check_offset_redis(patient_off)
        self.check_offset_redis(patientclinic_off)

        p_off = self.redis_conn.get_val(patient_off)
        pc_off = self.redis_conn.get_val(patientclinic_off)
        p_max_id, pc_max_id = self.get_mysql_max_id()

        records = self.get_records_mysql(p_off, pc_off, pc_max_id, p_max_id)
        self.create_index_in_redis()

        for row in records:
            log.debug("row in records while transfering mysql_data_to_redis : {0}".format(row))
            self.send_record_to_redis(row)

        if p_max_id is not None:
            self.redis_conn.set_val(patient_off, p_max_id)
        if pc_max_id is not None:
            self.redis_conn.set_val(patientclinic_off, pc_max_id)
```
 

 This is the main method running as cron job, this fetches incremental updates from Mysql and indexes them in redis. It then also updates the date **time** offset keys in redis. The following method indexes records in redis

```
def send_record_to_redis(self, row):
        patient_id = int(row[0])
        first_name = self.remove_special_characters(row[1])
        last_name = self.remove_special_characters(row[2])
        clinic_id = row[3]
        doctor_id = row[4]
        mrid = row[5]
        nric = self.remove_special_characters(row[6])
        phone_number = row[7]
        phone_country_code = row[8]
        email = self.remove_special_characters(row[9])
        remember_token = row[10]
        device = row[11]
        BSL_2HPP = -1 if row[12] in ('None', None) else int(float(row[12]))
        bpDiastolic = -1 if row[13] in ('None', None) else int(float(row[13]))
        chronicDiagnosis = row[14]
        user_id = row[15]

        ind = str(clinic_id) + ':' + str(patient_id) + ':' + str(doctor_id)

        self.client.add_document(ind, replace=True, patient_id=patient_id, first_name=first_name, last_name=last_name,
                                 clinic_id=clinic_id, doctor_id=doctor_id, mrid=mrid, nric=nric,
                                 phone_number=phone_number, phone_country_code=phone_country_code, email=email,
                                 remember_token=remember_token, device=device, BSL_2HPP=BSL_2HPP,
                                 bpDiastolic=bpDiastolic, chronicDiagnosis=chronicDiagnosis,
                                 user_id=user_id)
```

I also have a separate cron which updates the same records on the same index with additional fields that comes from data warehouse every hour. Attaching this below. 

```
    def dwh_data_to_redis(self):
        patient_off = 'patient_date_offset'
        patientclinic_off = 'patient_clinic_date_offset'

        # if offset doesn't exist then create
        self.check_offset_redis(patient_off)
        self.check_offset_redis(patientclinic_off)
        p_off = self.redis_conn.get_val(patient_off)
        pc_off = self.redis_conn.get_val(patientclinic_off)

        p_max_id, pc_max_id = self.get_max_id()
        records = self.get_records(p_off, pc_off, pc_max_id, p_max_id)

        self.create_index_in_redis()
        for row in records:
            self.send_record_to_redis(row)

        if p_max_id is not None:
            self.redis_conn.set_val(patient_off, p_max_id)
        if pc_max_id is not None:
            self.redis_conn.set_val(patientclinic_off, pc_max_id)
```

The issue is some odd records donot show in redissearch for about an hour or two after it appears in mysql_to_redis logs.

**Comment by thehector** [comment]
sorry about deleted comments..

**Comment by dvirsky** [comment]
Well, it seems fine. So what you're saying is that only the hourly cron eventually causes the documents to be there?

Anyway, a couple of suggestions:

1. When you have such a situation, and you run FT.GET {index} {id} on redis, do you see these documents at all? 

2. I see that you're not handling exceptions at all in this code (assuming it's production code). Any error  in the following loop will cause all the rest of the records to get lost:

```py
 for row in records:
            log.debug("row in records while transfering mysql_data_to_redis : {0}".format(row))
            self.send_record_to_redis(row)
```

Are you at least logging exceptions somehow? If your process silently swallows exceptions, any timeout or encoding glitch or whatever will cause the rest of the records in the same batch to be silently dropped. Why not do:

```py
 for row in records:
            log.debug("row in records while transfering mysql_data_to_redis : {0}".format(row))
            try:
                self.send_record_to_redis(row)
            except RedisError as e:
                log.error("Exception while updating {}: {}".format(row, e)
```

**Comment by dvirsky** [comment]
Also, you can log everything that gets into redis with MONITOR to see if these records actually get inserted into redis.

**Comment by thehector** [comment]
Thanks I will implement the changes you mentioned.. Will update you about the situation..

**Comment by dvirsky** [comment]
@thehector any news? Can we close this?

**Comment by thehector** [comment]
Donot Close it as of now.. Still monitoring the logs continuouly... will need to monitor for atleast a week or two and check if it reoccurs...

**Comment by dvirsky** [comment]
Please re-open if there's still a problem. Thanks!
