### ISSUE TITLE
Geo query returns invalid/inconsistent results depending on position in query

### ISSUE THREAD

**Issue by ojji** [RedisLabsModules/RediSearch#281]
I have a database where I'm indexing a text field and a geo position, when my query matches multiple documents in the geo range and the geo term is after the other fields term in the query, I get 0 results.

 ### My sample db:
`"FT.CREATE" "geo-bug-repro" "SCHEMA" "body" "TEXT" "NOSTEM" "location" "GEO"`
`"FT.ADD" "geo-bug-repro" "doc1" "1" "LANGUAGE" "english" "FIELDS" "body" "document1 body" "location" "19.35515,47.59657"`
`"FT.ADD" "geo-bug-repro" "doc2" "1" "LANGUAGE" "english" "FIELDS" "body" "document2 with different text" "location" "19.03991,47.49801"`

### Queries where the georadius matches only one document, this looks fine
`"FT.SEARCH" "geo-bug-repro" "(@body:\"document2\") (@location:[19.03 47.49 10 km])" "LANGUAGE" "english"`

 1.  "1"
 2.  "doc2"
 3. 1.   "body"
     2.   "document2 with different text"
     3.   "location"
     4.   "19.03991,47.49801"

`"FT.SEARCH" "geo-bug-repro" "(@location:[19.03 47.49 10 km]) (@body:\"document2\")" "LANGUAGE" "english"`

 1.  "1"
 2.  "doc2"
 3. 1.   "body"
     2.   "document2 with different text"
     3.   "location"
     4.   "19.03991,47.49801"

### Queries where georadius matches both documents, now the results are inconsistent
`"FT.SEARCH" "geo-bug-repro" "(@body:\"document2\") (@location:[19.03 47.49 30 km])" "LANGUAGE" "english"`

 1.  "0"

`"FT.SEARCH" "geo-bug-repro" "(@location:[19.03 47.49 30 km]) (@body:\"document2\")" "LANGUAGE" "english"`

 1.  "1"
 2.  "doc2"
 3. 1.   "body"
     2.   "document2 with different text"
     3.   "location"
     4.   "19.03991,47.49801"

Feel free to lecture me if the query or the document creation syntax is bad, I'm actually starting to lose my sanity over this 😃

**Comment by dvirsky** [comment]
The query looks okay, looks like a bug. Although they usually manifest only in very small data sets of 1-2 documents. I'll have a look.

**Comment by dvirsky** [comment]
Fixed in master. Please pull and verify, I'll release it with the next version.

**Comment by ojji** [comment]
This bug looks smashed, all the documents are retrieved from the real database.
Amazing reaction time too, thank you for the quick fix! 👍

**Comment by dvirsky** [comment]
@ojji thanks, and thanks for reporting, great find.
