### ISSUE TITLE
Sortkeys are lost (and ft.drop misbehaves on tags) after restore from AOF

### ISSUE THREAD

**Issue by tw-bert** [RedisLabsModules/RediSearch#282]
Redis `4.0.7`, RediSearch `1.0.6`

This issue is a follow-up on [RediSearch crash with BGSAVE #277](https://github.com/RedisLabsModules/RediSearch/issues/277 )

1. After restore from AOF, sorting does not work anymore, as the sortkeys are not restored.
2. Also (somehow related we assume, so no separate issue submitted), after restore from AOF, tag hashes are not dropped anymore after a `FT.DROP`.
    - This had us stunned. Before we knew what was going on, we dropped and repopulated the index, but the results were all wrong because of the existing tag hashes. Hence -> 
3. Please raise an exception at `FT.CREATE` if a tag hash exists that will cause mayhem with the index.

Simple to reproduce:

```lisp
ft.create idx schema foo text sortable bar tag
ft.add idx 1 1 fields foo A bar 1
ft.add idx 2 1 fields foo B bar 1
bgrewriteaof
debug loadaof
ft.search idx '@bar:{1}' sortby foo asc return 1 foo withsortkeys
--> Results below are in the wrong order [reason: the sortkeys should not be (nil)]
1) (integer) 2
2) "2"
3) (nil)
4) 1) "foo"
   2) "B"
5) "1"
6) (nil)
7) 1) "foo"
   2) "A"
ft.drop idx
keys *
--> Result below shows leftover junk, which will cause mayhem after a following ft.create!
1) "tag:idx/bar"
```

We can work around this issue by:
1. drop all our FT indexes
2. delete offending left over tag hashes
3. recreate the FT indexes
4. repopulate the indexes (our custom scripts)

**Comment by tw-bert** [comment]
Not sure if this is related (could be because of `debug` command), log shows:

```haskell
9738:M 05 Feb 08:27:19.797 * Background AOF rewrite finished successfully
9738:M 05 Feb 08:27:32.673 # Unable to obtain the AOF file length. stat: Bad file descriptor
9738:M 05 Feb 08:27:32.673 # Append Only File loaded by DEBUG LOADAOF
```

**Comment by mnunberg** [comment]
@tw-bert have you tried using this from master? In any event, I'll try to reproduce this locally.

**Comment by tw-bert** [comment]
@mnunberg I'm not clear on what you're asking. FT works fine on live, and live master has not recently been restored from AOF. We did not use any replication on the restored copy. This issue is not master/slave related, but AOF rewrite+restore related.

**Comment by tw-bert** [comment]
@mnunberg Ahh scratch that comment. Master branch of course ;) No, did not test this on master yet.

**Comment by mnunberg** [comment]
😁

**Comment by mnunberg** [comment]
no need to try with master though, I've just reproduced it.

**Comment by mnunberg** [comment]
@tw-bert I've just pushed a fix to master. Apparently my previous fixed made it so it wouldn't crash, but just barely - as it was still broken and I had to use a machete to dig myself out of the bugs!

**Comment by tw-bert** [comment]
@mnunberg Great, I'll test. Did you address only 1, or 1,2,3 (top comment)?

**Comment by mnunberg** [comment]
I didn't address the DROP issue - it would seem to be unrelated here. Let me check once again though, to be sure

**Comment by mnunberg** [comment]
hrm, indeed the tag field still exists. I think this might just be an oversight. I can handle this one as well.

**Comment by mnunberg** [comment]
Ok, I have a fix for this as well, but please file a new bug for this? :)

**Comment by tw-bert** [comment]
Ah.... If I read your words correctly, you just fixed "tag fields do not work over aof" already? Or only the drop part?
I'll open a new issue.

**Comment by mnunberg** [comment]
The drop and the tag fields not working over aof are related to each other. The issue I fixed here with sortables and aof is not related. You'll have a fix for that within a few minutes though :)

**Comment by tw-bert** [comment]
You guys are awesome, thx

**Comment by tw-bert** [comment]
@mnunberg : Fix confirmed
