### ISSUE TITLE
Strange behaviour when searching multiple words

### ISSUE THREAD

**Issue by prog13** [RedisLabsModules/RediSearch#284]
Hi there!
Say I have a couple of docs in my idx with the following "value" fields:

- hello fellow kids
- hello kitty
- hello kitty toys

If I run the search
`FT.SEARCH idx "@value:hello @value:ki*"`
or
`FT.SEARCH idx @value:(hello ki*)`

I'll get the following result
- hello fellow kids

instead of expected
- hello fellow kids
- hello kitty
- hello kitty toys

If I run the following search
`FT.SEARCH idx "@value:hello @value:kit*"`
I'll get the result of
- hello kitty
- hello kitty toys
which is correct.

`SLOP` parameter seem to have no result on these searches. What am I missing here? Thanks for advice.

**Comment by dvirsky** [comment]
Looks like a bug, I'll investigate. tip: in such cases use FT.EXPLAIN to see what's going on.

**Comment by dvirsky** [comment]
Umm, I can't actually recreate it. Can you post the exact redis-cli commands you're running to get to this state? Here's what I'm doing:

```
127.0.0.1:6379> ft.create idx schema foo text
OK
127.0.0.1:6379> ft.add idx 1 1 fields foo "hello fellow kids"
OK
127.0.0.1:6379> ft.add idx 2 1 fields foo "hello kitty"
OK
127.0.0.1:6379> ft.add idx 3 1 fields foo "hello kitty toys"
OK
127.0.0.1:6379> ft.search idx "@foo:hello @foo:ki*"
1) (integer) 3
2) "3"
3) 1) "foo"
   2) "hello kitty toys"
4) "2"
5) 1) "foo"
   2) "hello kitty"
6) "1"
7) 1) "foo"
   2) "hello fellow kids"
127.0.0.1:6379> ft.search idx "@foo:(hello ki*)"
1) (integer) 3
2) "3"
3) 1) "foo"
   2) "hello kitty toys"
4) "2"
5) 1) "foo"
   2) "hello kitty"
6) "1"
7) 1) "foo"
   2) "hello fellow kids"
127.0.0.1:6379> ft.search idx "@foo:(hello kit*)"
1) (integer) 2
2) "3"
3) 1) "foo"
   2) "hello kitty toys"
4) "2"
5) 1) "foo"
   2) "hello kitty"
```

**Comment by prog13** [comment]
I tried to reproduce the issue on the same test database as yours and failed as well. Maybe the issue pops up on larger data sets, because actual db I'm having issues with, contains way more documents (~1M). I populated it with records using [redis protocol spec](https://redis.io/topics/protocol).

```
127.0.0.1:6379> DBSIZE
(integer) 1232138

127.0.0.1:6379> FT.SEARCH suggestions "@value:hello @value:ki*" # returns the single result
1) (integer) 1
2) "47693b2a"
3) 1) "country"
   2) "US"
   3) "value"
   4) "hello fellow kids"
   5) "traffic"
   6) "5400"
   7) "type"
   8) "phrase"

127.0.0.1:6379> FT.SEARCH suggestions "@value:hello @value:kit*" # returns 24 results, the one above isn't there
 1) (integer) 24
 2) "c389fda3"
 3) 1) "country"
    2) "US"
    3) "value"
    4) "hello kitty"
    5) "traffic"
    6) "201000"
    7) "type"
    8) "phrase"
 4) "b938c864"
 5) 1) "country"
    2) "US"
    3) "value"
    4) "hello kitty games"
    5) "traffic"
    6) "33100"
    7) "type"
    8) "phrase"

...
```

The schema for db is
```
127.0.0.1:6379> FT.CREATE suggestions SCHEMA value text country text traffic NUMERIC SORTABLE type text
```

 Here, I've uploaded the [whole dump to dropbox](https://www.dropbox.com/s/fehavkj1bjgj3pj/dump.rdb?dl=0) (~200 mb .rdb), hope it'll help you to investigate.

**Comment by dvirsky** [comment]
I think I know what it is. The number of prefix completions is capped at 200 by default, for performance reasons. Probably "kitty" is not in the 200 expansions returned for "ki" at that database size. You can change that setting when starting the module by specifying MAXEXPANSIONS

e.g.
```
redis-server --loadmodule ./redisearch.so MAXEXPANSIONS 1024
```

But keep in mind the worst case complexity is the N*M - number of expansions times number of records in each expansion.

**Comment by dvirsky** [comment]
Please try changing this setting and close the issue if it indeed fixes it. If not I'll investigate the RDB, but I'm pretty positive that this is the issue.

**Comment by dvirsky** [comment]
BTW I see that your database is a suggestion database. Have you checked out the FT.SUGG* family of commands? It might be more suitable for your use case.

**Comment by prog13** [comment]
Yep, increasing `MAXEXPANSIONS` value did the trick. Thank a lot for the tip!

As for FT.SUGG* commands — yeah, I've tried to implement my service prototype using those, but ran into some complications. Maybe I just didn't get the idea right. 

Here's my use-case: I need to store a fairly large number of documents with a few numeric and text fields defined and return this documents as an auto-complete suggestions along with data stored in those fields (also sorted by some criteria). 

The main complication is additional data round-trip:

1. server receives the query
2. logic layer performs FT.SUGGET
3. redisearch returns some ids to logic layer
4. logic layer performs MGET to retrieve data stored in suggested docs
5. server returns response to the client

This doubles waiting time for the client in case if business logic and redis are running on different machines, which is a big no-no for an autocompletion service. The only way to store data within suggestion is to use PAYLOAD which is not sortable or searchable.

If there's a command that I've missed which can perform sorting and/or filtering of suggestions, I couldn't be happier to use it instead. For now I find it more efficient to implement my prototype using FT.SEARCH even considering potentially high complexity.

Closing the issue, and again — thanks for your time.

**Comment by dvirsky** [comment]
Try the following: store what you need to retrieve as a payload to suggestions, and use FT.SUGGET WITHPAYLOADS to retrieve it. Perhaps this is what you need?

```
127.0.0.1:6379> FT.SUGADD completions "hello kids" 1 PAYLOAD '{"foo": [1,2,3]}'
(integer) 1
127.0.0.1:6379> FT.SUGADD completions "hello kitty" 1 PAYLOAD '{"foo": [4,5,6]}'
(integer) 2
127.0.0.1:6379> FT.SUGGET completions "hello k" WITHPAYLOADS
1) "hello kids"
2) "{\"foo\": [1,2,3]}"
3) "hello kitty"
4) "{\"foo\": [4,5,6]}"
```

Notice that if you had `hello fellow kids` in an entry, it would NOT be retrieved for the prefix `hello ki`

**Comment by prog13** [comment]
Thanks, I'll try to implement this approach.

**Comment by dvirsky** [comment]
For some cases it's better, for some it isn't (because you have to match a prefix of a term, so if you want permutations of it you need to add them manually). But it's much more optimized for speed than the star search approach, and it has an internal scoring function based on the length of the suffix, the match size, and the record's initial score.

**Comment by dvirsky** [comment]
@prog13 I'm curious as to what solution you'll choose in the end. Let me know, and of course don't hesitate to ask questions if you have any. The mailing list is a good place for non issue questions.

**Comment by prog13** [comment]
@dvirsky thank you! Definitely will keep you updated.

**Comment by prog13** [comment]
@dvirsky Hi!

I ended up using FT.SUG* commands for a few reasons:

- initial data import routine (preparing files in Redis protocol and importing) is way faster
- storing additional data in PAYLOAD turned out to be easy manageable
- sorting of query execution result I replaced with properly pre-calculated SCORE
- filtering has become possible using multiple dictionaries instead of one huge search index
- speed boost is insane, down to ~5 ms instead of ~80-100 when using FT.SEARCH with increased MAXEXPANSIONS
- it was difficult to process user inputs to properly working star completions

Thanks again for the PAYLOAD idea!

**Comment by dvirsky** [comment]
That sounds great! If you would like to write a short post about your
journey with both options, it would be awesome.
