### ISSUE TITLE
RedisSearch/Redis crashes after a while in production

### ISSUE THREAD

**Issue by varun-s** [RedisLabsModules/RediSearch#285]
=== REDIS BUG REPORT START: Cut & paste starting from here ===
30606:M 11 Feb 14:56:46.540 # Redis 4.0.7 crashed by signal: 11
30606:M 11 Feb 14:56:46.541 # Crashed running the instruction at: 0x7ff1e5090db3
30606:M 11 Feb 14:56:46.541 # Accessing address: 0x40
30606:M 11 Feb 14:56:46.541 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/etc/redis-search/RediSearch/src/redisearch.so(NI_Abort+0x3)[0x7ff1e5090db3]

Backtrace:
./redis-server 127.0.0.1:6379(logStackTrace+0x32)[0x468572]
./redis-server 127.0.0.1:6379(sigsegvHandler+0xa6)[0x468c46]
/lib64/libpthread.so.0(+0xf5a0)[0x7ff1edbce5a0]
/etc/redis-search/RediSearch/src/redisearch.so(NI_Abort+0x3)[0x7ff1e5090db3]
/etc/redis-search/RediSearch/src/redisearch.so(II_Abort+0x33)[0x7ff1e5090cf3]
/etc/redis-search/RediSearch/src/redisearch.so(baseResultProcessor_Next+0xd6)[0x7ff1e5084d96]
/etc/redis-search/RediSearch/src/redisearch.so(scorerProcessor_Next+0x29)[0x7ff1e5084e09]
/etc/redis-search/RediSearch/src/redisearch.so(sorter_Next+0x49)[0x7ff1e5085d89]
/etc/redis-search/RediSearch/src/redisearch.so(pager_Next+0x44)[0x7ff1e50852c4]
/etc/redis-search/RediSearch/src/redisearch.so(loader_Next+0x54)[0x7ff1e5084ec4]
/etc/redis-search/RediSearch/src/redisearch.so(ResultProcessor_Next+0x4e)[0x7ff1e50859ee]
/etc/redis-search/RediSearch/src/redisearch.so(Query_SerializeResults+0x76)[0x7ff1e5083516]
/etc/redis-search/RediSearch/src/redisearch.so(QueryPlan_Execute+0x18)[0x7ff1e5083888]
/etc/redis-search/RediSearch/src/redisearch.so(runQueryGeneric+0xeb)[0x7ff1e50958bb]
/etc/redis-search/RediSearch/src/redisearch.so(threadProcessQuery+0x6e)[0x7ff1e5095a0e]
/etc/redis-search/RediSearch/src/redisearch.so(+0x60294)[0x7ff1e50a6294]
/lib64/libpthread.so.0(+0x7de5)[0x7ff1edbc6de5]
/lib64/libc.so.6(clone+0x6d)[0x7ff1ed8f330d]

------ INFO OUTPUT ------
# Server
redis_version:4.0.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:dd1e79e9559bb0c2
redis_mode:standalone
os:Linux 4.9.76-3.78.amzn1.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:6.4.1
process_id:30606
run_id:1f8c8bf79133c73a1b5024a30337943d33f24f49
tcp_port:6379
uptime_in_seconds:29979
uptime_in_days:0
hz:10
lru_clock:8411566
executable:/etc/redis/redis-stable/src/./redis-server
config_file:/etc/redis/redis-stable/redis.conf

# Clients
connected_clients:6
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:1

# Memory
used_memory:1202334464
used_memory_human:1.12G
used_memory_rss:1447354368
used_memory_rss_human:1.35G
used_memory_peak:1202727600
used_memory_peak_human:1.12G
used_memory_peak_perc:99.97%
used_memory_overhead:84375296
used_memory_startup:765840
used_memory_dataset:1117959168
used_memory_dataset_perc:93.04%
total_system_memory:8372740096
total_system_memory_human:7.80G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.20
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0

**Comment by dvirsky** [comment]
Hi, this has been fixed in master but not released yet. Please use the master version and reopen if it happens again.

**Comment by varun-s** [comment]
Works!
Thank you!!
