### ISSUE TITLE
Building on Mac?

### ISSUE THREAD

**Issue by ethanhann** [RedisLabsModules/RediSearch#29]
Are there additional dependencies or build steps for Mac that aren't covered in the quick start guide? Running "make all" produces this output:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C util
make[1]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C rmutil
make[1]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C dep/snowball libstemmer.o
cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-pointer-sign -fPIC  -std=gnu99 -I./ -DREDIS_MODULE_TARGET -mmacosx-version-min=10.6 -O3 -g -Iinclude  -c -o compiler/space.o compiler/space.c
Could not open input file: app/console
Could not open input file: app/console
Could not open input file: app/console
chmod: -R: No such file or directory
chmod: app/logs: No such file or directory
chmod: -R: No such file or directory
chmod: app/cache: No such file or directory
make[1]: *** [compiler/space.o] Error 1
make: *** [snowball] Error 2
```

**Comment by dvirsky** [comment]
That is odd, I'm developing the module on Mac and I've never encountered this problem.

What version is this?

**Comment by amallia** [comment]
Looks like an error in snowball (dep) compilation

**Comment by ethanhann** [comment]
version is 0.9

**Comment by dvirsky** [comment]
@ethanhann I mean what version of Mac OS is this? Looks like you are missing some build tool.

**Comment by ethanhann** [comment]
<img width="246" alt="image" src="https://cloud.githubusercontent.com/assets/402597/23858228/1f73dc9c-07d6-11e7-9780-8c73d94b3795.png">

**Comment by dvirsky** [comment]
I'm using Sierra (10.12.3), though I doubt that is what makes the difference. It looks like some permission problem you have.

**Comment by dvirsky** [comment]
@ethanhann I'm really a bit lost here... I can send you a binary build if you want to play with it. Googling these errors mostly comes up with some PHP related stuff. WTF? :)

Tell me if you want a binary build for now and I'll send you a compiled one.

**Comment by dvirsky** [comment]
@ethanhann Could it be that the directory where the project is compiled has a space in it? your home dir maybe? In any case, I've modified the makefiles so it won't affect anything. Try pulling the current master and see if it builds ok.

**Comment by ethanhann** [comment]
Sorry for wasting your time with this. It looks like at some point I installed something that created an alias called "cc" that was ahead of the real cc in my path. I can compile on fine.

**Comment by dvirsky** [comment]
No worries, moving everything to relative paths was a good idea regardless. Enjoy!
