### ISSUE TITLE
With the long query, return the different result count

### ISSUE THREAD

**Issue by nixlnixl** [RedisLabsModules/RediSearch#293]
I indexed some chinese content and then use the same query to search ,but the result count is not always same.
used querystring:"@content:(word1 | word2 | word3 | ...)"
The return count is not always same when I used about 2000 words.
The return count is same when I query with about 800 words.
But It's not always same when I used about 2000 words.
Is there a max length limit for query string?

**Comment by dvirsky** [comment]
There is a timeout on the maximum query execution time. By default it's 500ms, so the number of results for huge queries is the number of results the engine manages to process in 500ms, and that varies.  See here re configuing this: http://redisearch.io/Configuring/

There should be another option - whether to fail on timeout or do a best effort like today.
