### ISSUE TITLE
Dropping an index with geo field does not delete the geo set.

### ISSUE THREAD

**Issue by ojji** [RedisLabsModules/RediSearch#295]
Trying to drop an index with a geo field doesn't seem to delete the sorted set storing the geographical data. 

Running the following commands:
`FT.CREATE personIdx SCHEMA name TEXT location GEO`
`FT.ADD personIdx 1 1.0 FIELDS name "Derper Herbert" location "19.04,47.497"`
`FT.DROP personIdx`
`KEYS *personIdx*`

Gives the result: 
` 1)  "geo:personIdx/location"`

**Comment by dvirsky** [comment]
thanks. that's indeed a problem.
