### ISSUE TITLE
failing while compile

### ISSUE THREAD

**Issue by manishtoons** [RedisLabsModules/RediSearch#296]
Hi, im not able to compile on centos6,4 and glibc2.12, getting below error, is it supported on centos6.4?

make -C ./src all
make[1]: Entering directory /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src' cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -Werror=implicit-function-declaration -D_GNU_SOURCE -std=gnu99 -I"/repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src" -DREDIS_MODULE_TARGET -DREDISMODULE_EXPERIMENTAL_API -g -ggdb -O3 -c /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/buffer.c -o /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/buffer.o -MMD -MF /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/buffer.d cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -Werror=implicit-function-declaration -D_GNU_SOURCE -std=gnu99 -I"/repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src" -DREDIS_MODULE_TARGET -DREDISMODULE_EXPERIMENTAL_API -g -ggdb -O3 -c /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/byte_offsets.c -o /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/byte_offsets.o -MMD -MF /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/byte_offsets.d cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -Werror=implicit-function-declaration -D_GNU_SOURCE -std=gnu99 -I"/repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src" -DREDIS_MODULE_TARGET -DREDISMODULE_EXPERIMENTAL_API -g -ggdb -O3 -c /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/cndict_loader.c -o /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/cndict_loader.o -MMD -MF /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/cndict_loader.d cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -Werror=implicit-function-declaration -D_GNU_SOURCE -std=gnu99 -I"/repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src" -DREDIS_MODULE_TARGET -DREDISMODULE_EXPERIMENTAL_API -g -ggdb -O3 -c /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/concurrent_ctx.c -o /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/concurrent_ctx.o -MMD -MF /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/concurrent_ctx.d cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -Werror=implicit-function-declaration -D_GNU_SOURCE -std=gnu99 -I"/repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src" -DREDIS_MODULE_TARGET -DREDISMODULE_EXPERIMENTAL_API -g -ggdb -O3 -c /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/config.c -o /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/config.o -MMD -MF /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/config.d cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -Werror=implicit-function-declaration -D_GNU_SOURCE -std=gnu99 -I"/repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src" -DREDIS_MODULE_TARGET -DREDISMODULE_EXPERIMENTAL_API -g -ggdb -O3 -c /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/doc_table.c -o /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/doc_table.o -MMD -MF /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/doc_table.d cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -Werror=implicit-function-declaration -D_GNU_SOURCE -std=gnu99 -I"/repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src" -DREDIS_MODULE_TARGET -DREDISMODULE_EXPERIMENTAL_API -g -ggdb -O3 -c /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/document.c -o /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/document.o -MMD -MF /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/document.d In file included from /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/tag_index.h:7, from /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/document.c:17: /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h: In function ‘RS_StringVal’: /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:52: error: unknown field ‘strval’ specified in initializer /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:52: error: extra brace group at end of initializer /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:52: error: (near initialization for ‘(anonymous)’) /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:52: warning: excess elements in struct initializer /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:52: warning: (near initialization for ‘(anonymous)’) /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h: In function ‘RS_RedisStringVal’: /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:63: error: unknown field ‘rstrval’ specified in initializer /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:63: warning: excess elements in struct initializer /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:63: warning: (near initialization for ‘(anonymous)’) /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h: In function ‘RS_NumVal’: /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:86: error: unknown field ‘numval’ specified in initializer /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:86: warning: excess elements in struct initializer /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:86: warning: (near initialization for ‘(anonymous)’) /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h: In function ‘RS_ArrVal’: /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:93: error: unknown field ‘arrval’ specified in initializer /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:93: error: extra brace group at end of initializer /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:93: error: (near initialization for ‘(anonymous)’) /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:93: warning: excess elements in struct initializer /repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/value.h:93: warning: (near initialization for ‘(anonymous)’) At top level: cc1: warning: unrecognized command line option "-Wno-unused-result" make[1]: *** [/repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src/document.o] Error 1 make[1]: Leaving directory/repo/RnD/workspace/mahendra/redistools/modules/RediSearch/src’
make: * [all] Error 2

**Comment by dvirsky** [comment]
This seems to be a very old compiler that doesn't support some of the features we're using. Try a newer version of CentOs

**Comment by manishtoons** [comment]
thanks for quick response @dvirsky 

So i resolved this issue by changing gcc to latest one ie. 4.8.2 which I had previously built

```
# CC:=$(shell sh -c 'type $(CC) >/dev/null 2>/dev/null && echo $(CC) || echo gcc')
CC=/opt/gcc-4.8.2/bin/cc
export CC
```
