### ISSUE TITLE
How to change schema and re-index on the same redis instance?

### ISSUE THREAD

**Issue by vruizext** [RedisLabsModules/RediSearch#297]
I realized I would like to add a new field, and change one field from `TAG` type to `TEXT`

I have over 200k items indexed, scraped from websites. At this point rebuild the whole index starts to be costly. And I would like to do all the steps working at Redis level, i.e. if possible avoid to export the whole database to an external file to re-index it, which would be straightforward, but IMHO not very efficient.

So I tried the following strategy:

1. Create `new_index` with the new schema

2. Get all the ids indexed in `old_index` and re-index them in `new_index` using `FT.ADDHASH`

3. Drop `old_index`

I expected that, since this hashes are stored in Redis independently from RediSearch, they wouldn't be deleted. But dropping `old_index` drops also all the hashes stored in Redis. Hence, after dropping `old_index`, I can't get the documents content when I run a search in `new_index`.

Hence, I've come to a new strategy

1. Get all the ids indexed in `old_index`, rename the keys adding a prefix `new_index:{id}`

2. Drop `old_index`

3. Create `new_index` with the new schema

4. Rename the keys to their original ids, from `new_index:{id}` to `{id}`

5. Index the hashes in `new_index` using `FT.ADDHASH`

Am I missing something? Is there any other more efficient way to do this?

**Comment by dvirsky** [comment]
No, you are right, FT.DROP should support deleting the hashes as an optional thing only.

**Comment by vruizext** [comment]
Indeed, it was very easy to modify the code to not delete the documents by default

```
int deleteDocuments = RMUtil_ArgIndex("DELETEDOCS", argv, argc) > 0 ? 1 : 0;
Redis_DropIndex(&sctx, deleteDocuments);
```

I will add some tests and send a PR. 

Is `DELETEDOCS` ok for this option flag? I'm sometimes very bad at naming, couldn't come to anything better

**Comment by dvirsky** [comment]
Hi @vruizext. I've added this to the API. Since the default was to delete the documents I've added an option called KEEPDOCS so we won't break backwards compatibility, even though the other way was better. It's now in master and will be published in the next version.
