### ISSUE TITLE
To use the FT.SEARCH preset @word:a* to query the error with the prefix of 'a'

### ISSUE THREAD

**Issue by 1051063313** [RedisLabsModules/RediSearch#298]
When I use the statement: FT.SEARCH preset @word:a* to search for the prefix query that starts with 'a' or  other internal stopword（but I did not manually set the stopword here）, it is wrong: Syntax error at offset 7 near'a',but if a prefix query is carried out with other strings, it will pass normally, and it will not report error.

**Comment by dvirsky** [comment]
First of all, prefixes of less than 2 characters are not supported, but you are right that this should: a. ignore stopwords, and b. give a more coherent error message.

**Comment by 1051063313** [comment]
In my project, I solved the error by set the empty stop word when creating the index. But what if I input some special symbols? For example, FT.SEARCH preset @word:#* will also report "Syntax error at offset 7 near'word '."

**Comment by dvirsky** [comment]
Again, we limit the completions to a minimum of two character prefixes. You can change that in the module configuration. See http://redisearch.io/Configuring/#minprefix

**Comment by mnunberg** [comment]
Closing this issue - issue has been addressed.
