### ISSUE TITLE
Python - Is Index Exists

### ISSUE THREAD

**Issue by aviperetz34** [RedisLabsModules/RediSearch#30]
when upgrading from 0.4 to 0.9, creating an existing index raised a ResponseError.
is there a way to check if index exist without an exception?

**Comment by dvirsky** [comment]
First of all, if you are upgrading between 0.4 and 0.9 you need to delete the data and start fresh. 

Second, the way to check the existence of an index is to call `FT.INFO` on it, and if the index does not exist you receive an error.

So basically:

```py

try:
  client.info()
except ResponseError:
  client.create_index(...)
```

**Comment by dvirsky** [comment]
I'm closing the issue as this doesn't seem to be a bug. 

I might change the key naming in a future version in a way that the usual redis EXISTS and TYPE commands will apply to inverted indexes.
