### ISSUE TITLE
Make all on Linux fails

### ISSUE THREAD

**Issue by tsundara** [RedisLabsModules/RediSearch#305]
I am on  Linux and am trying to compile  Redisearch source with the make all command. However, I get some errors. Any help is appreciated. Below is the std error.

$ make all

cc -Wall -Wno-unused-function -Wno-unused-variable -Wno-unused-result -fPIC -Werror=implicit-function-declaration -D_GNU_SOURCE -std=gnu99 -I"/dis/redisearch/RediSearch-master/src" -DREDIS_MODULE_TARGET -DREDISMODULE_EXPERIMENTAL_API  -g -ggdb -O3  -Wfree-nonheap-object   -c /dis/redisearch/RediSearch-master/src/aggregate/aggregate_request.c -o /dis/redisearch/RediSearch-master/src/aggregate/aggregate_request.o -MMD -MF /dis/redisearch/RediSearch-master/src/aggregate/aggregate_request.d

cc1: error: unrecognized command line option "-Wfree-nonheap-object"
cc1: warning: unrecognized command line option "-Wno-unused-result"
make: *** [/dis/redisearch/RediSearch-master/src/aggregate/aggregate_request.o] Error 1

**Comment by dvirsky** [comment]
What distro and version? Looks like an old gcc.

**Comment by dvirsky** [comment]
It take it that you've managed to build it? Reopen if not.
