### ISSUE TITLE
Duplicate responses in results with geo fields

### ISSUE THREAD

**Issue by stockholmux** [RedisLabsModules/RediSearch#306]
I'm getting duplicate results when using a GEO filter. I've played with the other filters combinations (numeric, ft, text, etc) and the dupes only seem to be returned when there a geo filter involved.

```
"ft.create" "query-dupe-test" "SCHEMA" "budget" "NUMERIC" "SORTABLE" "original_title" "TEXT" "tags" "TAG" "waypoint" "GEO"
OK
"ft.add" "query-dupe-test" "item-1" "1" "FIELDS" "budget" "3800" "original_title" "abc" "tags" "alberta" "waypoint" "-113.524,53.5244"
OK
"ft.add" "query-dupe-test" "item-2" "1" "FIELDS" "budget" "1800" "original_title" "xyz" "tags" "ontario" "waypoint" "-79.395,43.661667"
OK
"ft.search" "query-dupe-test" "@waypoint:[-113.52 53.52 20 mi]|@tags:{ontario}"
1) (integer) 2
2) "item-2"
3) 1) "budget"
   2) "1800"
   3) "original_title"
   4) "xyz"
   5) "tags"
   6) "ontario"
   7) "waypoint"
   8) "-79.395,43.661667"
4) "item-2"
5) 1) "budget"
   2) "1800"
   3) "original_title"
   4) "xyz"
   5) "tags"
   6) "ontario"
   7) "waypoint"
   8) "-79.395,43.661667"
```

Using `redis_version:4.0.9` and RediSearch 10008.

The `FT.EXPLAIN` of the query is 
```
UNION {
  GEO waypoint:{-113.520000,53.520000 --> 20.000000 mi}
  TAG:@tags {
    ontario
  }
}
```

If you break down the query and do the geo filter and tag search separately you get the expected items (`item-1` for geofilter and `item-2` for the tag search)

**Comment by mnunberg** [comment]
I'm debugging this now - probably something in the IdListIterator stuff.

**Comment by dvirsky** [comment]
Mark, no matter how trivial the fix might seem, do not push to master/1.0.
This is dragon territory, tread carefully

**Comment by mnunberg** [comment]
The offending line seems to be: https://github.com/RedisLabsModules/RediSearch/blob/master/src/id_list.c#L17

Which basically invalidates the iterator for use in SkipTo (which checks to see if HasNext works). isEOF should only be set when the current iteration won't return results.

Another way to fix this is to not use HasNext() when using SkipTo, or to reorder it (for example, only use HasNext if we are really *advancing* the iterator):

https://github.com/RedisLabsModules/RediSearch/blob/1.0/src/index.c#L182

**Comment by dvirsky** [comment]
@mnunberg that's actually intentional - we mark the iterator as "at end" for the next check, but return ok for the current read. It might accidentally fix this issue but it seems to be something else. I'm checking.

**Comment by dvirsky** [comment]
Fixed
