### ISSUE TITLE
ft.search Syntax error at offset xxxxxx near 'https'

### ISSUE THREAD

**Issue by francisoliverlee** [RedisLabsModules/RediSearch#307]
i store some data like
{
   'url':'https://github.com'
}
the error appears when i search by "@url:https://github.com"

it seems i have a **colon** in the express values, 
how can i do with it ? i can not find answers in the command bellow

[http://redisearch.io/Commands/#parameters_4](url)

FT.SEARCH {index} {query} [NOCONTENT] [VERBATIM] [NOSTOPWORDS] [WITHSCORES] [WITHPAYLOADS] [WITHSORTKEYS]
  [FILTER {numeric_field} {min} {max}] ...
  [GEOFILTER {geo_field} {lon} {lat} {raius} m|km|mi|ft]
  [INKEYS {num} {key} ... ]
  [INFIELDS {num} {field} ... ]
  [RETURN {num} {field} ... ]
  [SUMMARIZE [FIELDS {num} {field} ... ] [FRAGS {num}] [LEN {fragsize}] [SEPARATOR {separator}]]
  [HIGHLIGHT [FIELDS {num} {field} ... ] [TAGS {open} {close}]]
  [SLOP {slop}] [INORDER]
  [LANGUAGE {language}]
  [EXPANDER {expander}]
  [SCORER {scorer}]
  [PAYLOAD {payload}]
  [SORTBY {field} [ASC|DESC]]
  [LIMIT offset num]

**Comment by mnunberg** [comment]
You can try escaping the `:` with a `\` though in my experimenting it might not work as expected. Anyway, your search query would not yield results anyway as it is tokenized as separate terms (i.e. `https' and `github` and `com`

**Comment by francisoliverlee** [comment]
it does work with words-separated.
can we use **:** in the query?

**Comment by itamarhaber** [comment]
As of 1.2.0 we have full escaping in document text and tags: https://github.com/RedisLabsModules/RediSearch/commit/dccd1447d5f3399ff5ca90bc3f92c6d636167a9c

Please consider closing this issue.
