### ISSUE TITLE
Sorting on multiple fields

### ISSUE THREAD

**Issue by manishtoons** [RedisLabsModules/RediSearch#311]
Hi,

I was just wondering if its possible to add sorting similar to the Aggregations API, 
something like:

`SORTBY 4 @foo ASC @bar DESC`

it would be very helpful to have in `SEARCH` function.

**Comment by manishtoons** [comment]
That sound perfect! having such functionality could really help a lot! thanks a lot. I already tried AGGREGATE its pretty powerful and fast.

**Comment by dvirsky** [comment]
which of them? search through aggregate or multiple SORTBY?

**Comment by manishtoons** [comment]
search through aggregate

**Comment by mnunberg** [comment]
Closing, I believe this is done via aggregations.

**Comment by Nomafin** [comment]
Sorry to comment on closed issue, but is there a way to combine infields parameter from search and multiple sortby clauses from aggregations?
