### ISSUE TITLE
Please drop -mpopcnt from CFLAGS

### ISSUE THREAD

**Issue by lamby** [RedisLabsModules/RediSearch#313]
RediSearch stopped being compilable in Debian (see [#896593](https://bugs.debian.org/896593)) due to the use of -mpopcnt. This is not portable, alas.

**Comment by dvirsky** [comment]
I don't want to completely drop it, but let's figure out a way to find out whether it's supported or not.

**Comment by lamby** [comment]
That's not possible at compile-time I'm afraid. `POPCNT` was introduced in SSE 4.2 so if my processor is SSE 4.1 the instruction will be simply missing and I'll get an illegal instruction error at runtime...

**Comment by dvirsky** [comment]
It's not a problem to test for it though.

**Comment by dvirsky** [comment]
Oh I get what you mean, compile time is irrelevant in this case. 

Anyway it's not that important,  I can just go fo a naive, slightly slower implementation of it and that's it.

**Comment by dvirsky** [comment]
@lamby please try 1.0, I've removed the flag and any reference to the instructions, and went with a simple table based population counting method.

**Comment by dvirsky** [comment]
Removing the flag without modifying the code will make the module fail in
some systems.

**Comment by lamby** [comment]
> Removing the flag without modifying the code will make the module fail in some systems.

How come, out of interest?

**Comment by dvirsky** [comment]
It will just crash with "undefined symbol" when you try to load the module.

**Comment by lamby** [comment]
Thanks! Uploaded in `redisearch 1.0.10-3` :)

**Comment by dvirsky** [comment]
@lamby I've released 1.1.0 today, a pretty big change.
