### ISSUE TITLE
 FT.search   GEOFILTER is not returning any result

### ISSUE THREAD

**Issue by ashutoshtripathi** [RedisLabsModules/RediSearch#321]
Hi,
I created & added index as below:
`FT.CREATE myIndex SCHEMA id TEXT field1 TEXT field2 TEXT  location GEO `
`FT.ADD myIndex 12Id 1 FIELDS id "0" field1 "0" field2 "99501"  location "-98.17,38.71" `

And I am trying to search the data as below:
`FT.search myIndex   GEOFILTER location -98.71 38.17 1000 mi`

But I am NOT getting any results

Version Details:
Redis server v=4.0.9 sha=00000000:0 malloc=libc bits=64 build=c49f4faf7c3c647a

**Comment by mnunberg** [comment]
The reason this is failing is because you are not providing any query string (I believe you should just be able to use `*` if you just want a geo query. so for example

```
127.0.0.1:6379> FT.search myIndex "*" GEOFILTER location -98.71 38.17 1000 mi
1) (integer) 1
2) "12Id"
3) 1) "id"
   2) "0"
   3) "field1"
   4) "0"
   5) "field2"
   6) "99501"
   7) "location"
   8) "-98.17,38.71"
```

I would advise to also use the newer embedded syntax as well, which looks nicer :)

```
127.0.0.1:6379> FT.search myIndex "@location:[-98.71 38.17 1000 mi]"
1) (integer) 1
2) "12Id"
3) 1) "id"
   2) "0"
   3) "field1"
   4) "0"
   5) "field2"
   6) "99501"
   7) "location"
   8) "-98.17,38.71"
```

**Comment by ashutoshtripathi** [comment]
Thank you very much. It was very helpful and I feel good to be part of Redis community.
