### ISSUE TITLE
Are there any plans for Stored Queries?

### ISSUE THREAD

**Issue by dremekie** [RedisLabsModules/RediSearch#322]
Please refer to:
- https://github.com/flaxsearch/luwak
- https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-percolate-query.html

Basically, you store one or more queries, then send in a document to see what queries it match that document.

**Comment by dvirsky** [comment]
Not at the moment. Might be an interesting idea.

**Comment by rustyedges** [comment]
latest request is now in #3175
