### ISSUE TITLE
Redis is slow

### ISSUE THREAD

**Issue by jtiq** [RedisLabsModules/RediSearch#328]
Redis is slow when I edit/delete/add new documents. Indexed 250k documents. After drop the index and reindex documents, Redis returns documents fast.

**Comment by mnunberg** [comment]
Can you define how slow is slow? a bit of a slowdown might be normal, but maybe we're not properly releasing locks somewhere.

**Comment by jtiq** [comment]
When send command `bgsave` Redis is not available for operations.

**Comment by jtiq** [comment]
Also, the size of the dump after indexing is significantly less than it was before the edit/delete/add. In the index, apparently, there are old indices or garbage.

**Comment by mnunberg** [comment]
`BGSAVE` should be immediate, other than increasing CPU usage for the duration of the same. I'm unsure what you mean about the index size though.

**Comment by jtiq** [comment]
Size of the `dump.rdb`

**Comment by mnunberg** [comment]
Are you saying that after adding more documents the index size decreases? that's certainly possible especially if you are deleting documents, depending on the documents' contents.

**Comment by jtiq** [comment]
Active use in the form of removal and/or modification greatly slows down all operations in Redis.

**Comment by mnunberg** [comment]
At what rate of concurrency are you working with, and how large are your documents?

**Comment by jtiq** [comment]
> Are you saying that after adding more documents the index size decreases? that's certainly possible especially if you are deleting documents, depending on the documents' contents.

After ReIndex of documents

**Comment by mnunberg** [comment]
I'm not sure what you mean by reindex. RS never indexes a document more than once. Are you doing a lot of replaces? Internally a replace is really a delete+add.

**Comment by jtiq** [comment]
34 NUMERIC columns;
2 TEXT columns;
All columns SORTABLE.

**Comment by jtiq** [comment]
NUMERIC data is mostly changed.

**Comment by jtiq** [comment]
1) Do `FT.DROP indexName`
2) I create a new indexName with the fields I need
3) I add all fields from MySQL

After these actions, Redis works faster

**Comment by mnunberg** [comment]
So we don't have any kind of garbage collection on numeric indexes currently (working on this problem right now, actually). This means that the database size will increase and increase the more you modify the numeric indexes.

Do you need to actually index all these numeric fields? it sounds like you might benefit from PARTIAL and NOINDEX attributes -- though I'm unsure if they work with non-text fields (if they don't, I'll fix that in the next release).

**Comment by jtiq** [comment]
> So we don't have any kind of garbage collection on numeric indexes currently (working on this problem right now, actually). This means that the database size will increase and increase the more you modify the numeric indexes.

> Do you need to actually index all these numeric fields? it sounds like you might benefit from PARTIAL and NOINDEX attributes -- though I'm unsure if they work with non-text fields (if they don't, I'll fix that in the next release).

I use `REPLACE PARTIAL` when edit the document

**Comment by mnunberg** [comment]
But is the field declared as NOINDEX?

**Comment by jtiq** [comment]
> But is the field declared as NOINDEX?
No.. I used it for search :)

**Comment by jtiq** [comment]
Delete document with `DD`

**Comment by slavaGanzin** [comment]
@jtiq "When send command bgsave Redis is not available for operations."

It *can be* symptoms you don't set __transparent huge pages__ and __overcommit memory__. Here is guide: https://redis.io/topics/admin

**Comment by jtiq** [comment]
> It can be symptoms you don't set transparent huge pages and overcommit memory. Here is guide: 

I fulfilled these conditions

Русский? Если да, то я выполнил эти штуки

**Comment by mnunberg** [comment]
This doesn't seem to be an issue with RS
