### ISSUE TITLE
Tokenization escaping not working

### ISSUE THREAD

**Issue by KimDroid** [RedisLabsModules/RediSearch#330]
Hi. Can I ask something..?
I tried that
########################################
FT.CREATE idx_test SCHEMA ip TEXT

FT.ADD idx_test 1 1 FIELDS ip "111\\.222\\.33\\.44"

FT.SEARCH idx_test "@ip:111.222.33.44"
FT.SEARCH idx_test "@ip:111\\.222\\.33\\.44"
FT.SEARCH idx_test "@ip:111\\\.222\\\.33\\\.44"
########################################

but I cannot get a result.

I referenced the following site
[http://redisearch.io/Escaping/](http://redisearch.io/Escaping/)

What is my problem..?

**Comment by mnunberg** [comment]
You need to perform the same escape in the document itself, i.e. when doing FT.ADD

**Comment by KimDroid** [comment]
Sorry I can't understand.
I added index with "\" character
and I search with "\"

also I added index "111.222.33.44" but same result..

**Comment by salt4pommes** [comment]
Works well for me if you also escape the backslash:

FT.CREATE idx_test SCHEMA ip TEXT

FT.ADD idx_test 1 1 FIELDS ip "111\\.222\\.33\\.44"

FT.SEARCH idx_test "@ip:111\\.222\\.33\\.44"

**Comment by KimDroid** [comment]
I changed version 1.1.0 to 1.2.0
and then it works!

Thank you.
