### ISSUE TITLE
I want to add the field dynamic.

### ISSUE THREAD

**Issue by KimDroid** [RedisLabsModules/RediSearch#334]
I want to make the field dynamic.

For example

FT.CREATE user SCHEMA name TEXT

and then...maybe

FT.ADDFIELDS user SCHEMA age numeric

**Comment by KimDroid** [comment]
or... can I use default field type when add a new field?

**Comment by itamarhaber** [comment]
Hello @KimDroid,

Thanks for the feature request. Could you please tell us more about your use case and why you would want to add fields post index creation?

1. At the moment you can only work around this by:
  a. Creating initially a lot of to-be-used fields (common SQL trick) <- wasteful, but does the job; or
  b. Using a tag field to store something like 'age=45' and aggregating on it <- no numeric ranges; or
  c. Rebuild the index (that's what most search engines do); or
  d. A combo of the above.

2. The good news is that the next release (v1.2.1) will feature a way to add new fields (e.g. `FT.ALTER <idx> SCHEMA ADD <field>...`). Note, however, that new fields (and indexing of) will only apply to newly created documents. I'd be happy to hear if this is something that you'd be able to use to solve your requirement.

**Comment by mnunberg** [comment]
This is supported by FT.ALTER. Closing - please reopen if this doesn't work for you
