### ISSUE TITLE
Ubuntu - After 'make all' command, Then?

### ISSUE THREAD

**Issue by dendihandian** [RedisLabsModules/RediSearch#341]
I'm using Homestead VM and I have cloned the repository to a directory. Then I change the directory to Redisearch/src and executed `make all` command. The result seems OK and fine with no error noticed. I already have Redis installed in `/etc/systemd/system/redis.service` .

Then I expect this command `/etc/systemd/system/redis.service --loadmodule ./redisearch.so
` to be executed as explained in documentation. But I find this command is wrong or I miss something?

Later, If this command only need to be executed manually, how I can automaticaly to reload redisearch on redis?

**Comment by itamarhaber** [comment]
Closing this issue - feel free to reopen if needed.
