### ISSUE TITLE
Use redisearch with redis cluster

### ISSUE THREAD

**Issue by ashutoshtripathi** [RedisLabsModules/RediSearch#345]
Hi,
I am not able to use redisearch with redis cluster. Is it supported?

**Comment by itamarhaber** [comment]
Hello @ashutoshtripathi,

RediSearch will not work correctly on a cluster. The enterprise version of RediSearch, which is commercially available from Redis Labs, does support a cluster set up and scales to hundreds of nodes, billions of documents and terabytes of data. See the [Redis Labs Website](https://redislabs.com/redis-enterprise-documentation/developing/modules/redisearch/) for more details.
