### ISSUE TITLE
Fuzzy Search: LD > 1 also matching

### ISSUE THREAD

**Issue by xevix** [RedisLabsModules/RediSearch#347]
Example

```
FT.CREATE myIdx SCHEMA title TEXT WEIGHT 5.0
FT.ADD myIdx doc1 1.0 FIELDS title "some"
FT.ADD myIdx doc2 1.0 FIELDS title "now"
FT.SEARCH myIdx "%som%"
```

Output

```
OK
OK
OK
1) (integer) 2
2) "doc2"
3) 1) "title"
   2) "now"
4) "doc1"
5) 1) "title"
   2) "some"
```

Expected: "som" would require changing the first and last letter to match now, giving it an LD score of 2. The RediSearch docs say that LD of 1 is used, so this shouldn't be matching.

Is this the expected behavior?

**Comment by mnunberg** [comment]
Note, @stockholmux has also seen this behavior.

**Comment by mnunberg** [comment]
Fixed in latest commit https://github.com/RedisLabsModules/RediSearch/commit/2afb289aa749ce72d2654748e76fb4344bf8451d
