### ISSUE TITLE
Syntax error at offset 0 near ''

### ISSUE THREAD

**Issue by tuananh** [RedisLabsModules/RediSearch#353]
when i do a query with only 1 char `(`, i got this error
```
FT.CREATE myIdx SCHEMA name TEXT
FT.ADD myIdx doc1 1.0 FIELDS name "ha noi"
FT.ADD myIdx doc2 1.0 FIELDS name "ha nam"

FT.SEARCH myIdx "(" WITHPAYLOADS INORDER VERBATIM SCORER BM25
```

**Comment by itamarhaber** [comment]
Hello @tuananh,

This doesn't look like an issue to me. The search query that you're using, i.e "(", is indeed errornous - the left parentheses (as well as the right one, and a bunch of others) is a special character that's used for explicitly grouping search terms. Refer to the docs for more info on query syntax.

Closing but feel free to reopen if I misunderstood.
