### ISSUE TITLE
tags with ":" characters are not matched - escaping issues?

### ISSUE THREAD

**Issue by mmasouras** [RedisLabsModules/RediSearch#356]
I use ":" characters in tags (the tags themselves are redis keys) and RediSearch seems to fail to find them when I query with the tag. 

Here's an example that reproduces the problem:

```
127.0.0.1:6379> FT.CREATE idx SCHEMA title TEXT tags TAG
OK
127.0.0.1:6379> HGETALL foo
1) "title"
2) "blah"
3) "tags"
4) "a:b,c:d"
127.0.0.1:6379> FT.ADDHASH idx foo 1 REPLACE
OK
127.0.0.1:6379> FT.SEARCH idx blah
1) (integer) 1
2) "foo"
3) 1) "title"
   2) "blah"
   3) "tags"
   4) "a:b,c:d"
127.0.0.1:6379> FT.SEARCH il1 @tags:{c\:d}
1) (integer) 0
```

**Comment by mnunberg** [comment]
The default tag separator is `,` and not `;`. You can specify an alternate separator with the SEPARATOR keyword when creating the index, e.g. `FT.CREATE ... tags TAG SEPARATOR ';'`

**Comment by mmasouras** [comment]
":" is not a separator, it's part of the tag id. The separator is "," in my example: "a:b,c:d"

**Comment by mnunberg** [comment]
Perhaps it's because you're double-escaping? Try FT.EXPLAIN to see what is actually being searched. On my version, your search actually gives a syntax error, and this might be related to recent fixes.

**Comment by mmasouras** [comment]
The double escaping was there so that the git code viewer will display the \ correctly. I changed it to a single \ and it seems git shows it correctly now. 

Anyway, this query does not produce syntax errors but doesn't return anything:
FT.SEARCH il1 @tags:{c\:d}

**Comment by mnunberg** [comment]
What version are you using? works fine here

```
127.0.0.1:6379> FT.SEARCH idx @tags:{c\:d}
1) (integer) 1
2) "foo"
3) 1) "title"
   2) "blah"
   3) "tags"
   4) "a:b,c:d"
```

**Comment by mmasouras** [comment]
I cloned from trunk last week - this is what I got:
127.0.0.1:6379> MODULE LIST
1) 1) "name"
   2) "ft"
   3) "ver"
   4) (integer) 10200

I confirmed that the series of commands I pasted above still doesn't work, I am surprised it works for you.

**Comment by mmasouras** [comment]
More info:

127.0.0.1:6379> FT.TAGVALS idx tags
1) "a:b"
2) "c:d"
127.0.0.1:6379> FT.SEARCH il1 @tags:{c\:d}
1) (integer) 0

**Comment by mmasouras** [comment]
One tangential question: Will I save space / speed if I use as short tag names as possible - e.g. is a numerical id like "55" better than "some:tags:have:long:ids".

Thanks for looking into this.

**Comment by mnunberg** [comment]
re mem savings, tag indexes are implemented in a fashion somewhat similar to actual search indexes. Basically, the space savings are proportional to the uniqueness of tags rather than their length. If you have 1M documents with a tag `veryverygverylong` and 1M documents with a tag `z`, you will not gain any savings. Most of the overhead is in the actual existence of a specific tag rather than its actual length (of course, if you have 1M tags, and each one is several K, you might start seeing the difference; however tag lengths are capped at 10k anyway).

**Comment by mmasouras** [comment]
Hold on, there was a typo above - i was searching the wrong index. It seems to work now for the example I provided, sorry for the fuss. I 'll report back if I encounter other problems.

Thanks!

**Comment by mnunberg** [comment]
Can you close this if it's resolved? :)
