### ISSUE TITLE
RedisSearch do not support  command 'FT.CREATE' ?

### ISSUE THREAD

**Issue by apple987** [RedisLabsModules/RediSearch#357]
hi! when I start the JRedisSearch demo,the junit print error"ERR unknown command 'FT.CREATE' at redis.clients "my redis version 4.0.2.0,jdk1.8,how to solve lt?

**Comment by dvirsky** [comment]
This means you did not load the module into your redis instance when starting it.

**Comment by apple987** [comment]
how  to install  redisSearch module？my   redis  version  is 4.0.2 windows x64 edition，could you tell how to install  redissearch？thanks

**Comment by itamarhaber** [comment]
Hello @apple987,

I am not aware of a version of Redis for windows that supports modules. I recommend that you use the official Redis project - the module is certified to work with it.

Closing this issue, but feel free to reopen if needed.
