### ISSUE TITLE
Redisearch list indexes

### ISSUE THREAD

**Issue by aviperetz34** [RedisLabsModules/RediSearch#36]
Hi,
i'm currently using RediSeacrh 0.4 in production and i use FT.INFO num_docs field to get the number of documents in my index. in this method i get less documents then i expect and last documents than showed in __redis_docIdCounter__, but i guess this counter is global to all indexes.
Is there a way to list indexes ? this will help me debug the problem.

**Comment by dvirsky** [comment]
hi @aviperetz34. I suggest you upgrade to a more recent version of the engine that doesn't use redis_docIdCounter (which indeed was global to all indexes). 0.4 is super old. I suggest you switch to 0.10 ASAP

**Comment by aviperetz34** [comment]
i work in Videocites.
well this will be great but this is not possible for now.
can you tell me the integrity of FT.INFO num_docs field in this version.

**Comment by dvirsky** [comment]
I know, I'm talking to Eitan, he's waiting for 0.11 actually to switch (a fix I'm making especially for you guys). num_docs should be 100% accurate. Things that might make it less than the number of documents you _think_ you should have: 

1. inserting duplicate documents.
2. deleting documents (not sure if it's even supported in 0.4)
3. inserting invalid documents (with no tokens or fields maybe)

I would not invest time investigating bugs in a 3 month old version...

**Comment by uglide** [comment]
@dvirsky Is it possible to retrieve a list of RediSearch indexes in redis-server?
