### ISSUE TITLE
FT.EXPLAIN to output as a simple string for less terrible UX

### ISSUE THREAD

**Issue by stockholmux** [RedisLabsModules/RediSearch#361]
In `redis-cli`:
```
127.0.0.1:6379> FT.EXPLAIN permits "car port"
"INTERSECT {\n  UNION {\n    car\n    +car(expanded)\n  }\n  UNION {\n    port\n    +port(expanded)\n  }\n}\n"
```

This is pretty poor UX. Since `FT.EXPLAIN` is for humans, it would be nice to just output the results as a simple string. While this can be accomplished by using the `--raw` switch on `redis-cli` it kind of interrupts the flow of working to have to exit `redis-cli` or keep another window open. 

If the result was sent as simple string  (à la `INFO`) rather than a bulk string, we'd need a much nicer output. Desired would be:

```
> FT.EXPLAIN permits "car port"
INTERSECT {
  UNION {
    car
    +car(expanded)
  }
  UNION {
    port
    +port(expanded)
  }
}
```

**Comment by stockholmux** [comment]
PR #362

**Comment by mnunberg** [comment]
can you make the test pass too? :D

**Comment by mnunberg** [comment]
We can't fix this in the form of a simple string because of the way the Redis protocol works. Simple strings cannot contain embedded newlines.
