### ISSUE TITLE
RediSearch produces corrupt rdb file -  'numericdx'

### ISSUE THREAD

**Issue by mmasouras** [RedisLabsModules/RediSearch#366]
This is an example that causes the error - also see https://github.com/RedisLabsModules/RediSearch/issues/266
for a list of alternative paths to get to the same result.

````
127.0.0.1:6379> FT.CREATE atest SCHEMA textfield TEXT numfield NUMERIC
OK
127.0.0.1:6379> HSET foo textfield blah numfield 1
(integer) 2
127.0.0.1:6379> FT.ADDHASH atest foo 1 REPLACE
OK
127.0.0.1:6379> hset foo numfield 2
(integer) 0
127.0.0.1:6379> FT.ADDHASH atest foo 1 REPLACE
OK

$ redis-server&
.....
12739:M 20 Jun 12:52:22.680 # Error loading data from RDB (short read or EOF). Read performed by module 'ft' about type 'numericdx' after reading '0' bytes of a value.

````

**Comment by mmasouras** [comment]
The error message looks identical.

I can't tell what kind of corruption happens under the hood.

**Comment by mnunberg** [comment]
The error messages will usually look the same. We'll need to get more detailed in our error reporting.

**Comment by mmasouras** [comment]
Some more info that might help home-in. The error seems to be caused when using REPLACE even if you haven't changed the value in the db, or if you delete the key from the index:

1. Same value
```
127.0.0.1:6379> FT.CREATE atest SCHEMA numfield NUMERIC
OK
127.0.0.1:6379> hset foo numfield 1
(integer) 1
127.0.0.1:6379> FT.ADDHASH atest foo 1 REPLACE
OK
127.0.0.1:6379> FT.ADDHASH atest foo 1 REPLACE
OK
127.0.0.1:6379> SHUTDOWN
$(restart)
....
12999:M 20 Jun 15:03:05.838 # Error loading data from RDB (short read or EOF). Read performed by module 'ft' about type 'numericdx' after reading '0' bytes of a value.
```
2. Add, Delete, Add doesn't work either:
```
127.0.0.1:6379> FT.CREATE atest SCHEMA numfield NUMERIC
OK
127.0.0.1:6379> hset foo numfield 1
(integer) 1
127.0.0.1:6379> FT.ADDHASH atest foo 1 REPLACE
OK
127.0.0.1:6379> FT.DEL atest foo
(integer) 1
127.0.0.1:6379> FT.ADDHASH atest foo 1 REPLACE
OK
127.0.0.1:6379> SHUTDOWN

$(restart)
....
13015:M 20 Jun 15:04:49.024 # Error loading data from RDB (short read or EOF). Read performed by module 'ft' about type 'numericdx' after reading '0' bytes of a value.
```

**Comment by mmasouras** [comment]
Ouch - it also happens if you just delete a document - no replace necessary

```
127.0.0.1:6379> FT.CREATE atest SCHEMA numfield NUMERIC
OK
127.0.0.1:6379> hset foo numfield 2
(integer) 1
127.0.0.1:6379> FT.ADDHASH atest foo 1
OK
127.0.0.1:6379> FT.DEL atest foo
(integer) 1
127.0.0.1:6379> SHUTDOWN
....
13190:M 20 Jun 15:22:35.527 # Error loading data from RDB (short read or EOF). Read performed by module 'ft' about type 'numericdx' after reading '0' bytes of a value.
```

**Comment by mmasouras** [comment]
I am checking out some older commits - so far it seems that this commit is OK (does not reproduce the error):

commit 57a8bbb4cae0d8011bbbab42618761e8e8a023de (HEAD)
Author: Dvir Volk <dvirsky@gmail.com>
Date:   Sun Jan 21 17:20:46 2018 +0200

    Fixed corruption of rdb due to duplicate numeric entries.

**Comment by mnunberg** [comment]
Ok, I've managed to reproduce it. I think the fix is fairly simple, actually:

```
diff --git a/src/gc.c b/src/gc.c
index da8e6b14..cae2d97d 100644
--- a/src/gc.c
+++ b/src/gc.c
@@ -272,6 +272,7 @@ size_t gc_NumericIndex(RedisModuleCtx *ctx, GarbageCollectorCtx *gc, int *status
     blockNum = InvertedIndex_Repair(nextNode->range->entries, &sctx->spec->docs, blockNum,
                                     DOCS_TO_SCAN_EACH_ITERATION, &bytesCollected, &recordsRemoved);
     /// update the statistics with the the number of records deleted
+    numericGcCtx->rt->numEntries -= recordsRemoved;
     totalRemoved += recordsRemoved;
     gc_updateStats(sctx, gc, recordsRemoved, bytesCollected);
     // blockNum 0 means error or we've finished
```

**Comment by JefStat** [comment]
Added more details to my comment. I run redis without AOF by default but I'm making the changes to enable it by default now.

**Comment by mnunberg** [comment]
Ahh, I meant that AOF without the preamble setting won't work. I'll look into the steps soon.

**Comment by mnunberg** [comment]
Ok, I've managed to reproduce!-

**Comment by salt4pommes** [comment]
@JefStat is right :) The corrupted database works when enabling:

 appendonly yes
 aof-use-rdb-preamble yes

Only rdb seems to be corrupted.

**Comment by mnunberg** [comment]
Should work now! - and yes, it was related to RDB.

**Comment by mmasouras** [comment]
Does that fix the PAYLOADS issue, or also the REPLACE issue reported at the top?

**Comment by mnunberg** [comment]
There's a commit before that, which fixes the issue at the top

**Comment by mmasouras** [comment]
I now get a different error for the steps at the top:
44219:M 09 Jul 11:16:46.086 # The RDB file contains module data for the module '' that is not terminated by the proper module value EOF marker

I use redis 4.0.10 and built redisearch from head.

// start redis with no dump.rdb file (no data)

$ redis-server /Users/michaelmasouras/src/redis-4.0.10/redis.conf &

43502:M 09 Jul 11:02:50.626 * <ft> RediSearch version 1.2.0 (Git=v1.2.0-159-gacd8b6a)
43502:M 09 Jul 11:02:50.626 * <ft> concurrency: ON, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, search pool size: 20, index pool size: 8,
43502:M 09 Jul 11:02:50.627 * <ft> Initialized thread pool!
43502:M 09 Jul 11:02:50.627 * Module 'ft' loaded from /Users/michaelmasouras/src/redis-4.0.10/redisearch.so


// make an index and write some data

127.0.0.1:6379> FT.CREATE atest SCHEMA textfield TEXT numfield NUMERIC
OK
127.0.0.1:6379> HSET foo textfield blah numfield 1
(integer) 2
127.0.0.1:6379> FT.ADDHASH atest foo 1 REPLACE
OK
127.0.0.1:6379> hset foo numfield 2
(integer) 0
127.0.0.1:6379> FT.ADDHASH atest foo 1 REPLACE
OK
127.0.0.1:6379> SHUTDOWN


sh43502:M 09 Jul 11:05:53.914 # User requested shutdown...
43502:M 09 Jul 11:05:53.914 * Saving the final RDB snapshot before exiting.
43502:M 09 Jul 11:05:53.914 * <ft> Trie: saving 1 nodes.
43502:M 09 Jul 11:05:53.915 * DB saved on disk
43502:M 09 Jul 11:05:53.915 * Removing the pid file.
43502:M 09 Jul 11:05:53.916 # Redis is now ready to exit, bye bye...


// start redis again


$ redis-server /Users/michaelmasouras/src/redis-4.0.10/redis.conf &

44219:M 09 Jul 11:16:46.085 # Server initialized
44219:M 09 Jul 11:16:46.085 * <ft> RediSearch version 1.2.0 (Git=v1.2.0-167-g407c761)
44219:M 09 Jul 11:16:46.085 * <ft> concurrency: ON, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, search pool size: 20, index pool size: 8,
44219:M 09 Jul 11:16:46.086 * <ft> Initialized thread pool!
44219:M 09 Jul 11:16:46.086 * Module 'ft' loaded from /Users/michaelmasouras/src/redis-4.0.10/redisearch.so
44219:M 09 Jul 11:16:46.086 # The RDB file contains module data for the module '' that is not terminated by the proper module value EOF marker

**Comment by mmasouras** [comment]
I just built from head and this now looks fixed, thanks.
