### ISSUE TITLE
Search returns field content from another index

### ISSUE THREAD

**Issue by JefStat** [RedisLabsModules/RediSearch#376]
From this example you can see there are 2 indices `listener;DTOT5` and `listener;DTOT1` a document is added to each index with a different value for the text1 field. When searching the DTOT5 index the value of text1 from DTOT1 is returned 

```
127.0.0.1:6379> ft.search listener;DTOT5 @text1:(nav)
1) (integer) 0
127.0.0.1:6379> ft.add listener;DTOT5 1000 1 FIELDS text1 nav
OK
127.0.0.1:6379> ft.search listener;DTOT5 @text1:(nav)
1) (integer) 1
2) "1000"
3) 1) "text1"
   2) "nav"
127.0.0.1:6379> ft.add listener;DTOT1 1000 1 FIELDS text1 lol
OK
127.0.0.1:6379> ft.search listener;DTOT5 @text1:(nav)
1) (integer) 1
2) "1000"
3) 1) "text1"
   2) "lol"
```

**Comment by JefStat** [comment]
The problem is linked to the fact that both document have the same id. If I use unique document ids there is no issue.

**Comment by mnunberg** [comment]
This is kind of by design. You could explicitly select the fields you want to return using the RETURN  keyword.

**Comment by mnunberg** [comment]
I suppose we could add a feature to the schema (i.e. `CREATE`) which adds a document prefix. Would that help?

**Comment by JefStat** [comment]
yes that would help

**Comment by mnunberg** [comment]
On second thought- couldn't you just use that form of prefixing in your application? or prefix your fields?

**Comment by JefStat** [comment]
I prefix my ids with the index name in my application. The behaviour is unexpected and pretty subtle to catch though. At least some documentation mentioning the intended behaviour would be a good enough fix.

**Comment by mnunberg** [comment]
@itamarhaber can you add this to the docs?

**Comment by JefStat** [comment]
Great
