### ISSUE TITLE
Docker version: ERR unknown command 'ft.info' when run with command redis-server --appendonly yes

### ISSUE THREAD

**Issue by ikandars** [RedisLabsModules/RediSearch#383]
Hi,

I'm using RediSearch docker version `redislabs/redisearch:1.2.0`

First I run this command and everything works well, except the data does not persist.

```
docker run \
    -p 6379:6379 \
    -d \
    --name redisearch \
    -v redisearch-data:/data \
    redislabs/redisearch:1.2.0
```

Then run following command via `redis-cli` and the output is:

```
127.0.0.1:6379> ft.create myIndex1 SCHEMA type TEXT WEIGHT 5.0 content TEXT
OK
```

Base on official Redis image docs, I need to to add `redis-server --appendonly yes` argument to make my data persist. So I run this command:

```
docker run \
    -p 6379:6379 \
    -d \
    --name redisearch \
    -v redisearch-data:/data \
    redislabs/redisearch:1.2.0 \
    redis-server --appendonly yes
```

Then run following command via `redis-cli` and the output is:

```
ft.create myIndex2 SCHEMA type TEXT WEIGHT 5.0 content TEXT
(error) ERR unknown command 'ft.create'
```

**Comment by mnunberg** [comment]
You need to also use `—loadmodule redisearch.so` or similar:)

**Comment by ikandars** [comment]
Thx it works now. So here the complete command incase some one have same issue.

```
docker run \
    -p 6379:6379 \
    -d \
    --name redisearch \
    -v redisearch-data:/data \
    redislabs/redisearch:1.2.0 \
    redis-server --appendonly yes \
    --loadmodule /usr/lib/redis/modules/redisearch.so
```

**Comment by arikapudi95** [comment]
> Thx it works now. So here the complete command incase some one have same issue.
> 
> ```
> docker run \
>     -p 6379:6379 \
>     -d \
>     --name redisearch \
>     -v redisearch-data:/data \
>     redislabs/redisearch:1.2.0 \
>     redis-server --appendonly yes \
>     --loadmodule /usr/lib/redis/modules/redisearch.so
> ```

how are you executing this command with out any description??
can u help me with this.

**Comment by arikapudi95** [comment]
may i know how you executed this command
