### ISSUE TITLE
Opensource Vs Enterprise

### ISSUE THREAD

**Issue by nginxsantos** [RedisLabsModules/RediSearch#387]
Hi,

I have a question on the RediSearch.

Can you please clarify what is that not supported in Opensource version and only limited to the enterprise version. To me it seems that open source one only supports the standalone redis and for redis-cluster , the openesource RediSearch can't be used. Can you please clarify.

I am using Redis-cluster in my product and I am looking for the RediSearch.

Please clarify.
thanks, santos

**Comment by gkorland** [comment]
@nginxsantos Currently RediSearch OpenSource only supports non-clustered redis. Currently only the Enterprise version supports a cluster

**Comment by nginxsantos** [comment]
thanks @gkorland

**Comment by nginxsantos** [comment]
On another thought, is there any support for Bulk Update: i.e ability to update multiple records in one operation

I am sorry This is not the right forum to ask this. Please let me know where should I post this. My apologies

**Comment by gkorland** [comment]
You can always post such questions on one of the following channels:
[RediSearch Group](https://groups.google.com/forum/#!forum/redisearch)
[RediSearch Stackoverflow](https://stackoverflow.com/questions/tagged/redisearch)
