### ISSUE TITLE
Sorting issue with FT.SEARCH with empty field values

### ISSUE THREAD

**Issue by ashutoshtripathi** [RedisLabsModules/RediSearch#389]
Hi,
I am running into an issue that doesn't yield me sorted result. I am attaching sample use case below.

`FT.CREATE my1 SCHEMA title TEXT name TEXT SORTABLE` 
`FT.ADD my1 doc2 1.0 FIELDS title "hello world2" name  "a" `
`FT.ADD my1 doc3 1.0 FIELDS title "hello world3" name  "b" `
`FT.ADD my1 doc4 1.0 FIELDS title "hello world4" `
`FT.ADD my1 doc5 1.0 FIELDS title "hello world3" name  NULL`
`FT.ADD my1 doc6 1.0 FIELDS title "hello world3" name  ""`
`FT.ADD my1 doc7 1.0 FIELDS title "hello world1" name  "apple"` 
`FT.ADD my1 doc8 1.0 FIELDS title "hello world1" name  "aa"`
`FT.SEARCH my1  "*" SORTBY name ASC `

Below is the result I get from this search and is not sorted with name field. Can someone point out the issue or interim solution.
```
1) (integer) 7
 2) "doc6"
 3) 1) "title"
    2) "hello world3"
    3) "name"
    4) ""
 4) "doc2"
 5) 1) "title"
    2) "hello world2"
    3) "name"
    4) "a"
 6) "doc8"
 7) 1) "title"
    2) "hello world1"
    3) "name"
    4) "aa"
 8) "doc7"
 9) 1) "title"
    2) "hello world1"
    3) "name"
    4) "apple"
10) "doc4"
11) 1) "title"
    2) "hello world4"
12) "doc3"
1) (integer) 7
 2) "doc6"
 3) 1) "title"
    2) "hello world3"
    3) "name"
    4) ""
 4) "doc2"
 5) 1) "title"
    2) "hello world2"
    3) "name"
    4) "a"
 6) "doc8"
 7) 1) "title"
    2) "hello world1"
    3) "name"
    4) "aa"
 8) "doc7"
 9) 1) "title"
    2) "hello world1"
    3) "name"
    4) "apple"
10) "doc4"
11) 1) "title"
    2) "hello world4"
12) "doc3"
13) 1) "title"
    2) "hello world3"
    3) "name"
    4) "b"
14) "doc5"
15) 1) "title"
    2) "hello world3"
    3) "name"
    4) "NULL"
```

**Comment by salt4pommes** [comment]
Dont see any error here?

When using aggregation engine:

ft.aggregate my1 * LOAD 1 "@title" APPLY "@name" AS name SORTBY 2 "@name" ASC

The result is:
1) (integer) 7
2) 1) "title"
   2) "hello world4"
   3) "name"
   4) (nil)
3) 1) "title"
   2) "hello world3"
   3) "name"
   4) ""
4) 1) "title"
   2) "hello world2"
   3) "name"
   4) "a"
5) 1) "title"
   2) "hello world1"
   3) "name"
   4) "aa"
6) 1) "title"
   2) "hello world1"
   3) "name"
   4) "apple"
7) 1) "title"
   2) "hello world3"
   3) "name"
   4) "b"
8) 1) "title"
   2) "hello world3"
   3) "name"
   4) "null"

**Comment by mnunberg** [comment]
It appears to be using normal lexical sorting. Please reopen if you expected different results.
