### ISSUE TITLE
Corrupt aof file

### ISSUE THREAD

**Issue by JefStat** [RedisLabsModules/RediSearch#394]
We have been seeing this issue in production so far only guess is that is happens during a power outage.
Redis doesn't come back online because of corruption in the aof file. 
```
11833:M 23 Jul 07:50:58.426 * <ft> Initialized thread pool!
11833:M 23 Jul 07:50:58.426 * Module 'ft' loaded from /solink/run/redisearch.so
11833:M 23 Jul 07:50:58.426 * Reading RDB preamble from AOF file...
11833:M 23 Jul 07:50:58.426 * Reading the remaining AOF tail...
11833:M 23 Jul 07:50:59.099 # Bad file format reading the append only file: make a backup of your AOF file, then use ./redis-check-aof --fix <filename>
```
Then this is output of of check aof.
```
The AOF appears to start with an RDB preamble.
Checking the RDB preamble to start:
[offset 0] Checking RDB file appendonly.aof
[offset 26] AUX FIELD redis-ver = '4.0.9'
[offset 40] AUX FIELD redis-bits = '64'
[offset 52] AUX FIELD ctime = '1532140131'
[offset 67] AUX FIELD used-mem = '992032'
[offset 83] AUX FIELD aof-preamble = '1'
[offset 85] Selecting DB ID 0
[offset 488] Checksum OK
[offset 488] \o/ RDB looks OK! \o/
[info] 2 keys read
[info] 0 expires
[info] 0 already expired
RDB preamble is OK, proceeding with AOF tail...
0x         119fad2: Expected prefix '*', got: '
AOF analyzed: size=18480421, ok_up_to=18479826, diff=595
AOF is not valid. Use the --fix option to try fixing it.
```

Is there a way to auto accept the `--fix` param? Because for my situation I'd like to truncate and continue and accept the data loss.

**Comment by itamarhaber** [comment]
Hello @JefStat 

Is your Redis configured with `aof-load-truncated yes`?

**Comment by JefStat** [comment]
Damn my prod systems did not have `aof-load-truncated yes` setting was missed in a update.  
After changing that setting should redis start up without running `redis-check-aof --fix`?

**Comment by itamarhaber** [comment]
Yep, that's the expected behavior.

**Comment by JefStat** [comment]
Ok that's not what I'm experiencing. After enabling the `aof-load-truncated yes` redis would still not start having the same error as with the setting off. . @itamarhaber I can supply an appendonly file with the rdb preamble file (via email link) if you would like.

**Comment by mnunberg** [comment]
This doesn't really seem to have much to do with Search. In any event, the trailing bytes are just dead, not simply truncated.

```
mnunberg@mpb15iii ~/Source/RediSearch/build $ dd if=appendonly_v409.aof skip=18479826 bs=1 | od -h
595+0 records in
595+0 records out
595 bytes transferred in 0.000889 secs (669244 bytes/sec)
0000000      0000    0000    0000    0000    0000    0000    0000    0000
*
0001120      0000    0000                                                
0001123
```

**Comment by JefStat** [comment]
So is this an issue with redis' aof-load-truncated setting?

**Comment by itamarhaber** [comment]
Indeed - very weird. I suggest we move this to the redis repo - @JefStat would you open the issue there (feel free to ref this)?

**Comment by mnunberg** [comment]
Closing this issue here, as this doesn't seem related to RS, and this will get better help and visibility on the main Redis repo. If I *had* to guess, it seems that there is space allocated in the file, but it is not written to prior to power failure? though it appears it's using stdio so 🤷‍♂️

**Comment by antirez** [comment]
Hello, this usually happens with specific kernel parameters for the Linux kernel filesystem. If the mount options regarding data safety of ext4 or other filesystems are not strict enough, the metadata of the file could be updated before the file page itself is flushed on disk. This results in zero-padding of the file.

**Comment by antirez** [comment]
P.S. for your convenience here there is something from the kernel documentation:

```
data=journal		All data are committed into the journal prior to being
			written into the main file system.  Enabling
			this mode will disable delayed allocation and
			O_DIRECT support.

data=ordered	(*)	All data are forced directly out to the main file
			system prior to its metadata being committed to the
			journal.

data=writeback		Data ordering is not preserved, data may be written
			into the main file system after its metadata has been
			committed to the journal.
```
