### ISSUE TITLE
MAC OS x compilation issues

### ISSUE THREAD

**Issue by pfreixes** [RedisLabsModules/RediSearch#4]
Ive got some issues compiling RedisSearch in my MAC OS X Yosemite, first issue with the header to import all definitions regarding the `malloc.h` file and the second o one related with the `u_short` symbol definition. Next snippet displays the silly modifications made to overcome this issues.

```
diff --git a/src/rmutil/sdsalloc.h b/src/rmutil/sdsalloc.h
index 33ee741..1538fdf 100644
--- a/src/rmutil/sdsalloc.h
+++ b/src/rmutil/sdsalloc.h
@@ -36,7 +36,11 @@
  * the include of your alternate allocator if needed (not needed in order
  * to use the default libc allocator). */

+#if defined(__MACH__)
+#include <stdlib.h>
+#else
 #include <malloc.h>
+#endif
 //#include "zmalloc.h"
 #define s_malloc malloc
 #define s_realloc realloc
diff --git a/src/types.h b/src/types.h
index 13cde82..9d5be91 100644
--- a/src/types.h
+++ b/src/types.h
@@ -2,8 +2,12 @@
 #define __MDMA_TYPES_H__
 #include <stdlib.h>

+#if defined(__MACH__)
+#include <sys/types.h>
+#endif
+
 typedef u_int32_t t_docId;
 typedef u_int32_t t_offset;


-#endif
\ No newline at end of file
+#endif
```

Aside of this issue, just worth mentioning that default linker in MAC does not recognize the   `-Bsymbolic` option. To address this issue use the original gcc command rather than the default one shipped with the MAC

``` bash
$ brew install gcc48
$ export CC=/usr/local/Cellar/gcc48/4.8.4/bin/gcc-4.8
$ export LD=/usr/local/Cellar/gcc48/4.8.4/bin/gcc-4.8
$ make all
```

**Comment by dvirsky** [comment]
Thanks. I don't have a Mac handy here. Care to make this into a PR?

**Comment by dvirsky** [comment]
Hi @silasrm, I'm sorry but I don't have a Mac to test this, I'll try to get my hands on one or ask someone who has a dev environment to try and see. But if it's just warnings, I'd ignore them for now. 

Re the fatal error - this looks like you are not using the wrong redis version. Use only a cloned from `unstable` branch version, as this is a feature that has not yet been released. 

Let me know if this fixed the issue.

**Comment by silasrm** [comment]
Ok @dvirsky.
I'll try with unstable.

**Comment by mheiber** [comment]
@silasrm I got this to compile on OS X when using the `unstable` branch of Redis and tweaking the Makefile. I didn't have to use a special gcc version.

If this works for others, I'll PR it: https://github.com/mheiber/RediSearch/tree/patch-os-x-compilation.

**Comment by silasrm** [comment]
Hi @mheiber my macbook is broken but I'll save in bookmark.

Thk's
