### ISSUE TITLE
"FT.SEARCH index the" returning error

### ISSUE THREAD

**Issue by raulggonzalez** [RedisLabsModules/RediSearch#40]
When I run `FT.SEARCH ix the`, I'm receiving an error. Example:

```
127.0.0.1:6379> FT.SEARCH bands th
1) (integer) 0
127.0.0.1:6379> FT.SEARCH bands the
(error) Syntax error at offset 0 near ''
127.0.0.1:6379> FT.SEARCH bands then
(error) Syntax error at offset 0 near ''
127.0.0.1:6379> FT.SEARCH bands thenn
1) (integer) 0
127.0.0.1:6379> FT.SEARCH bands '@name:the'
(error) Syntax error at offset 5 near ':'
127.0.0.1:6379>
```

Other problematic terms: `and`, `if`, `or`...

Environment info:
- Redis: 4.0 RC2
- RediSearch: 0.12.1

**Comment by dvirsky** [comment]
Basically "the" is a stopword so it gets stripped. This is not a syntax error per se, but basically you've submitted an empty query. 

So basically we have two issues:
1. We should control the stopword list manually. This is in the TODO and a PR would be welcome.
2. The error message on an empty query should be more understandable.

**Comment by dvirsky** [comment]
Stopwords are now configurable, and empty queries do not return errors, so I'm closing this issue.
