### ISSUE TITLE
Aggregation-Query-Scoring?

### ISSUE THREAD

**Issue by salt4pommes** [RedisLabsModules/RediSearch#404]
Just a question which poped up in my head:

When searching using aggregations like for example this: FT.AGGREGATE myIdx "hello"

Which scorer will be used when no sortby is defined?

If a scorer is used, it would be cool to be able to select which scorer should be use.

Thank you!

**Comment by mnunberg** [comment]
For aggregations, no scorer is used if no SORTBY is defined. In practice it will end up being something similar to insertion order; though this depends on the specific filter query.

**Comment by salt4pommes** [comment]
Ok, thank you for clarification :)
