### ISSUE TITLE
Error searching for 

### ISSUE THREAD

**Issue by dmitrypol** [RedisLabsModules/RediSearch#41]
FT.CREATE User SCHEMA name TEXT
FT.ADD User 'bob'
FT.SEARCH User ''

RESULT
(error) Syntax error at offset 0 near ''

Sometimes UI searches pass empty strings when person clicks Search w/o specifying anthing

**Comment by dvirsky** [comment]
It's still an error... you should catch that exception in your client, or not pass it to the server at all

**Comment by dvirsky** [comment]
I mean, I might change it, but it's a matter of taste basically.

**Comment by dmitrypol** [comment]
I am catching it in my library dmitrypol/redi_search_rails but thought you might want to know

**Comment by dvirsky** [comment]
I know, but I hate to put something like:

```c
if (strlen(query) == 0) {
// ignore the syntax error in the parser
}
```

so now what if the query is `"  "`? or `"     "`? or `",. ?---- !!!? "` or `"a"` (which is a stopword)  - all of those are empty queries, I don't want to pre-process the query. I want the parser to just get it and do its best to parse it.

**Comment by dvirsky** [comment]
let's try this - I've added a rule in the grammar for empty queries. pull master and try it.
