### ISSUE TITLE
For Windows 

### ISSUE THREAD

**Issue by wjkhappy14** [RedisLabsModules/RediSearch#416]
no module for redis on windows ?

**Comment by itamarhaber** [comment]
Hello @wjkhappy14 

As far as I know, there is no official Redis for Windows, let alone one that supports modules. That being the case, there are no Redis modules for Redis on Windows.

I suggest that you run Redis on a Linux server or using [WSL on Windows](https://redislabs.com/blog/redis-on-windows-10/), and then you'll be able to use all modules without any special considerations.

P.S. the unofficial, alpha repo at https://github.com/tporadowski/redis/releases does not support modules.

**Comment by shijuabraham** [comment]
https://github.com/tporadowski/redis/releases now supports modules. Can we get redisearch module updated for windows also?

**Comment by zkteco-home** [comment]
@itamarhaber i compiled redis windows edition,it supports modules,https://github.com/zkteco-home/redis-windows
someone ask if redisearch can build windows dll,https://github.com/zkteco-home/redis-windows/issues/29
so i also want to know if i can compile windows dll.

**Comment by tobaba** [comment]
When I migrate the **dump.rdb** file generated by the unofficial, alpha repo at **https://github.com/tporadowski/redis/releases** to your project, the windows service automatically stops and fails to load. Is there a solution?

**Comment by aburakab** [comment]
Also if it's possible for other modules like [RedisJSON](https://redis.io/docs/stack/json), [RediSearch](https://redis.io/docs/stack/search), [RedisGraph](https://redis.io/docs/stack/graph), [RedisTimeSeries](https://redis.io/docs/stack/timeseries), and [RedisBloom](https://redis.io/docs/stack/bloom),

**Comment by tcrch** [comment]
Any updates to this port?
