### ISSUE TITLE
Redisearch HA - Master-Slave-Sentinel on GKE 

### ISSUE THREAD

**Issue by gabparanth** [RedisLabsModules/RediSearch#426]
Hi ! 

I would like to have a Redisearch setup in HA using GKE,
If I understand well, I should do Redisearch Master-Slave with Redis Sentinel but I struggle to let it work. 

I would like to know if it's something that can be done ? 
if yes, would you have by any chance a working manifest ? 

what I've done so far : 
1. redisearch master + slave, with replication set up on run-time : working perfectly!
2. Redis Sentinel + Master + Slave using helm ( https://hub.kubeapps.com/charts/stable/redis-ha )
-> it's working properly for redis but doesn't look to be compatible with Redisearch

Thanks so much for your help !

Gab

**Comment by mnunberg** [comment]
What happens when you try? You'd need to get it to load the redisearch.so module somehow in the first place.

**Comment by gabparanth** [comment]
Thanks for your answer, 

I just found the following repo that helped me to achieve it finally : 
https://github.com/yuzone/gke-redis-sentinel

I don't use the cluster.yaml (rs not supported in cluster mode in open-source) and add the redisearch docker image instead of redis and the alpine 4.x for the sentinel.
If I kill the master pod, master role is assigned to an existing slave, GKE redeploy a new pod with Redisearch + sentinel and replicate automatically the data to the new pod. 

I had in my previous tests issues to properly link redisearch with the sentinel, fail-over wasn't working and replication wasn't working natively. 

but it's all god now ! 
 
sorry for bothering you, 
When I finish my deployement, I will create a procedure to do it from scratch, let me know if I should post it somewhere specifically. 

thanks again. 

Gab
