### ISSUE TITLE
Query on special character doesnt seem to work 

### ISSUE THREAD

**Issue by dragnot** [RedisLabsModules/RediSearch#44]
it seem that the query gets broken on special character instead of treating it as a string 

example 
127.0.0.1:6379> "FT.SEARCH" "idxvisa" "@BusinessName:\"Wells Fargo Bank, National Association\"" "VERBATIM"
(error) Syntax error at offset 27 near 'Bank'
works without comma
127.0.0.1:6379> "FT.SEARCH" "idxvisa" "@BusinessName:\"Wells Fargo Bank National Association\"" "VERBATIM"
 1) (integer) 5
 2) "decc7c4f-45ab-46c1-a1f6-62dd9277ccc4"
 3)  1) "LastModified"
     2) "37527.108076"
     3) "BusinessName"
     4) "Wells Fargo Bank, National Association"
     5) "Classification"
     6) "Processor"
     7) "ClientCountry"
     8) "UNITED STATES OF AMERICA"
     9) "BusinessID"
    10) "10000056"

**Comment by dvirsky** [comment]
Thanks for catching. Fixed in master.
