### ISSUE TITLE
FT.EXPLAIN reply is a single raw instead of multi raw

### ISSUE THREAD

**Issue by MeirShpilraien** [RedisLabsModules/RediSearch#445]
Provide an FT.EXPLAIN variant that displays nicely

From @stockholmux 

"FT.EXPLAIN with proper line breaks
In the course, I extensively use FT.EXPLAIN as a method of conveying the meaning of a query. In the current form, it uses a string output but it contains new lines, which doesn't play nicely with redis-cli and is unreadable.

```
127.0.0.1:6379> ft.explain permits "deck|patio"
"UNION {\n  UNION {\n    deck\n    <TK(expanded)\n    +deck(expanded)\n  }\n  UNION {\n    patio\n    <PT(expanded)\n    +patio(expanded)\n  }\n}\n"
```

I would suggest showing each line as a result in a multi-bulk response (it could be an optional argument to FT.EXPLAIN, perhaps MULTILINE)"

See also #361

**Comment by MeirShpilraien** [comment]
The issue is that the redis-cli is perform escaping on the result by default.
It is possible to run the redis-cli with --raw flag and then the result will be fine but all the other results will not looks good (they will not contains bulk number for example).

There is no way to tell the redis-cli to perform escaping on some commands and on other not.

We can remove the '\n' entirely and remain with a single line result

Regarding the other suggested option:
```
127.0.0.1:6379> ft.explain permits "deck|patio"MULTLINE
 1) "UNION {"
 2) " UNION {"
 3) "   deck"
 4) "    <TK(expanded)"
 5) "    +deck(expanded)"
 6) "  }"
 7) "  UNION {"
 8) "    patio"
 9) "    <PT(expanded)"
10) "   +patio(expanded)"
11) "  }"
12) "}"
```
I do not like it because if you use it with the python client you will get an array like this:
[ "UNION {", " UNION {", "   deck","    <TK(expanded)" ...  ]

@mnunberg, @stockholmux , @itamarhaber 
Any thoughts?

**Comment by mnunberg** [comment]
This was already addressed previously. In the future it might be good to provide JSON output (not some kind of random format), but we would need to incorporate a JSON encoder. Another option would be to provide a specialized cli client for RS.

**Comment by stockholmux** [comment]
@MeirShpilraien Yeah - this makes little sense in a programmatic use, but neither does FT.EXPLAIN generally, it is (largely) a debugging command to be executed from redis-cli. Notice the argument `MULTILINE` - this should only be rendered this way when requested, `FT.EXPLAIN` would continute outputting pure strings with lines breaks. This is proposed to be optional.

More Background/Context:
It's been my experience that RediSearch developers stumble with the query language. Many query problems could easily be solved by running FT.EXPLAIN, as it clearly outlines what is happening, but FT.EXPLAIN is  developer hostile in it's current form. To get developers to actually read the docs and swap back and forth between redis-cli with and without the `--raw` flag is not a battle we will win.

**Comment by stockholmux** [comment]
@mnunberg JSON output doesn't address the readability in redis-cli problem, which is the reason for this request.

**Comment by mnunberg** [comment]
the only way we are going to get readability in redis-cli is if redis-cli itself changes. If we just want something short-term, we can output arrays, though I don't know if doing so is at all trivial.

**Comment by stockholmux** [comment]
@mnunberg I wouldn't hold my breath on redis-cli changing anytime soon. The next opportunity will be with the proposed protocol changes, IMHO. That's 12-18 months away, even then the rest of the community may disagree for unanticipated reasons.

As far as complexity, could you take the current string output then split by "\n" (`strtok`)? I'm sure it's more than that, but that was the general idea I had in mind.

**Comment by stockholmux** [comment]
@mnunberg Yeah, as an argument switch on `FT.EXPLAIN` is what I was looking for, but yours work too. I don't want to cause changes to tests and things which rely on the raw output of `FT.EXPLAIN`

**Comment by MeirShpilraien** [comment]
@stockholmux on our fork the redis-cli knows not to perform escaping on commands which were added with a specific flag, the question is whether or not it reasonable to use our redis-cli fork in your course?

**Comment by mnunberg** [comment]
As we move towards a unified command for aggregate and search, I think a keyword works for both. Something like

FT.<MAGIC_COMMAND> query … EXPLAIN [FORMATTED|ASARRAY]

or maybe just EXPLAINARRAY and EXPLAIN

Anyway, the entrypoint doesn’t matter as much as the ability to get the results you need
