### ISSUE TITLE
No error checking on arguments LIMIT

### ISSUE THREAD

**Issue by stockholmux** [RedisLabsModules/RediSearch#464]
Not sure if this is a _feature_ or a _bug_.

RediSearch seems to do very limited checking of arguments allowing for some potentially unexpected results when accepting user input.

Take, for example, pagination where the end user can pass in directly the offset and count to LIMIT.

`FT.SEARCH myidx "some query" LIMIT {offset from URL} {count from URL}`

Imagine the URL is something like `http://myawesome.com/?offset={offset}&perpage={count}`.

Now, it's obviously bad practice to do no validation of user input at all, but one could pass in something like this:

`http://myawesome.com/?offset=SUMMARIZE&perpage=somefield`.

Resulting in 

`FT.SEARCH myidx "some query" LIMIT SUMMARIZE somefield`

RediSearch will gladly execute this command, ignoring the `LIMIT` instead of erring out as you might expect if `LIMIT` gets non-numeric arguments.  

I haven't tested every argument for every command but I'm not sure this is limited (uhh) to limit.

**Comment by mnunberg** [comment]
This should be fixed in master :)

**Comment by stockholmux** [comment]
Ahh! I did that test before pulling a fresh copy this morning. Seems like it's fixed. Feel free to close or leave open for FT.AGGREGATE
