### ISSUE TITLE
Query using field modifiers returning syntax error if the field name contains '_'

### ISSUE THREAD

**Issue by vruizext** [RedisLabsModules/RediSearch#51]
`FT.SEARCH idx @brand:(ford) @model:(mustang gt)` => works

If now I index brand and model in a single field and name it `brand_model`

`FT.SEARCH idx @brand_model:(ford mustang)` => `(error) Syntax error at offset 0 near 'brand'`

RediSearch 0.16 with  Redis 3.9.103

**Comment by dvirsky** [comment]
Thanks @vruizext. It's fixed now in master, you can pull it and verify.

**Comment by vruizext** [comment]
wow that was fast! will pull it and test, thanks! 👍

**Comment by vruizext** [comment]
confirmed, it works
