### ISSUE TITLE
How to install RediSearch in production

### ISSUE THREAD

**Issue by mahemoff** [RedisLabsModules/RediSearch#513]
Hi, I'm hoping to install RediSearch in production - Ubuntu 16.04 - what's the recommended installation procedure? I'm not familiar with the Redis modules model, but thought there might be a way to get a plugin distribution similar to Apache http server's dynamic modules. 

Options I've looked at:

* Docker - This is the main option in the README, but I'd rather avoid the overhead and keep things simple as it will be a dedicated VPS.
* Compile from source - I had some cmake issues following the README. It's probably possible, but looking for a simpler distribution model if available.
* Package. An unofficial Debian package is [referenced here](https://groups.google.com/forum/#!topic/redisearch/0UrMRJUNSEc), but appears to have been removed.

**Comment by mnunberg** [comment]
Compiling from source would be the preferred way to run it in production (IMO), but Docker would be the preferred way to play around with it, in the environment. Either way, it's a single shared library object, so deployment is really simple.

**Comment by MeirShpilraien** [comment]
@mahemoff what issue did you experienced with cmak?

**Comment by mahemoff** [comment]
Thanks. I'll make a separate issue on cmake then.

**Comment by mahemoff** [comment]
Actually it worked with cmake when I extracted the tarball to a fresh folder. For the record, I was getting this error prior to that, not sure why but it's solved now.

> CMake Error: The source directory                                                            
>   "/home/build/RediSearch-1.4.0-rc3/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx"                                                                                  
>   is a file, not a directory.

I also ran into the issue reported in #4 "Bad directive or wrong number of arguments" until I downloaded and compiled the beta (5.0rc6). I think the docs could indicate minimum compatible redis-server version.

**Comment by mnunberg** [comment]
For the CMake issue, I've never seen that before. Maybe it's something we're doing in our project files? If you are using Mac, make sure you have software that's reasonably up to date (i.e. within the past year or so).

**Comment by mahemoff** [comment]
It was on Ubuntu 16.04. I installed cmake as part of this via apt-get and I recall running getting the error about having to set the cmake environment variable. Maybe the initial build before the env variable was set put the directory into an odd state? (I didn't look into it much tbh as I wanted to check first if it's the recommended approach for install.)
