### ISSUE TITLE
Search with prefix return unexpected result

### ISSUE THREAD

**Issue by aburakovskiy** [RedisLabsModules/RediSearch#533]
My index
<img width="293" alt="2018-11-08_1347" src="https://user-images.githubusercontent.com/1153385/48197021-f4e5d700-e35c-11e8-86bb-89908de0c8e4.png">

I try to do search with prefix in this way:
`FT.SEARCH locations '@name_normalized:(san francisco*)' `
according to the documentation this should be similar to sql query 
`name_normalized LIKE 'san francisco%'`
and expect that in the result will be all records which begin from 'san francisco' but now I also get records which have some words before this phrase, e.g. 'south san francisco'
<img width="290" alt="2018-11-08_1344" src="https://user-images.githubusercontent.com/1153385/48196842-6bcea000-e35c-11e8-9e48-60dada08cc57.png">
Is it possible to exclude these records from result?

**Comment by itamarhaber** [comment]
Hello @aburakovskiy 

TEXT fields undergo automatic tokenization, rendering their contents into search terms. The query, therefore, returns all results with both 'san' and 'francisco''s prefices.

Instead, use a TAG field (whose default separator is ',') for the effect that you're looking for. Makes sense?

**Comment by aburakovskiy** [comment]
Thank you @itamarhaber I tried to use TAGs but there is a disadvantage - the matching prefix is not allowed. Therefore, if I have two locations: 'New York' and 'New York City' and I do a search "@field:{ New York }" I'll get an exact match and in the response will be only the first location. So to use prefix with text fields is more preferable.

**Comment by MeirShpilraien** [comment]
@aburakovskiy prefix search on TAGS is totally possible:
```
127.0.0.1:6379> FT.CREATE idx SCHEMA test TAG SORTABLE
OK
127.0.0.1:6379> FT.ADD idx doc1 1.0 FIELDS test "this is a test"
OK
127.0.0.1:6379> FT.ADD idx doc2 1.0 FIELDS test "this is another test"
OK
127.0.0.1:6379> ft.search idx "@test:{this\\ is*}"
1) (integer) 2
2) "doc2"
3) 1) "test"
   2) "this is another test"
4) "doc1"
5) 1) "test"
   2) "this is a test"
```

**Comment by aburakovskiy** [comment]
Thanks guys, I forgot about escaping, now it works well
