### ISSUE TITLE
Add support for Timedate

### ISSUE THREAD

**Issue by gkorland** [RedisLabsModules/RediSearch#558]

**Comment by mnunberg** [comment]
How would this function differently than a normal number?

**Comment by gkorland** [comment]
1. Should be able to use 
```
 BETWEEN ["1984-02-16", "1985-02-17"]
```

**Comment by jameycai** [comment]
I usually convert time to 13-bit milliseconds,   I want to add long-type numerical queries.

**Comment by jameycai** [comment]
I usually convert the time to 13-bit milliseconds. I hope you can add long-types numerical queries.

**Comment by jameycai** [comment]
I usually convert time to 13 bit milliseconds, I hope you can add long numeric queries,  thank you!

**Comment by dvirsky** [comment]
This should be done from the client libraries and not internally.

**Comment by gkorland** [comment]
@dvirsky but the server doesn't support 64bit integers, so how can we make from the clients side?

**Comment by jameycai** [comment]
@gkorland   In the next release, is this feature added?

**Comment by jameycai** [comment]
@gkorland @mnunberg @dvirsky    In the next release, is this feature added?

**Comment by jameycai** [comment]
@gkorland @mnunberg @dvirsky     Add support for 64-bit long integers. Can you add this feature in the next version?

**Comment by mnunberg** [comment]
Closing this in favor of #557
