### ISSUE TITLE
Error at compile time

### ISSUE THREAD

**Issue by yisi-liu** [RedisLabsModules/RediSearch#563]
```
make[3]: Leaving directory `/home/d/www/redis/RediSearch/build-compat'
make[3]: Entering directory `/home/d/www/redis/RediSearch/build-compat'
[ 17%] Building C object CMakeFiles/rscore.dir/src/aggregate/aggregate_exec.c.o
In file included from /home/d/www/redis/RediSearch/src/sortable.h:4,
                 from /home/d/www/redis/RediSearch/src/doc_table.h:8,
                 from /home/d/www/redis/RediSearch/src/spec.h:8,
                 from /home/d/www/redis/RediSearch/src/search_ctx.h:7,
                 from /home/d/www/redis/RediSearch/src/aggregate/aggregate_exec.c:3:
/home/d/www/redis/RediSearch/src/value.h: In function ‘RSValue_MakeReference’:
/home/d/www/redis/RediSearch/src/value.h:104: error: unknown field ‘ref’ specified in initializer
/home/d/www/redis/RediSearch/src/value.h:104: warning: excess elements in struct initializer
/home/d/www/redis/RediSearch/src/value.h:104: warning: (near initialization for ‘(anonymous)’)
At top level:
cc1: warning: unrecognized command line option "-Wno-unused-result"
make[3]: *** [CMakeFiles/rscore.dir/src/aggregate/aggregate_exec.c.o] Error 1
make[3]: Leaving directory `/home/d/www/redis/RediSearch/build-compat'
make[2]: *** [CMakeFiles/rscore.dir/all] Error 2
make[2]: Leaving directory `/home/d/www/redis/RediSearch/build-compat'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/d/www/redis/RediSearch/build-compat'
make: *** [build-compat/redisearch.so] Error 2
```

**Comment by mnunberg** [comment]
What version of gcc/OS is this? 

It would appear that it does not support anonymous unions.

**Comment by yisi-liu** [comment]
> 这是什么版本的gcc / OS？
> 
> 它似乎不支持匿名工会。

gcc 4.x, os is centos7

**Comment by yisi-liu** [comment]
> 这是什么版本的gcc / OS？
> 
> 它似乎不支持匿名工会。

gcc 4.x, os is centos7

**Comment by yisi-liu** [comment]
> 这是什么版本的gcc / OS？
> 
> 它似乎不支持匿名工会。

Trying to upgrade gcc to 8.x

**Comment by yisi-liu** [comment]
> What version of gcc/OS is this?
> 
> It would appear that it does not support anonymous unions.

The previous problem was solved, but a new problem

Scanning dependencies of target redisearchS
[ 75%] Linking C static library libredisearchS.a
[ 75%] Built target redisearchS
Scanning dependencies of target test_vector
[ 75%] Building C object src/rmutil/CMakeFiles/test_vector.dir/test_vector.c.o
[ 76%] Linking C executable test_vector
CMakeFiles/rmutil.dir/periodic.c.o: In function `rmutilTimer_Loop':
periodic.c:(.text+0x36): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
make[2]: *** [src/rmutil/test_vector] Error 1
make[1]: *** [src/rmutil/CMakeFiles/test_vector.dir/all] Error 2
make: *** [all] Error 2
[root@l-dev6.ops.bj0.daling.com build]#

**Comment by mnunberg** [comment]
Are you sure this is standard Centos7? I’ve just built it on Centos 7 without any issue. You might try adding -lrt in ldflags, but you might run into other issues.

**Comment by yisi-liu** [comment]
> Are you sure this is standard Centos7? I’ve just built it on Centos 7 without any issue. You might try adding -lrt in ldflags, but you might run into other issues.
> […](#)

I tried it, but I didn't find it. How can I add the -lrt method? Can you give an example? Thank you very much.

**Comment by mnunberg** [comment]
Try something like (at https://github.com/RedisLabsModules/RediSearch/blob/master/CMakeLists.txt#L89)
```
TARGET_LINK_LIBRARIES(redisearch rt)
```

then rebuild.

**Comment by yisi-liu** [comment]
> 尝试类似的东西（在https://github.com/RedisLabsModules/RediSearch/blob/master/CMakeLists.txt#L89）
> 
> ```
> TARGET_LINK_LIBRARIES(redisearch rt)
> ```
> 然后重建。
qqq

> Try something like (at https://github.com/RedisLabsModules/RediSearch/blob/master/CMakeLists.txt#L89)
> 
> ```
> TARGET_LINK_LIBRARIES(redisearch rt)
> ```
> then rebuild.

qqq

**Comment by yisi-liu** [comment]
> Try something like (at https://github.com/RedisLabsModules/RediSearch/blob/master/CMakeLists.txt#L89)
> 
> ```
> TARGET_LINK_LIBRARIES(redisearch rt)
> ```
> then rebuild.

I tried to modify the location, is it correct?

I tried to modify the location, is it correct, and set it at the same time，
OPTION(RS_RUN_TESTS "Build & Run RediSearch's tests" OFF)


ADD_LIBRARY(redisearchS STATIC ${FINAL_OBJECTS})
ADD_LIBRARY(redisearch SHARED ${FINAL_OBJECTS} src/module-init/module-init.c)

SET_TARGET_PROPERTIES(redisearch PROPERTIES PREFIX "")
SET_TARGET_PROPERTIES(redisearch PROPERTIES SUFFIX ".so")
TARGET_LINK_LIBRARIES(redisearchS -lm -lc -ldl -lrt)

IF (RS_RUN_TESTS)
    ADD_SUBDIRECTORY(src/tests)
    ADD_SUBDIRECTORY(src/pytest)
ENDIF()

**Comment by yisi-liu** [comment]
> > Try something like (at https://github.com/RedisLabsModules/RediSearch/blob/master/CMakeLists.txt#L89)
> > ```
> > TARGET_LINK_LIBRARIES(redisearch rt)
> > ```
> > then rebuild.
> 
> I tried to modify the location, is it correct?
> 
> I tried to modify the location, is it correct, and set it at the same time，
> OPTION(RS_RUN_TESTS "Build & Run RediSearch's tests" OFF)
> 
> ADD_LIBRARY(redisearchS STATIC ${FINAL_OBJECTS})
> ADD_LIBRARY(redisearch SHARED ${FINAL_OBJECTS} src/module-init/module-init.c)
> 
> SET_TARGET_PROPERTIES(redisearch PROPERTIES PREFIX "")
> SET_TARGET_PROPERTIES(redisearch PROPERTIES SUFFIX ".so")
> TARGET_LINK_LIBRARIES(redisearchS -lm -lc -ldl -lrt)
> 
> IF (RS_RUN_TESTS)
> ADD_SUBDIRECTORY(src/tests)
> ADD_SUBDIRECTORY(src/pytest)
> ENDIF()

Still reporting an error

[ 93%] Built target redisearchS
make[3]: Entering directory `/home/d/www/redis/RediSearch-master/build-compat'
Scanning dependencies of target test_vector
make[3]: Leaving directory `/home/d/www/redis/RediSearch-master/build-compat'
make[3]: Entering directory `/home/d/www/redis/RediSearch-master/build-compat'
[ 94%] Building C object src/rmutil/CMakeFiles/test_vector.dir/test_vector.c.o
[ 95%] Linking C executable test_vector
CMakeFiles/rmutil.dir/periodic.c.o: In function `rmutilTimer_Loop':
periodic.c:(.text+0x36): undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
make[3]: *** [src/rmutil/test_vector] Error 1
make[3]: Leaving directory `/home/d/www/redis/RediSearch-master/build-compat'
make[2]: *** [src/rmutil/CMakeFiles/test_vector.dir/all] Error 2
make[2]: Leaving directory `/home/d/www/redis/RediSearch-master/build-compat'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/d/www/redis/RediSearch-master/build-compat'
make: *** [build-compat/redisearch.so] Error 2

**Comment by mnunberg** [comment]
can you show the *full* output of the build? i.e. clean, then re-run cmake and make

**Comment by mnunberg** [comment]
So it appears that the actual .so file exists, but some of the tests aren’t building. You are safe to use the module as is, and ignore the error

**Comment by mnunberg** [comment]
The module itself should be in build-compat/redisearch.so

I plan to make building the tests optional (and off by default) in future releases

**Comment by yisi-liu** [comment]
> The module itself should be in build-compat/redisearch.so I plan to make building the tests optional (and off by default) in future releases
> […](#)

Very looking forward to

**Comment by yisi-liu** [comment]
> So it appears that the actual .so file exists, but some of the tests aren’t building. You are safe to use the module as is, and ignore the error
> […](#)

 I tried it and there will be an error. undefined symbol: clock_gettime

**Comment by yisi-liu** [comment]
> > So it appears that the actual .so file exists, but some of the tests aren’t building. You are safe to use the module as is, and ignore the error
> > […](#)
> 
> I tried it and there will be an error. undefined symbol: clock_gettime

The parameter does not take effect  -lrt

**Comment by yisi-liu** [comment]
> Are you using some kind of reproducible environment?

Sorry, I don’t understand what you mean, :)

**Comment by mnunberg** [comment]
I mean, can you give me a set of instructions which would give me the same kind of distribution that you’re using? Maybe a docker image?

**Comment by mnunberg** [comment]
Ahhh, ok. I will try to run it on Centos6 and see what I find.

**Comment by mnunberg** [comment]
Unfortunately we do not support anything under Centos6. In this case it appears to be a simple linking error, so poking around and including the correct libaries should resolve this; however, no further promises can be made. As I understand it, the `.so` is built, so that's probably as good as it's going to get.

PS: The master branch of RediSearch does not require tests be built by default, so you might not encounter this anymore.

**Comment by yisi-liu** [comment]
> Unfortunately we do not support anything under Centos6. In this case it appears to be a simple linking error, so poking around and including the correct libaries should resolve this; however, no further promises can be made. As I understand it, the `.so` is built, so that's probably as good as it's going to get.
> 
> PS: The master branch of RediSearch does not require tests be built by default, so you might not encounter this anymore.

Ok, thank you for your patience. I installed and run it on centos7. Next, I will conduct a Chinese word segmentation test. I may also ask you new questions. Thank you.

**Comment by R-tesh** [comment]
updating the below line with -lrt in CMakeLists.txt fixes it:

SET(CMAKE_C_FLAGS "-lrt ${CMAKE_C_FLAGS} ${RS_C_FLAGS}")
