### ISSUE TITLE
How to remove all suggestions

### ISSUE THREAD

**Issue by janakaonline** [RedisLabsModules/RediSearch#564]
Hi, Love this project, made my life much easier. Thanks for that.

I have this problem, so when you add a suggestion entry, yes, you can remove a single entry by calling SUGDEL. But what if we want to clear the entire suggestion index? Any advice?

Thanks

**Comment by MeirShpilraien** [comment]
@janakaonline suggestions are saved inside a given key, so you can use 'del <key-name>' to delete the entire key.

**Comment by janakaonline** [comment]
Awesome, Thanks, This solved the issue.
