### ISSUE TITLE
aof not working with the configuration

### ISSUE THREAD

**Issue by unisqu** [RedisLabsModules/RediSearch#570]
my /etc/redis.conf is here
https://pastebin.com/6tBiH5z0

do i have to always do bgsave all the time to save to db? no idea why aof is not working. how else can i save it to db all the time because data is lost when restart.

**Comment by mnunberg** [comment]
You need to pass redis config path as the first argument to redis, e.g.

redis-server /etc/redis.conf —loadmodule ….

**Comment by unisqu** [comment]
ok thx.
