### ISSUE TITLE
New Ruby client library for RediSearch

### ISSUE THREAD

**Issue by vruizext** [RedisLabsModules/RediSearch#59]
So far the only Ruby gem to work with RediSearch is Rails only. I'm working on a project with Sinatra, so I had to build my own client, and now I've open sourced it. It is framework agnostic, the only dependence is the _official_ Ruby client for Redis 4 RC1. It would be great if you could help to spread the word adding it to the README. Thanks!

https://github.com/vruizext/redisearch-rb
https://rubygems.org/gems/redisearch-rb/versions/0.1.3

**Comment by dvirsky** [comment]
Thanks.

Could you make a PR to README.md?
