### ISSUE TITLE
Don't return `foo: nil` if `foo` is not in document

### ISSUE THREAD

**Issue by mnunberg** [RedisLabsModules/RediSearch#598]
This wastes network resources.

This also has the unfortunate consequence where, if any document has `foo`, then that field will be returned as null for all subsequent documents.

**Comment by mnunberg** [comment]
@mmasouras Can you try out the associated PR? does that resolve (as in, not trigger) the issue?

**Comment by mnunberg** [comment]
Merged; fixed.

**Comment by mmasouras** [comment]
I confirm this is fixed - thanks.
