### ISSUE TITLE
Incorrect search results with large numbers

### ISSUE THREAD

**Issue by dme-development** [RedisLabsModules/RediSearch#610]
I am not getting the desired search results when searching on large numbers. I convert dates to their epoch values and search then as numeric ranges. You can see in this example that the search is returning inconsistent data:

0.0.0.0:6379> FT.SEARCH idxCachedAuctionItem "@AuctionBatchId:[116288 116288]" RETURN 3 "AuctionBatchId" "BatchStartDate" "BatchEndDate"
1) (integer) 1
2) "CAI:3188790"
3) 1) "AuctionBatchId"
   2) "116288"
   3) "BatchStartDate"
   4) "1549537200"
   5) "BatchEndDate"
   6) "1550487300"
0.0.0.0:6379> "FT.SEARCH" "idxCachedAuctionItem" "@BatchStartDate:[0 1550486661] @BatchEndDate:[1550486661 +inf] @AuctionBatchId:[116288 116288]"
1) (integer) 0

**Comment by mnunberg** [comment]
1) Is it possible to share the rdb that produces this data?
2) If you change the order of the search criteria, do the results change?

**Comment by dme-development** [comment]
Hi Mark, I've dropped you an email with the dump. Changing the order of the search criteria doesn't affect the result.

**Comment by dme-development** [comment]
Closing this issue, as it was seen on 1.3.0 and not reproducible on the latest verion.
