### ISSUE TITLE
Redis crashes unexpecteldy 

### ISSUE THREAD

**Issue by manishtoons** [RedisLabsModules/RediSearch#617]
I'm using RediSearch 1.2.0 and redis-server 4.0.10 in production without any hiccup for almost 6 months now, keyspaces scalling upto 200k to 7.4million without any worry, this crash which I'm reporting is actually new to me, which is caused by RediSearch, though upon redis-server start I didnt find any issue. As RediSearch which im using is not the latest one, I'm reporting this issue to keep you guys posted on this unexpected behaviour.

Thanks for such a awesom product and amazing support!

=== REDIS BUG REPORT START: Cut & paste starting from here ===
2130:S 22 Feb 15:17:48.748 # Redis 4.0.10 crashed by signal: 11
2130:S 22 Feb 15:17:48.768 # Crashed running the instruction at: 0x4c9145
2130:S 22 Feb 15:17:48.795 # Accessing address: 0x7617d0
2130:S 22 Feb 15:17:48.815 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/usr/local/bin/redis-server 10.100.2.36:6379[0x4c9145]

Backtrace:
/usr/local/bin/redis-server 10.100.2.36:6379(logStackTrace+0x29)[0x468859]
/usr/local/bin/redis-server 10.100.2.36:6379(sigsegvHandler+0xac)[0x468efc]
/lib64/libpthread.so.0(+0xf5e0)[0x7f58306105e0]
/usr/local/bin/redis-server 10.100.2.36:6379[0x4c9145]
/usr/local/bin/redis-server 10.100.2.36:6379(je_tcache_bin_flush_small+0x443)[0x4ead43]
/usr/local/bin/redis-server 10.100.2.36:6379(je_free+0x1d3)[0x4bf163]
/etc/redis/modules/redisearch.so(indexBlock_Free+0xd)[0x7f5827c755ed]
/etc/redis/modules/redisearch.so(InvertedIndex_Free+0x2e)[0x7f5827c7562e]
/usr/local/bin/redis-server 10.100.2.36:6379(freeModuleObject+0xf)[0x43d53f]
/usr/local/bin/redis-server 10.100.2.36:6379(decrRefCount+0x5d)[0x43d5cd]
/usr/local/bin/redis-server 10.100.2.36:6379(_dictClear+0x84)[0x428784]
/usr/local/bin/redis-server 10.100.2.36:6379(dictEmpty+0x18)[0x429168]
/usr/local/bin/redis-server 10.100.2.36:6379(emptyDb+0xa7)[0x4421a7]
/usr/local/bin/redis-server 10.100.2.36:6379(readSyncBulkPayload+0x1fa)[0x4439ba]
/usr/local/bin/redis-server 10.100.2.36:6379(aeProcessEvents+0x2a0)[0x426820]
/usr/local/bin/redis-server 10.100.2.36:6379(aeMain+0x2b)[0x426aeb]
/usr/local/bin/redis-server 10.100.2.36:6379(main+0x49f)[0x4238ef]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f583025fc05]
/usr/local/bin/redis-server 10.100.2.36:6379[0x423be2]

------ INFO OUTPUT ------
# Server
redis_version:4.0.10
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:4b188ce7e20184c8
redis_mode:standalone
os:Linux 3.10.0-514.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.8.5
process_id:2130
run_id:0494589ed53802e6efa4d76b0df2e3a6edd8cdb4
tcp_port:6379
uptime_in_seconds:1892617
uptime_in_days:21
hz:10
lru_clock:7324923
executable:/usr/local/bin/redis-server
config_file:/etc/redis/6379.conf

# Clients
connected_clients:8
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:1137820264
used_memory_human:1.06G
used_memory_rss:62070996992
used_memory_rss_human:57.81G
used_memory_peak:90894917544
used_memory_peak_human:84.65G
used_memory_peak_perc:1.25%
used_memory_overhead:2248388
used_memory_startup:786968
used_memory_dataset:1135571876
used_memory_dataset_perc:99.87%
total_system_memory:101034352640
total_system_memory_human:94.10G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:33000000000
maxmemory_human:30.73G
maxmemory_policy:volatile-lru
mem_fragmentation_ratio:54.55
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1550821741
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:287
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:10557906944
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:6223
total_commands_processed:624726169
instantaneous_ops_per_sec:5
total_net_input_bytes:223065867688
total_net_output_bytes:21236901024
instantaneous_input_kbps:73287.79
instantaneous_output_kbps:8.17
rejected_connections:0
sync_full:1
sync_partial_ok:3
sync_partial_err:1
expired_keys:56
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:3751690
keyspace_hits:8649772699
keyspace_misses:2059635
pubsub_channels:15
pubsub_patterns:0
latest_fork_usec:1735434
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:slave
master_host:10.100.2.35
master_port:6379
master_link_status:down
master_last_io_seconds_ago:-1
master_sync_in_progress:1
slave_repl_offset:1
master_sync_left_bytes:0
master_sync_last_io_seconds_ago:0
master_link_down_since_seconds:1550828795
slave_priority:50
slave_read_only:1
connected_slaves:0
master_replid:de131db51b1653d85683c89ef1e90076292b495a
master_replid2:dd58769242e5af8c6e7d513e0c31f00f7faa138f
master_repl_offset:142841960561
second_repl_offset:142784891532
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:142840911986
repl_backlog_histlen:1048576

# CPU
used_cpu_sys:89639.62
used_cpu_user:524729.06
used_cpu_sys_children:189085.91
used_cpu_user_children:1244205.75

# Commandstats
cmdstat_rpush:calls=1856,usec=35012,usec_per_call=18.86
cmdstat_set:calls=2,usec=48,usec_per_call=24.00
cmdstat_psync:calls=4,usec=1897094,usec_per_call=474273.50
cmdstat_exec:calls=170887142,usec=19150351125,usec_per_call=112.06
cmdstat_sort:calls=9920,usec=295257,usec_per_call=29.76
cmdstat_replconf:calls=2716,usec=6197,usec_per_call=2.28
cmdstat_setex:calls=1315,usec=20714,usec_per_call=15.75
cmdstat_FT.SEARCH:calls=206,usec=4826609,usec_per_call=23430.14
cmdstat_monitor:calls=7,usec=12,usec_per_call=1.71
cmdstat_subscribe:calls=179,usec=808,usec_per_call=4.51
cmdstat_select:calls=10791453,usec=9819757,usec_per_call=0.91
cmdstat_rpop:calls=828845,usec=18669173,usec_per_call=22.52
cmdstat_command:calls=8,usec=12144,usec_per_call=1518.00
cmdstat_sadd:calls=10134,usec=155815,usec_per_call=15.38
cmdstat_sync:calls=1,usec=2,usec_per_call=2.00
cmdstat_client:calls=404,usec=1487,usec_per_call=3.68
cmdstat_publish:calls=11272208,usec=57555565,usec_per_call=5.11
cmdstat_srem:calls=494,usec=3785,usec_per_call=7.66
cmdstat_del:calls=17510456,usec=87233951,usec_per_call=4.98
cmdstat_keys:calls=2,usec=23,usec_per_call=11.50
cmdstat_lpush:calls=851641,usec=29294108,usec_per_call=34.40
cmdstat_expire:calls=355486225,usec=1321647960,usec_per_call=3.72
cmdstat_exists:calls=834,usec=2829,usec_per_call=3.39
cmdstat_setnx:calls=55628,usec=343057,usec_per_call=6.17
cmdstat_FT.DEL:calls=24530,usec=267528,usec_per_call=10.91
cmdstat_type:calls=8,usec=253,usec_per_call=31.62
cmdstat_info:calls=773899,usec=119142943,usec_per_call=153.95
cmdstat_config:calls=22,usec=25510379,usec_per_call=1159562.75
cmdstat_ping:calls=5503430,usec=9101430,usec_per_call=1.65
cmdstat_slaveof:calls=1,usec=670,usec_per_call=670.00
cmdstat_multi:calls=50712599,usec=13237975,usec_per_call=0.26

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=19234,expires=0,avg_ttl=0
db10:keys=1,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=1067196880 addr=10.100.2.34:55477 fd=11 name=sentinel-a1fab4c2-cmd age=7833 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=ping
id=1066902662 addr=10.100.17.119:46528 fd=220 name= age=8702 idle=1497 flags=N db=11 sub=14 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=1067219386 addr=10.100.2.20:40481 fd=14 name= age=7781 idle=11 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=info
id=1067192515 addr=10.100.2.35:48484 fd=8 name=sentinel-dba25e9f-pubsub age=7845 idle=0 flags=N db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=1067192518 addr=10.100.2.34:60775 fd=15 name=sentinel-a1fab4c2-pubsub age=7845 idle=0 flags=N db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=1067192519 addr=10.100.2.36:47176 fd=376 name=sentinel-f6d94928-cmd age=7845 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=publish
id=1067192520 addr=10.100.2.36:32782 fd=378 name=sentinel-f6d94928-pubsub age=7845 idle=0 flags=N db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=subscribe
id=1067196879 addr=10.100.2.35:46623 fd=10 name=sentinel-dba25e9f-cmd age=7833 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=ping

------ REGISTERS ------
2130:S 22 Feb 15:17:49.326 # 
RAX:00007f55d2601a20 RBX:00007f56ffd013b0
RCX:00000000ffffffff RDX:00007f55d262e300
RDI:000000000075be80 RSI:00000000007617c0
RBP:00007f55d2601a20 RSP:00007ffd28bffbd0
R8 :000000000000000d R9 :0000000000001000
R10:00007f55d2600000 R11:00007f55d2600000
R12:00007f55d2600000 R13:00007f55d2601a30
R14:00000000000000ff R15:00007f56ffd00080
RIP:00000000004c9145 EFL:0000000000010206
CSGSFS:0000000000000033
2130:S 22 Feb 15:17:49.345 # (00007ffd28bffbdf) -> 00000020ffd11601
2130:S 22 Feb 15:17:49.363 # (00007ffd28bffbde) -> 00007f5830000180
2130:S 22 Feb 15:17:49.379 # (00007ffd28bffbdd) -> 00000000004ead43
2130:S 22 Feb 15:17:49.396 # (00007ffd28bffbdc) -> 00007f582980d180
2130:S 22 Feb 15:17:49.417 # (00007ffd28bffbdb) -> 0000000000000010
2130:S 22 Feb 15:17:49.421 # (00007ffd28bffbda) -> 0000000000000df0
2130:S 22 Feb 15:17:49.425 # (00007ffd28bffbd9) -> 00007f56ffd00080
2130:S 22 Feb 15:17:49.440 # (00007ffd28bffbd8) -> 00007f56ffd00e70
2130:S 22 Feb 15:17:49.461 # (00007ffd28bffbd7) -> 0000000000000000
2130:S 22 Feb 15:17:49.475 # (00007ffd28bffbd6) -> 00007f3c9be0c350
2130:S 22 Feb 15:17:49.492 # (00007ffd28bffbd5) -> 0000000000000000
2130:S 22 Feb 15:17:49.511 # (00007ffd28bffbd4) -> 00007f56ffd00080
2130:S 22 Feb 15:17:49.533 # (00007ffd28bffbd3) -> 00007f55d2601a20
2130:S 22 Feb 15:17:49.558 # (00007ffd28bffbd2) -> 00007f5601c04610
2130:S 22 Feb 15:17:49.582 # (00007ffd28bffbd1) -> 000000000075be80
2130:S 22 Feb 15:17:49.609 # (00007ffd28bffbd0) -> 0000000000000003

------ FAST MEMORY TEST ------
2130:S 22 Feb 15:17:49.653 # Bio thread for job type #0 terminated
2130:S 22 Feb 15:17:49.673 # Bio thread for job type #1 terminated
2130:S 22 Feb 15:17:49.693 # Bio thread for job type #2 terminated
*** Preparing to test memory region 745000 (98304 bytes)
*** Preparing to test memory region 13b6000 (28714627072 bytes)
*** Preparing to test memory region 7f3a03402000 (6893723648 bytes)
*** Preparing to test memory region 7f3c7cc00000 (731906048 bytes)
*** Preparing to test memory region 7f3cb4000000 (286720 bytes)
*** Preparing to test memory region 7f3cb8200000 (65011712 bytes)
*** Preparing to test memory region 7f3cbc000000 (135168 bytes)
*** Preparing to test memory region 7f3cc0000000 (135168 bytes)
*** Preparing to test memory region 7f3cc4000000 (135168 bytes)
*** Preparing to test memory region 7f3cc8000000 (135168 bytes)
*** Preparing to test memory region 7f3ccc000000 (135168 bytes)
*** Preparing to test memory region 7f3cd0000000 (135168 bytes)
*** Preparing to test memory region 7f3cd4000000 (188416 bytes)
*** Preparing to test memory region 7f3cd8000000 (135168 bytes)
*** Preparing to test memory region 7f3cdc000000 (135168 bytes)
*** Preparing to test memory region 7f3ce0000000 (393216 bytes)
*** Preparing to test memory region 7f3ce4000000 (897024 bytes)
*** Preparing to test memory region 7f3ce8000000 (933888 bytes)
*** Preparing to test memory region 7f3cec000000 (135168 bytes)
*** Preparing to test memory region 7f3cf0000000 (135168 bytes)
*** Preparing to test memory region 7f3cf4000000 (135168 bytes)
*** Preparing to test memory region 7f3cf8000000 (135168 bytes)
*** Preparing to test memory region 7f3cfc000000 (135168 bytes)
*** Preparing to test memory region 7f3d00000000 (135168 bytes)
*** Preparing to test memory region 7f3d04000000 (135168 bytes)
*** Preparing to test memory region 7f3d08000000 (135168 bytes)
*** Preparing to test memory region 7f3d0c000000 (135168 bytes)
*** Preparing to test memory region 7f3d10000000 (135168 bytes)
*** Preparing to test memory region 7f3d14000000 (135168 bytes)
*** Preparing to test memory region 7f3d18000000 (135168 bytes)
*** Preparing to test memory region 7f3d1c000000 (204800 bytes)
*** Preparing to test memory region 7f3d20000000 (135168 bytes)
*** Preparing to test memory region 7f3d24000000 (135168 bytes)
*** Preparing to test memory region 7f3d28000000 (299008 bytes)
*** Preparing to test memory region 7f3d2c000000 (184320 bytes)
*** Preparing to test memory region 7f3d30200000 (29360128 bytes)
*** Preparing to test memory region 7f3d3c000000 (135168 bytes)
*** Preparing to test memory region 7f3d40200000 (4194304 bytes)
*** Preparing to test memory region 7f3d44000000 (135168 bytes)
*** Preparing to test memory region 7f3d48000000 (135168 bytes)
*** Preparing to test memory region 7f3d4c000000 (135168 bytes)
*** Preparing to test memory region 7f3d50000000 (135168 bytes)
*** Preparing to test memory region 7f3d54000000 (135168 bytes)
*** Preparing to test memory region 7f3d58000000 (135168 bytes)
*** Preparing to test memory region 7f3d5c000000 (180224 bytes)
*** Preparing to test memory region 7f3d60000000 (135168 bytes)
*** Preparing to test memory region 7f3d64000000 (176128 bytes)
*** Preparing to test memory region 7f3d68000000 (135168 bytes)
*** Preparing to test memory region 7f3d6c000000 (135168 bytes)
*** Preparing to test memory region 7f3d70000000 (135168 bytes)
*** Preparing to test memory region 7f3d74000000 (135168 bytes)
*** Preparing to test memory region 7f3d78000000 (135168 bytes)
*** Preparing to test memory region 7f3d7c000000 (135168 bytes)
*** Preparing to test memory region 7f3d80000000 (135168 bytes)
*** Preparing to test memory region 7f3d84000000 (135168 bytes)
*** Preparing to test memory region 7f3d88000000 (135168 bytes)
*** Preparing to test memory region 7f3d8c000000 (135168 bytes)
*** Preparing to test memory region 7f3d90000000 (135168 bytes)
*** Preparing to test memory region 7f3d94000000 (135168 bytes)
*** Preparing to test memory region 7f3d98000000 (135168 bytes)
*** Preparing to test memory region 7f3d9c000000 (135168 bytes)
*** Preparing to test memory region 7f3da0000000 (135168 bytes)
*** Preparing to test memory region 7f3da4000000 (135168 bytes)
*** Preparing to test memory region 7f3da8000000 (274432 bytes)
*** Preparing to test memory region 7f3dac000000 (135168 bytes)
*** Preparing to test memory region 7f3db0000000 (180224 bytes)
*** Preparing to test memory region 7f3db4000000 (274432 bytes)
*** Preparing to test memory region 7f3db8200000 (4194304 bytes)
*** Preparing to test memory region 7f3dc4000000 (135168 bytes)
*** Preparing to test memory region 7f3dcc000000 (135168 bytes)
*** Preparing to test memory region 7f3dd0000000 (135168 bytes)
*** Preparing to test memory region 7f3dd4000000 (135168 bytes)
*** Preparing to test memory region 7f3dd8000000 (176128 bytes)
*** Preparing to test memory region 7f3ddc000000 (135168 bytes)
*** Preparing to test memory region 7f3de0000000 (135168 bytes)
*** Preparing to test memory region 7f3de4000000 (135168 bytes)
*** Preparing to test memory region 7f3de8000000 (135168 bytes)
*** Preparing to test memory region 7f3dec000000 (135168 bytes)
*** Preparing to test memory region 7f3df0000000 (274432 bytes)
*** Preparing to test memory region 7f3df4000000 (135168 bytes)
*** Preparing to test memory region 7f3df8000000 (135168 bytes)
*** Preparing to test memory region 7f3dfc000000 (135168 bytes)
*** Preparing to test memory region 7f3e00000000 (135168 bytes)
*** Preparing to test memory region 7f3e04000000 (135168 bytes)
*** Preparing to test memory region 7f3e08000000 (184320 bytes)
*** Preparing to test memory region 7f3e0c000000 (135168 bytes)
*** Preparing to test memory region 7f3e10000000 (135168 bytes)
*** Preparing to test memory region 7f3e14000000 (135168 bytes)
*** Preparing to test memory region 7f3e18000000 (135168 bytes)
*** Preparing to test memory region 7f3e1c000000 (135168 bytes)
*** Preparing to test memory region 7f3e20000000 (135168 bytes)
*** Preparing to test memory region 7f3e24000000 (184320 bytes)
*** Preparing to test memory region 7f3e28000000 (135168 bytes)
*** Preparing to test memory region 7f3e2c000000 (135168 bytes)
*** Preparing to test memory region 7f3e30000000 (135168 bytes)
*** Preparing to test memory region 7f3e34000000 (135168 bytes)
*** Preparing to test memory region 7f3e38000000 (270336 bytes)
*** Preparing to test memory region 7f3e3c000000 (135168 bytes)
*** Preparing to test memory region 7f3e40000000 (2097152 bytes)
*** Preparing to test memory region 7f3e54000000 (135168 bytes)
*** Preparing to test memory region 7f3e58000000 (135168 bytes)
*** Preparing to test memory region 7f3e5c000000 (196608 bytes)
*** Preparing to test memory region 7f3e60000000 (135168 bytes)
*** Preparing to test memory region 7f3e64000000 (135168 bytes)
*** Preparing to test memory region 7f3e68000000 (135168 bytes)
*** Preparing to test memory region 7f3e6c000000 (176128 bytes)
*** Preparing to test memory region 7f3e70000000 (135168 bytes)
*** Preparing to test memory region 7f3e74000000 (135168 bytes)
*** Preparing to test memory region 7f3e78000000 (135168 bytes)
*** Preparing to test memory region 7f3e7c000000 (135168 bytes)
*** Preparing to test memory region 7f3e80200000 (2097152 bytes)
*** Preparing to test memory region 7f3f28000000 (135168 bytes)
*** Preparing to test memory region 7f3f2c000000 (135168 bytes)
*** Preparing to test memory region 7f3f30000000 (282624 bytes)
*** Preparing to test memory region 7f3f34000000 (135168 bytes)
*** Preparing to test memory region 7f3f38000000 (135168 bytes)
*** Preparing to test memory region 7f3f3c000000 (135168 bytes)
*** Preparing to test memory region 7f3f40000000 (135168 bytes)
*** Preparing to test memory region 7f3f44000000 (135168 bytes)
*** Preparing to test memory region 7f3f48000000 (135168 bytes)
*** Preparing to test memory region 7f3f4c000000 (274432 bytes)
*** Preparing to test memory region 7f3f50000000 (184320 bytes)
*** Preparing to test memory region 7f3f54000000 (135168 bytes)
*** Preparing to test memory region 7f3f58000000 (135168 bytes)
*** Preparing to test memory region 7f3f5c000000 (135168 bytes)
*** Preparing to test memory region 7f3f60000000 (135168 bytes)
*** Preparing to test memory region 7f3f64000000 (135168 bytes)
*** Preparing to test memory region 7f3f68000000 (184320 bytes)
*** Preparing to test memory region 7f3f6c000000 (135168 bytes)
*** Preparing to test memory region 7f3f70000000 (135168 bytes)
*** Preparing to test memory region 7f3f76800000 (4194304 bytes)
*** Preparing to test memory region 7f3f7e200000 (8388608 bytes)
*** Preparing to test memory region 7f3f84000000 (135168 bytes)
*** Preparing to test memory region 7f3f88000000 (10485760 bytes)
*** Preparing to test memory region 7f3f8c000000 (135168 bytes)
*** Preparing to test memory region 7f3f90000000 (135168 bytes)
*** Preparing to test memory region 7f3f94000000 (180224 bytes)
*** Preparing to test memory region 7f3f98000000 (135168 bytes)
*** Preparing to test memory region 7f3f9c000000 (135168 bytes)
*** Preparing to test memory region 7f3fa0000000 (135168 bytes)
*** Preparing to test memory region 7f3fa4000000 (134217728 bytes)
*** Preparing to test memory region 7f3fac000000 (135168 bytes)
*** Preparing to test memory region 7f3fb0000000 (135168 bytes)
*** Preparing to test memory region 7f3fb4000000 (135168 bytes)
*** Preparing to test memory region 7f3fb8000000 (172032 bytes)
*** Preparing to test memory region 7f3fbc000000 (135168 bytes)
*** Preparing to test memory region 7f3fc0000000 (135168 bytes)
*** Preparing to test memory region 7f3fc4000000 (135168 bytes)
*** Preparing to test memory region 7f3fc8000000 (135168 bytes)
*** Preparing to test memory region 7f3fcc000000 (135168 bytes)
*** Preparing to test memory region 7f3fd0000000 (274432 bytes)
*** Preparing to test memory region 7f3fd4000000 (135168 bytes)
*** Preparing to test memory region 7f3fd8000000 (180224 bytes)
*** Preparing to test memory region 7f3fdc000000 (135168 bytes)
*** Preparing to test memory region 7f3fe0000000 (135168 bytes)
*** Preparing to test memory region 7f3fe4000000 (135168 bytes)
*** Preparing to test memory region 7f3fe8000000 (135168 bytes)
*** Preparing to test memory region 7f3fec000000 (135168 bytes)
*** Preparing to test memory region 7f3ff0000000 (135168 bytes)
*** Preparing to test memory region 7f3ff4000000 (282624 bytes)
*** Preparing to test memory region 7f3ff8000000 (135168 bytes)
*** Preparing to test memory region 7f3ffc000000 (135168 bytes)
*** Preparing to test memory region 7f4000000000 (135168 bytes)
*** Preparing to test memory region 7f4004000000 (135168 bytes)
*** Preparing to test memory region 7f4008000000 (10485760 bytes)
*** Preparing to test memory region 7f5477a00000 (25165824 bytes)
*** Preparing to test memory region 7f55cc200000 (6291456 bytes)
*** Preparing to test memory region 7f55d4000000 (25165824 bytes)
*** Preparing to test memory region 7f5827ffa000 (12288 bytes)
*** Preparing to test memory region 7f5827ffe000 (8388608 bytes)
*** Preparing to test memory region 7f58287ff000 (8388608 bytes)
*** Preparing to test memory region 7f5829000000 (10485760 bytes)
*** Preparing to test memory region 7f5830000000 (2097152 bytes)
*** Preparing to test memory region 7f58305fc000 (20480 bytes)
*** Preparing to test memory region 7f5830819000 (16384 bytes)
*** Preparing to test memory region 7f5830f31000 (16384 bytes)
*** Preparing to test memory region 7f5830f41000 (12288 bytes)
*** Preparing to test memory region 7f5830f46000 (4096 bytes)
.45098:C 22 Feb 15:31:28.724 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo

**Comment by MeirShpilraien** [comment]
First, I recommend you to upgrade to 1.4.4 with redis 5, 1.2.0 is an old version and there was a lot of bug fixes (including crashes).
Second, did you do anything specific that cause the crash like drop index or flushall maybe?

**Comment by manishtoons** [comment]
Yeah, redis evicted few hundred thousands of keys when reached maxmemory

**Comment by MeirShpilraien** [comment]
@manishtoons did you managed to check on 1.4.4/5?

**Comment by manishtoons** [comment]
Today I upgraded to latest builds of redis and RS, haven't rolled out in production yet, I'll reply here if I able to reproduce this issue with current versions

**Comment by mnunberg** [comment]
Hi, I'm closing this bug for now. Reopen if you get this issue again
