### ISSUE TITLE
FT.SEARCH for TAG fails after TEXT update (using REPLACE PARTIAL)

### ISSUE THREAD

**Issue by youzi** [RedisLabsModules/RediSearch#621]
When having a simple schema like:
```
SCHEMA uuid TAG title TEXT
```
Updating the `title` field (type `TEXT`) on an existing doc using `REPLACE PARTIAL` breaks "searchability" for `uuid` field (type `TAG`).

Tricky to explain, here is an example:
```
❯ redis-cli ft.create test SCHEMA uuid TAG title TEXT
OK

❯ redis-cli ft.add test a 1 REPLACE PARTIAL FIELDS uuid foo title bar
OK

❯ redis-cli ft.search test '@uuid:{foo}'
1) (integer) 1
2) "a"
3) 1) "uuid"
   2) "foo"
   3) "title"
   4) "bar"

❯ redis-cli ft.add test a 1 REPLACE PARTIAL FIELDS title bar
OK

❯ redis-cli ft.search test '@uuid:{foo}'
1) (integer) 0
```

Result for `redis-cli ft.search test '@uuid:{foo}'` should be the same before/after updating `title`.

Only seems to break tags, not other texts.

**Comment by youzi** [comment]
fyi: Using latest docker image: `docker run -p 6379:6379 redislabs/redisearch:latest`

**Comment by MeirShpilraien** [comment]
Hey, thanks for reporting.
Please follow the PR for the fix : https://github.com/RedisLabsModules/RediSearch/pull/625
