### ISSUE TITLE
Optional query & weight query attribute returning wrong results

### ISSUE THREAD

**Issue by dme-development** [RedisLabsModules/RediSearch#623]
As discussed in the mailinglist, I've been experimenting with query boosting on optional clauses.

I'm creating this ticket because I believe there is a bug in the sorting or even in the querying when using optional clauses.

To my opinion the following queries are returning the wrong results:

In the first case (optional parameters in front of real clauses), the first two results are as expected, however nr 3,4 and 5 don't correspond with the real where clause but also not with the optional clauses.
```
0.0.0.0:6379> "FT.SEARCH" "idxCars" "~@Make:BMW=>{ $weight: 100; } ~@Make:Volvo=>{ $weight: 50; } @BodyType:Break" RETURN 2 Make BodyType LIMIT 0 5
 1) (integer) 121
 2) "CAI:3193376"
 3) 1) "Make"
    2) "BMW"
    3) "BodyType"
    4) "Hatchback"
 4) "CAI:3193257"
 5) 1) "Make"
    2) "BMW"
    3) "BodyType"
    4) "Hatchback"
 6) "CAI:3193380"
 7) 1) "Make"
    2) "Chevrolet"
    3) "BodyType"
    4) "MPV"
 8) "CAI:3193379"
 9) 1) "Make"
    2) "Audi"
    3) "BodyType"
    4) "Hatchback"
10) "CAI:3193378"
11) 1) "Make"
    2) "Aston Martin"
    3) "BodyType"
    4) "MPV"
```

In the second example  (optional parameters in behind the real clauses) it seems as if the optional clauses are completly ignored:

```
0.0.0.0:6379> "FT.SEARCH" "idxCars" "@BodyType:Break ~@Make:BMW=>{ $weight: 100; } ~@Make:Volvo=>{ $weight: 50; } " RETURN 2 Make BodyType LIMIT 0 5
 1) (integer) 29
 2) "CAI:3193303"
 3) 1) "Make"
    2) "Mercedes-Benz"
    3) "BodyType"
    4) "Break"
 4) "CAI:3193274"
 5) 1) "Make"
    2) "Mercedes-Benz"
    3) "BodyType"
    4) "Break"
 6) "CAI:3193289"
 7) 1) "Make"
    2) "Skoda"
    3) "BodyType"
    4) "Break"
 8) "CAI:3193288"
 9) 1) "Make"
    2) "Toyota"
    3) "BodyType"
    4) "Break"
10) "CAI:3193348"
11) 1) "Make"
    2) "BMW"
    3) "BodyType"
    4) "Break"
```

**Comment by dme-development** [comment]
Bug is still seen in the most recent version of the master (Git=v1.4.2-268-g83e6790c)

**Comment by mnunberg** [comment]
Hi, can you provide some sample entries of `idxCars`?

**Comment by dme-development** [comment]
@mnunberg: I've send you the dump via mail.

**Comment by nhapq** [comment]
Hello. I got the same issue. My query score seems to be correct on first three items, but it gives wrong results on the rest.

The scoring works perfectly if the query matchs with only one field of the documents. The error happens when the query matchs 2-3 fields of the documents.

**Comment by mnunberg** [comment]
This seems to be a parsing issue. Ensure that optional clauses are always enclosed by parens i.e. `(~@Make:BMW)`. See FT.EXPLAIN or FT.EXPLAINCLI for more information on how the query is actually being parsed.

**Comment by dme-development** [comment]
I've tested immediatly, but I don't think it is the full solution. The real query is correct now, but the optional clauses (with or without additional weight) are still not being calculated in the score. 

See this example:

```
0.0.0.0:6379> "FT.SEARCH" "idxCars" "@BodyType:Break (~@Make:BMW=>{ $weight: 100; }) (~@Make:Volvo=>{ $weight: 50; })" RETURN 2 Make BodyType LIMIT 0 5
 1) (integer) 30
 2) "CAI:3193303"
 3) 1) Make
    2) "Mercedes-Benz"
    3) BodyType
    4) "Break"
 4) "CAI:3193274"
 5) 1) Make
    2) "Mercedes-Benz"
    3) BodyType
    4) "Break"
 6) "CAI:3193289"
 7) 1) Make
    2) "Skoda"
    3) BodyType
    4) "Break"
 8) "CAI:3193288"
 9) 1) Make
    2) "Toyota"
    3) BodyType
    4) "Break"
10) "CAI:3191693"
11) 1) Make
    2) "Subaru"
    3) BodyType
    4) "Break" 
```

**Comment by nhapq** [comment]
Hi, I rewrite a scoring extension and I guess something went wrong with your:
tfidfRecursive(r->agg.children[i], dmd)
https://github.com/RedisLabsModules/RediSearch/blob/master/src/ext/default.c

The r->argg.children[i] behave differently on each documents, although my documents are pretty much the same. The error happens when two or more of query's field tag match with the document's fields (if only one single field is matched, everything works correctly.)

**Comment by mnunberg** [comment]
Yeah, I'm seeing that simply adding parens doesn't solve the issue.

@nhapq Can you file a new ticket? This doesn't seem related to the issue at hand.

**Comment by nhapq** [comment]
Hi @mnunberg , I don't know what causes this issue, but I believe I have the same problem with @dme-development : the scoring function words correctly for 2-3 documents then misbehave on he rest of results. I used the custom weight on tag fields as well.

with that said, I would like to apologize if they are not the same issue.

**Comment by mnunberg** [comment]
The issue we are seeing here seems more related to optional queries than the actual scoring functionality.

**Comment by dme-development** [comment]
Maybe @nhapq has a point, because when wrapping the optional clauses by parens, it seems that the real filter clauses are correct at least. Maybe then all that is left, is wrong calculated scoring functionality?

**Comment by mnunberg** [comment]
This one was quite tough to crack, but I believed I've identified the cause. It does not relate to the scoring function, but rather relates to the internals of the query iterators. I'll be coming with a fix later today or tomorrow.

**Comment by mnunberg** [comment]
@dme-development I've added a fix which should address this issue; let me know if this works for you.

**Comment by dme-development** [comment]
@mnunberg : I was able to do some tests today with the latest version of the master branch. The issue seems resolved. The first results are as expected. Will do some additional testing in the next days.
