### ISSUE TITLE
Retrieve multiple documents based on docIds similar to FT.MGET

### ISSUE THREAD

**Issue by gkorland** [RedisLabsModules/RediSearch#626]
moved from https://github.com/RediSearch/JRediSearch/issues/59

**Comment by mnunberg** [comment]
@shannonantony I'm unsure what you mean by docIds or how you want it to behave any differently than `FT.MGET`

**Comment by shannonantony** [comment]
I am looking for functionality similar to FT.MGET.

**Comment by mnunberg** [comment]
I'm still unsure what you mean by "similar to" FT.MGET. Why is FT.MGET insufficient?

**Comment by shannonantony** [comment]
Looking for similar functionality as part of java api

**Comment by mnunberg** [comment]
Reopened related Java ticket. We have MGET in the server itself.
