### ISSUE TITLE
Failed creating an index with numeric field and weight

### ISSUE THREAD

**Issue by omrib1** [RedisLabsModules/RediSearch#629]
When trying to create a numeric field with weight - we get an error: **Could not parse field spec**
This command works - weight is set to **text** field:
```
172.31.12.109:17039> FT.CREATE indx4 SCHEMA title TEXT WEIGHT 2.0 num NUMERIC
OK
```

This command doesn't work - weight is set to **numeric** field:
```
172.31.12.109:17039> FT.CREATE indx4 SCHEMA title TEXT num NUMERIC WEIGHT 3.0
(error) Could not parse field spec
```

**Comment by mnunberg** [comment]
Weight is not currently supported for numeric fields

**Comment by MeirShpilraien** [comment]
We should document it then ..
