### ISSUE TITLE
LIMIT 0 0 broken in master

### ISSUE THREAD

**Issue by mnunberg** [RedisLabsModules/RediSearch#635]
It appears that because of the way the options parser works, LIMIT 0 0 is understood as "use the defaults", rather than "don't return anything".

**Comment by K-Jo** [comment]
+ document behaviour

**Comment by mnunberg** [comment]
I'd feel much more comfortable with an explicit option like `COUNT_ONLY` instead of this magic trick.

**Comment by mnunberg** [comment]
Also, LIMIT 1 0 should work on both previous and current versions.. I think

**Comment by K-Jo** [comment]
+1 on the COUNT_ONLY syntax.  Suggest we sugar syntax it, but keep LIMIT 0 0 working too

**Comment by mnunberg** [comment]
It turns out that while we test for it, there is a bug which manifests when the result set is > 1 :) -- unfortunately, our test only uses a single result. The fix is simple.
