### ISSUE TITLE
Deleting a graph that does not exist crashes Redis

### ISSUE THREAD

**Issue by johntilley** [RedisLabsModules/RediSearch#639]
=== REDIS BUG REPORT START: Cut & paste starting from here ===
2618:M 23 Mar 10:03:14.319 # Redis 4.0.9 crashed by signal: 11
2618:M 23 Mar 10:03:14.319 # Crashed running the instruction at: 0x7f7eebf46802
2618:M 23 Mar 10:03:14.319 # Accessing address: 0x460
2618:M 23 Mar 10:03:14.319 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libpthread.so.0(pthread_rwlock_wrlock+0x12)[0x7f7eebf46802]

Backtrace:
/usr/bin/redis-server 0.0.0.0:6379(logStackTrace+0x5a)[0x56395b349eca]
/usr/bin/redis-server 0.0.0.0:6379(sigsegvHandler+0xb1)[0x56395b34a681]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7f7eebf4c890]
/lib/x86_64-linux-gnu/libpthread.so.0(pthread_rwlock_wrlock+0x12)[0x7f7eebf46802]
/etc/redis/RedisGraph/src/redisgraph.so(Graph_AcquireWriteLock+0x10)[0x7f7ee954e910]
/etc/redis/RedisGraph/src/redisgraph.so(_MGraph_Delete+0x118)[0x7f7ee95441e8]
/etc/redis/RedisGraph/src/redisgraph.so(+0x7fa44)[0x7f7ee955da44]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f7eebf416db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f7eebc6a88f]

**Comment by itamarhaber** [comment]
Needs to be moved to graph repo.

**Comment by johntilley** [comment]
Sorry my bad
