### ISSUE TITLE
Nested documents indexing and search of parents by children and vice verse is possible in RediSearch ?

### ISSUE THREAD

**Issue by aadibansal** [RedisLabsModules/RediSearch#648]

**Comment by mnunberg** [comment]
At the moment, redisearch utilizes a simple hash datatype, so it does not support hierarchical documents. Of course, you can simply pump JSON or whatever document you want, which contains text, into redisearch, and redisearch would then be able to index the text; but you wouldn't be able to do something like `@foo.bar.baz:[0, 10]`
