### ISSUE TITLE
Doc: When is full repopulate needed when upgrading RediSearch?

### ISSUE THREAD

**Issue by tw-bert** [RedisLabsModules/RediSearch#652]
First of all: Loving this product.

We're in the process of upgrading FT `1.4.0` to FT `1.4.6`.

**Question:** Do we need to completely `FT.DROP` all indices, recreate, and repopulate them, to make use of new features and get rid of bugfix-related side-effects?

1. If it's necessary, it would be nice to have an upgrade matrix in the docs. And/or make an upgrade path statement at each release note.
2. If it's not necessary: great, that would save us a lot of hassle.

_As a sidenote:_ we just had our first FT related crash since going live with RediSearch. We've been using RediSearch version `1.4.0` for over a year. It happened on a replica slave, at `redisearch.so(DocTable_Free+0x39)` , OS (Ubuntu Xenial) issued `signal 11` (segfault). The event triggering the slave crash, was a `FT.DROP` on the master, of a medium large (0.5M rows) index. Only 1 slave (of several) crashed, possibly indicating a threading issue. We can't reproduce it, and are moving to the latest FT version anyway, so not creating an issue for it unless you are interested. 

Cheers, TW

**Comment by MeirShpilraien** [comment]
@tw-bert I guess you mean version 1.4.0 and not 4.0.0 (which does not exist).
Regrading the upgrade you can just save the data to rdb (using save command) and then start the redis with the new version, we support backward compatibility so the new version will be able to read the rdb. That said, upgrade is always a risky process so I suggest to first take a copy of the rdb and try to load it to v1.4.6 on a none production environment, just to make sure its loaded successfully.

Regarding the crash, we are aware of rare issue with FT.DROP that causing crashes. We are currently investigating it and hope we will have a fix soon.

**Comment by tw-bert** [comment]
@MeirShpilraien Thanks for the info. 

> I guess you mean version 1.4.0 and not 4.0.0 (which does not exist).

Yes indeed. I'll change the text above.

> we support backward compatibility so the new version will be able to read the rdb. 

Does any conversion take place when loading an rdb or aof, at first start of a higher version of RediSearch? Or can I easily switch back and forth, with in-between redis dumps?

And furthermore: there were some improvements on `NOSAVE` (index-only) FT.ADD's, if I remember correctly. I can imagine some of the new `FT.SEARCH` functionality relies on that. So, it surprises me a little bit that repopulating the indices wouldn't be needed.

> try to load it to v1.4.6 on a none production environment

We already did some tests in a development environment. We are investigating one issue, not sure yet if it's FT related. My question here is not about obvious crashes and stuff (we'll notice them in our dev environments), but more about exact-same-result of queries when switching to a later FT version. Not asking for guarantees, an educated guess would be enough.

> we are aware of rare issue with FT.DROP that causing crashes

Useful input. Hope you find something.

Cheers, Tijs

**Comment by mnunberg** [comment]
> On Apr 11, 2019, at 5:00 PM, tw-bert <notifications@github.com> wrote:
> 
> @MeirShpilraien <https://github.com/MeirShpilraien> Thanks for the info.
> 
> I guess you mean version 1.4.0 and not 4.0.0 (which does not exist).
> 
> Yes indeed. I'll change the text above.
> 
> we support backward compatibility so the new version will be able to read the rdb.
> 
> Does any conversion take place when loading an rdb or aof, at first start of a higher version of RediSearch? Or can I easily switch back and forth, with in-between redis dumps?
> 
> And furthermore: there were some improvements on NOSAVE (index-only) FT.ADD's, if I remember correctly. I can imagine some of the new FT.SEARCH functionality relies on that. So, it surprises me a little bit that repopulating the indices wouldn't be needed.
> 
> 
I don’t recall any improvements on that front recently (it may have been a looooong time ago), but in any event, fundamentally, search is divided into two parts; the first part is just retrieving the documents from the indices, and the second is actually formatting the results, getting the rest of the document contents; scoring, sorting, etc.

The first part relies on an encoded inverted index format which has remained virtually unchanged since the earlier versions of FT (though we’ve made improvements in how those are read, processed, etc.) and that is probably the single most important factor of portability.

The second doesn’t really, broadly speaking, care about how the data is saved, but is more to do with how the data is present in RAM, which can be deserialized from whatever version the rdb was saved as.

**Comment by tw-bert** [comment]
@mnunberg Thank you Mark, excellent info. Closing this.
