### ISSUE TITLE
Serious FT.GET bug

### ISSUE THREAD

**Issue by mluggy** [RedisLabsModules/RediSearch#653]
redis 5.0.4 and redisearch 1.4.6. FT.GET ignores index name.

```
127.0.0.1:6379> FT.CREATE foo SCHEMA name TEXT
OK
127.0.0.1:6379> FT.ADD foo foo1 1 FIELDS name foo1-name
OK
127.0.0.1:6379> FT.GET foo foo1
1) "name"
2) "foo1-name"
127.0.0.1:6379> FT.CREATE bar SCHEMA whatever TEXT
OK
127.0.0.1:6379> FT.GET bar foo1
1) "name"
2) "foo1-name"
```

**Comment by mnunberg** [comment]
This should be fixed in master. In any event, I'm unsure I'd consider this a serious bug, because the document is actually stored as a plain hash under the document name (unless the `NOSAVE` option is passed to `FT.ADD`)

**Comment by mluggy** [comment]
how's this not a serious issue? the index name is ignored.

**Comment by mnunberg** [comment]
Because you shouldn't have a document with the same name in multiple indexes anyway. Anyway, this has been fixed in master. I just didn't want to let off the impression that you can have a "doc1" in idx1 and a "doc1" in idx2

**Comment by mluggy** [comment]
ok, now i get it. you look at redisearch as a way to index existing redis documents (which have unique keys), where i looked at it as a general purpose database where the key is composed of the index+docId.

so ft.add idx1 doc1 and ft.add idx2 doc1 simply make the same doc1 available on both indexes.

**Comment by mnunberg** [comment]
So this is actually a point of confusion. As it stands right now, it’s “both”, unfortunately with the restrictions of both. What I mean is that we:

- Recommend to only use the FT.* commands for accessing the keys (so if you just do HSET, the newly modified data does not get reindexed)
- Be aware that all “documents” share a single keyspace; so there is no namespace isolation within different indexes.

Now in the long term, we’d like a scenario where doing HSET will cause a reindex of the document, but it’ll be a while before this becomes available and stable within redisearch.

**Comment by mluggy** [comment]
yea, i wasn't aware. as mentioned I'm not handling any redis documents directly, only through redisearch. this started a journey that supposedly do this: https://twitter.com/mluggy/status/1057994312800198656
