### ISSUE TITLE
If a field is set to "NOINDEX" can I just make edits to the data's hash?

### ISSUE THREAD

**Issue by yghaile** [RedisLabsModules/RediSearch#655]
It seems like there shouldn't be an issue, but I would greatly appreciate some confirmation.  If so, I think this should be noted in the documentation.

**Comment by mnunberg** [comment]
Theoretically speaking, we try to abstract the fact that the document is in fact a hash away from the user. This is why we have commands like FT.GET. In theory, the document could reside elsewhere. However, assuming today’s implementation, there is no harm from editing the document’s fields indexed with NOINDEX via HSET etc.

**Comment by yghaile** [comment]
Got it.  Thank you.
