### ISSUE TITLE
Do we use space to record lack of membership in a given field?

### ISSUE THREAD

**Issue by kchristidis** [RedisLabsModules/RediSearch#662]
Assume:
1. an index with fields `FOO` and `BAR` in its schema
2. document `doc1` with both fields set
3. document `doc2` with only the `FOO` field set

Does RediSearch use any data to record the fact that `doc2` has its `BAR` field unset?

Logic says that it doesn't (we just record _membership_ in the inverted index, not lack of), but I'd like to double-check.

**Comment by MeirShpilraien** [comment]
RediSearch does not use any data to record the fact that doc2 has its BAR field unset.
The fields list saved globally on the index itself.
