### ISSUE TITLE
Cannot import Client

### ISSUE THREAD

**Issue by nengine** [RedisLabsModules/RediSearch#675]
I installed redisearch but cannot import.
```
>>> from redisearch import Client, TextField, NumericField, Query
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Client
```

**Comment by mnunberg** [comment]
Can you file this bug under the Python project?

Also, what version of the Python client are you using? It seems to work for me

**Comment by nengine** [comment]
Hi, Sorry about this.  I had a redisearch.py to import redisearch so this is why happening.  Works now.  Thanks a lot.
