### ISSUE TITLE
Redisearch persistence

### ISSUE THREAD

**Issue by autocorrectoff** [RedisLabsModules/RediSearch#676]
Google gave me no answers so I'm posting my question here: I'm using redis with AOF set, and data persists, even when I restart the server. When I start the redis server using --loadmodule flag to load redisearch.so, save some data, all works as expected, but when I stop the server and start it again, again loading redisearch, no data is persisted. Is this behavior expected? Is there no way to persist redisearch data after server restart?

**Comment by MeirShpilraien** [comment]
It should work both with AOF and RDB. Can you share more information about how you run the redis (redis config file, cmd command, ...).
In addition Can you verify that an aof file is actually created? If fore example you just perform `set` commands and then restart, is the data exists after the restart?

**Comment by autocorrectoff** [comment]
@MeirShpilraien It works now, I've added the module load inside redis.conf. It doesn't work when manually starting the server from the terminal, but it's not a redisearch issue because 'KEYS *' returns 'nil' even though I've stored data before stopping the server. This is happening on Ubuntu. 
Anyways, loading redisearch in redis.conf does the job
