### ISSUE TITLE
LIMIT return redundant records on the end of list

### ISSUE THREAD

**Issue by onexdrk** [RedisLabsModules/RediSearch#68]
From #61 

Seems that paging work not absolutely correct. Imagine i want to organize paging functionality with page-size = 4

create an index and add five documents to it:
```
FT.CREATE indexName SCHEMA status TEXT

FT.ADD indexName doc1 1 FIELDS status open
FT.ADD indexName doc2 1 FIELDS status open
FT.ADD indexName doc3 1 FIELDS status open
FT.ADD indexName doc4 1 FIELDS status open
FT.ADD indexName doc5 1 FIELDS status open
```
Then i want to get first page with 4 elements in it:

```
FT.SEARCH indexName "@status:open" LIMIT 0 4
1) (integer) 5
2) "doc5"
3) 1) "status"
   2) "open"
4) "doc4"
5) 1) "status"
   2) "open"
6) "doc3"
7) 1) "status"
   2) "open"
8) "doc2"
9) 1) "status"
   2) "open"
```
response correct

Now i want go see last element:
```
FT.SEARCH indexName "@status:open" LIMIT 4 4
1) (integer) 5
2) "doc4"
3) 1) "status"
   2) "open"
4) "doc3"
5) 1) "status"
   2) "open"
6) "doc2"
7) 1) "status"
   2) "open"
8) "doc1"
9) 1) "status"
   2) "open"
```
Incorrect - must contains only doc1.

I think i can try fix it in backend and if it is last page - trim result and use just a tail, but it looks like a problem

**Comment by dvirsky** [comment]
Works fine now, and I've added a test to make sure it remains like that. You can pull master and verify. Re-open if you find anything I missed. Thanks!

**Comment by autocorrectoff** [comment]
@dvirsky in which version was this fixed? because I'm experiencing it still, perhaps my prod redisearch version is an older one

**Comment by mnunberg** [comment]
If you see https://github.com/RediSearch/RediSearch/commit/345f417b9fd26a3b83793eee0dc2c6dfae1c3153, you'll see all the versions that include this fix. It's been around for a while :)

**Comment by dvirsky** [comment]
Wow, that is oooold. Exactly two years since the fix. 
Any chance that this is another issue manifesting itself in a similar manner?

**Comment by autocorrectoff** [comment]
the version this is happening on is 1.4.6. the query is something like this: ft.search index_name * return 1 some_field sortby bad_numeric limit 0 10. it doesn't occur when querying with no sortby, or sortby and another sortable numeric field in the index, just with this one sortable numeric field. the only difference I notice between the two sortable numerics is that the bad one is a 7 digits number, while the good one is a 5 digits number

**Comment by autocorrectoff** [comment]
ok, i think i figured out what is going on: the values of bad_numeric are not unique, there are duplicates and in the duplicate situation ft.search doesn't return in the records in the same order... any chance that sorting by multiple fields will be implemented in the future?

**Comment by mnunberg** [comment]
If you issue a query via FT.AGGREGATE, you can sort by multiple fields. Starting from version 1.6, FT.AGGREGATE is essentially a superset of FT.SEARCH, with some caveats in how fields are returned

**Comment by autocorrectoff** [comment]
but ft.aggregate returns only the fields you specify in groupby clause. or am i wrong?

**Comment by mnunberg** [comment]
You don't need to specify a `GROUPBY` clause in FT.AGGREGATE. It can be used as a direct substitute for FT.SEARCH if you specify the fields you want returned by the `LOAD` keyword. In version 1.6 it should also accept the `RETURN` keyword, but better use `LOAD` as that's documented.

**Comment by autocorrectoff** [comment]
so, i created a query like this:
FT.AGGREGATE index_name "*" LOAD 5 @f1 @f2 @f3 @f4 @f5 APPLY matched_terms() AS term sortby 2 @f1 asc @f2 desc
but, if i try to use more complex search term insted of "*", like "@f1:{ value1 } -@f2:{ value2 } (@f3:{ value3 } @f3:{ value4 }) | (@f3:{ value5 } @f3:{ value6 })", it doesn't return correct results. 
is this achievable or not with ft.aggregate?

**Comment by mnunberg** [comment]
It should return the exact same results. Make sure you’re sorting them by the same values!

**Comment by f3** [comment]
let's be careful with the formatting of comments  😄  `@f3` instead of @f3  would've saved some electrons from hitting my inbox  
> FT.AGGREGATE index_name "" LOAD 5 @mnunberg @autocorrectoff APPLY ...

kidding folks, of course
