### ISSUE TITLE
How removal operations are expensive?

### ISSUE THREAD

**Issue by AreaScript** [RedisLabsModules/RediSearch#682]
I have 100k documents in the search index. I make 3-6/sec operations on deleting.

the radisearch begins to work very slowly or completely blocked for some time. 

Any of the deleting operations separately also make a high load cpu.
At the same time, the addition of new documents does not present a problem. Intensive read operations are also ~ 10 / sec.

How removal operations are expensive?
It seems that this performance is exhausted.

I would be grateful for recommendations or tip.

**Comment by mnunberg** [comment]
ft.del deletes documents, but it eventually triggers garbage collection which may be time consuming if you have a lot of documents. However, 3-6/s documents is fairly trivial and should not cause that kind of performance hit at all. It should only be noticeable if you are also using replace operations (which internally is just del + add).

It’s quite abnormal to have the process blocked. Are you performing any other operations at the time? What is your application doing when the load is 13-21%? Search should be idle unless it’s being actively queried/added to.

**Comment by AreaScript** [comment]
When the load is 13-21% of the CPU, my app adding a new documents (3-5 doc per sec) and have read operations are ~ 60 / sec.

At the same time, I use the replace and partial replace operations for the noindex and sortable noindex fields (I even tried not to use them for a while, it doesn't matter)

No problem until start deleting documents.

I can still continue to work as usual, but as the index grows, the number of deletions should be reduced, and soon the prospect of deleting documents while the application is running will be sad.

**Comment by AreaScript** [comment]
I disabled the garbage collector, and CPU usage is now 10-15%, and removal operations become fast and do not cause problems

I do 30-60 / sec partial replace on the fields NUMERIC SORTABLE NOINDEX, I hope the garbage will not much grow from this... or that a 1-3 document is added/deleted every second. time will tell

Sometimes I will use FT.DROP instead of the garbage collector and re-create the index again with unloading data from Mysql

I hope this strategy is also acceptable.


Thanks for the tip.
