### ISSUE TITLE
Wrong complex query parsing

### ISSUE THREAD

**Issue by onexdrk** [RedisLabsModules/RediSearch#69]
Hello, i had another kind of problem, i have index with fields @status : text, @current_bet : NUMERIC

I want to find items with: status = open & current_bet > 200 & current_bet < 6000, need to use syntax with 3 conditions

```
127.0.0.1:7771> FT.EXPLAIN 2_25_1496935565 "   ( @status: \"open\" )   ( (@current_bet: [200.000000 +inf]) (@current_bet: [-inf 6000.000000]) )  "
@status:INTERSECT {
  @status:open
  @status:INTERSECT {
    NUMERIC {200.000000 <= @current_bet <= inf}
    NUMERIC {-inf <= @current_bet <= 6000.000000}
  }
}
```

same search but duplicate one condition in other place (problem not in duplicate, just for illustrate a problem)

```
127.0.0.1:7771> FT.EXPLAIN 2_25_1496935565 "   ( @status: \"open\" )   ( (@current_bet: [200.000000 +inf]) (@current_bet: [-inf 6000.000000]) ) (@current_bet: [200.000000 +inf])  "
@status:INTERSECT {
  @status:open
  @status:INTERSECT {
    NUMERIC {200.000000 <= @current_bet <= inf}
    NUMERIC {-inf <= @current_bet <= 6000.000000}
    NUMERIC {200.000000 <= @current_bet <= inf}
  }
}
```

```
127.0.0.1:7771> FT.SEARCH 2_25_1496935565 "   ( @status: \"open\" )   ( (@current_bet: [200.000000 +inf]) (@current_bet: [-inf 6000.000000]) )  "
5

127.0.0.1:7771> FT.SEARCH 2_25_1496935565 "   ( @status: \"open\" )   ( (@current_bet: [200.000000 +inf]) (@current_bet: [-inf 6000.000000]) ) (@current_bet: [200.000000 +inf])  "
7
```

i had different result, seems that @status was ignored

**Comment by dvirsky** [comment]
I'm not sure it's a query parsing bug, but what you are doing can simply be expressed as `@status:open @current_bet[200 6000]`. Or am I missing something?

**Comment by dvirsky** [comment]
@onexdrk this indeed wasn't a parsing problem, but a bug in the intersection algorithm. A fixed version should be out tomorrow. Thanks for noticing.

**Comment by dvirsky** [comment]
Should be okay in current master. Can you please verify?

**Comment by onexdrk** [comment]
excuse me, but can't do it now. I'll check it and message you later

**Comment by dvirsky** [comment]
Thanks!

**Comment by dvirsky** [comment]
@onexdrk can we close this one?

**Comment by dvirsky** [comment]
Closing, please reopen if needed.
