### ISSUE TITLE
FEATURE REQUEST: utf-8 support in autocomplete

### ISSUE THREAD

**Issue by mannol** [RedisLabsModules/RediSearch#7]
It's me again!
Just tried some searches containing utf-8 characters and here are the results:

```
// add utf8-encoded string
redisCommand(ctx, "FT.SUGADD userslex %b 1", "\u010Caji\u0107", sizeof("\u010Caji\u0107") - 1); 

// None of the two queries bellow have found the match
redisCommand(ctx, "FT.SUGGET userslex %b MAX 2 FUZZY", "\u010Caj", sizeof("\u010Caj") - 1);
redisCommand(ctx, "FT.SUGGET userslex %b MAX 2 FUZZY", "aji", sizeof("aji") - 1);

// However, if the utf8 character comes after the searched characters
redisCommand(ctx, "FT.SUGADD userslex %b 1", "Caji\u0107", sizeof("Caji\u0107") - 1);

// The query can find it
redisCommand(ctx, "FT.SUGGET userslex %b MAX 2 FUZZY", "aji", sizeof("aji") - 1);
```

Is it possible to implement this?

**Comment by dvirsky** [comment]
ah yes... a painful subject. 

For **non** fuzzy searches it works fine of course. for fuzzy queries it will require to align everything to 16 bit non variable encoding, which will increase memory footprint. And on top of that to normalize the text and remove accents, etc. Not trivial at all.

I'll need to have a look at the code to see what can be done. How critical/urgent it is for you? This one might take a few days of work and not a few hours of work.

**Comment by mannol** [comment]
Just checked, non fuzzy searches have the same results as the fuzzy ones; at least on my machine.
Well, I have about three weeks to fully implement search so considering that this already saved my a lot of effort, you can take your time. :)

**Comment by dvirsky** [comment]
Can you post the exact non fuzzy example you're having trouble with? As long as we're doing non fuzzy search, the search is just on sequences of bytes that have no meaning, so there shouldn't be any problem.

**Comment by dvirsky** [comment]
There could be problems with accents - if you're inserting with an accent and searching without an accent, we search the exact string you typed, so you won't find it. That should be handled on the client side as of now.

**Comment by mannol** [comment]
The example is the same as above without FUZZY arguments. I understand FUZZY searches having troubles with this but of course non fuzzy ones should just compare bytes - is what I thought.

**Comment by dvirsky** [comment]
But the example you give deoes not apply to non fuzzy searches  - you insert `\u010Caji\u0107` and then search for `Caji\u0107` and `aji`. Neither are prefixes of the string you've entered

**Comment by mannol** [comment]
Ah, yes but in the first part of the example it should be the case.
Unless I'm missing something obvoius: added `\u010Caji\u0107` searching for `\u010Caj` finds nothing
```
redisCommand(ctx, "FT.SUGADD userslex %b 1", "\u010Caji\u0107", sizeof("\u010Caji\u0107") - 1);
redisCommand(ctx, "FT.SUGGET userslex %b MAX 2", "\u010Caj", sizeof("\u010Caj") - 1);
```

**Comment by dvirsky** [comment]
ok, this seems like it's just a bug, regardless of unicode support. care to open a separate issue?

**Comment by mannol** [comment]
Sure, let me do that.

**Comment by dvirsky** [comment]
it might actually be a problem with the way hiredis encodes these escape sequences. I'll check

**Comment by mannol** [comment]
I made an issue including 2 examples, check it out >> #8

**Comment by dvirsky** [comment]
reopening as a new issue
