### ISSUE TITLE
sorting and limit problem.the last doc is wrong.

### ISSUE THREAD

**Issue by AllenLi1990** [RedisLabsModules/RediSearch#80]
version 0.17.2
first create index and insert data.
```
FT.CREATE myIdx SCHEMA title TEXT WEIGHT 5.0 body TEXT url TEXT sc NUMERIC SORTABLE
FT.ADD myIdx doc1 1.0 FIELDS title "hello world" body "lorem ipsum" url "http://redis.io" sc 1
FT.ADD myIdx doc2 1.0 FIELDS title "hello world" body "lorem ipsum" url "http://redis.io" sc 2
```
ok. here we sort by sc field(asc) and limit 2 doc return.
```
FT.SEARCH myIdx "hello" NOCONTENT SORTBY sc ASC LIMIT 0 2
```
```
1) (integer) 2
2) "doc1"
3) "doc2"
```

now we just want return the first one.
```
FT.SEARCH myIdx "hello" NOCONTENT SORTBY sc ASC LIMIT 0 1
```
```
1) (integer) 2
2) "doc2"
```
it will return doc2. After my practice found, not mater how many data I inserted, when I use limit and sort, the last doc is fixed.

**Comment by dvirsky** [comment]
I'll look into it, thanks.

**Comment by dvirsky** [comment]
Fixed, thank you for noticing

**Comment by AllenLi1990** [comment]
Thaks~LOL

**Comment by dvirsky** [comment]
Notice that upgrading redisearch requires upgrading redis to the latest unstable or 4.0 branches
