### ISSUE TITLE
Server dies on FT.SEARCH

### ISSUE THREAD

**Issue by stockholmux** [RedisLabsModules/RediSearch#82]
I can't seem to get the module to run. I'm running Redis 4 RC3 and RediSearch 0.18 on macOS. Every time I attempt to FT.SEARCH the server dies and the subsequently client eats it.

Here is what I'm doing:
```
127.0.0.1:6379> ft.create redishop-ft schema name text
OK
127.0.0.1:6379> hget redishop3:items:Small-Abstract-Mug name
"Small Abstract Mug"
127.0.0.1:6379> FT.ADDHASH redishop-ft redishop3:items:Small-Abstract-Mug 1
OK
127.0.0.1:6379> FT.SEARCH redishop-ft "hello world"
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```

I can simplify it even more:
```
127.0.0.1:6379> ft.create redishop-ft schema name text
OK
127.0.0.1:6379> FT.SEARCH redishop-ft "hello world"
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```
Attached is the bug report.

[redisearch-bug-report.txt](https://github.com/RedisLabsModules/RediSearch/files/1110556/redisearch-bug-report.txt)

**Comment by dvirsky** [comment]
As stated on the release notes of 0.18, it doesn't work with RC3 and requires the latest 0.4 or unstable branch to work.

**Comment by dvirsky** [comment]
@stockholmux you've inspired me to detect this issue and crash with a proper log message:

```
32343:C 29 Jun 15:23:00.030 # Redis version=3.9.103, bits=64, commit=51b12ed1, modified=0, pid=32343, just started
32343:C 29 Jun 15:23:00.030 # Configuration loaded
32343:M 29 Jun 15:23:00.032 * Running mode=standalone, port=50920.
32343:M 29 Jun 15:23:00.032 # Server initialized
32343:M 29 Jun 15:23:00.032 # <ft> ***** FATAL: Incompatible version of redis 4.0 detected. *****
                                Redis 4.0 RC3 or earlier will not run this module properly
                                Please use the latest 4.0 branch instead from https://github.com/antirez/redis/archive/4.0.zip
                                Redis will exit now!
32343:M 29 Jun 15:23:00.032 # Module module.so initialization failed. Module not loaded
32343:M 29 Jun 15:23:00.032 # Can't load module from module.so: server aborting
```

**Comment by stockholmux** [comment]
@dvirsky Awesome. Version checking will reduce wheel spinning for lots of people, I'm sure.

It _is_ weird that rc3 doesn't have the thread safe API. I know that thread-safe has been out for a while and didn't pay attention that rc3 is actually quite old. For those of us not involved with the development of modules/redis-server, going for the full-strength unstable is unusual. 

Maybe it'd be a good idea that the module API itself will have some sort of version check to prevent this.

**Comment by dvirsky** [comment]
It's an odd situation indeed, and a rare one even in the unstable branch of redis 4.0. Usually everything was always backwards compatible. The change was too big to support both modes of operation easily, and the gain from threading too big to wait with it - so I just went with it. 

In any case, redis 4.0 final is due within a few of weeks, I'm sure @antirez will release RC4 pretty soon :)
