### ISSUE TITLE
Core when using FT.INFO

### ISSUE THREAD

**Issue by slixurd** [RedisLabsModules/RediSearch#87]
1.redis version: 4.0 (https://github.com/antirez/redis/archive/4.0.zip)
2.redisearch version: github master branch
3.command before core: FT.INFO indexName
4.default config, not change any config nor use any redis.conf
5.OS: Darwin Mac.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
6.gcc: Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1 Apple LLVM version 8.1.0 (clang-802.0.42)
Here is the detail messgae:
6029:M 06 Jul 13:17:46.751 * Ready to accept connections
=== REDIS BUG REPORT START: Cut & paste starting from here ===
6029:M 06 Jul 13:53:02.528 # === ASSERTION FAILED ===
6029:M 06 Jul 13:53:02.528 # ==> networking.c:1898 'c->reply_bytes < SIZE_MAX-(1024*64)' is not true
6029:M 06 Jul 13:53:02.528 # (forcing SIGSEGV to print the bug report.)
6029:M 06 Jul 13:53:02.528 # Redis 3.9.103 crashed by signal: 11
6029:M 06 Jul 13:53:02.528 # Crashed running the instuction at: 0x10570088d
6029:M 06 Jul 13:53:02.528 # Accessing address: 0xffffffffffffffff
6029:M 06 Jul 13:53:02.528 # Failed assertion: c->reply_bytes < SIZE_MAX-(1024*64) (networking.c:1898)

------ STACK TRACE ------
EIP:
0   redis-server                        0x000000010570088d _serverAssert + 157

Backtrace:
0   redis-server                        0x00000001057024dd logStackTrace + 109
1   redis-server                        0x000000010570288c sigsegvHandler + 236
2   libsystem_platform.dylib            0x00007fff9b9f3b3a _sigtramp + 26
3   ???                                 0x0000000000000400 0x0 + 1024
4   redis-server                        0x00000001056c80f9 asyncCloseClientOnOutputBufferLimitReached + 361
5   redis-server                        0x000000010572dfe6 RM_ReplyWithSimpleString + 102
6   module.so                           0x00000001058ea5b4 IndexInfoCommand + 148
7   redis-server                        0x000000010572cdf3 RedisModuleCommandDispatcher + 147
8   redis-server                        0x00000001056ba998 call + 216
9   redis-server                        0x00000001056bb221 processCommand + 1297
10  redis-server                        0x00000001056cb234 processInputBuffer + 292
11  redis-server                        0x00000001056b3201 aeProcessEvents + 689
12  redis-server                        0x00000001056b34eb aeMain + 43
13  redis-server                        0x00000001056be13b main + 1643
14  libdyld.dylib                       0x00007fff9b7e4235 start + 1
15  ???                                 0x0000000000000003 0x0 + 3

....
------ CLIENT LIST OUTPUT ------
id=2 addr=127.0.0.1:51730 fd=8 name= age=2095 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=2 omem=18446744073709551458 events=r cmd=ft.info

------ CURRENT CLIENT INFO ------
id=2 addr=127.0.0.1:51730 fd=8 name= age=2095 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=2 omem=18446744073709551458 events=r cmd=ft.info
argv[0]: 'FT.INFO'
argv[1]: 'foodspu'

**Comment by slixurd** [comment]
But it cannot reproduce through the same operations.
I just create an index, write 100 documents by java api
then "FT.INFO foodspu" in the redis-cli

**Comment by dvirsky** [comment]
@slixurd Try the latest unstable branch of redis. I think I just fixed this in redis itself on https://github.com/antirez/redis/pull/4101 which was merged to unstable but not yet to 4.0

**Comment by dvirsky** [comment]
@slixurd AFAIK this has been addressed by the above mentioned fix, so I'm going to close this issue. Please reopen if it happens with a more recent version of redis.
