### ISSUE TITLE
FT.SEARCH INKEYS option is not fetching correct results

### ISSUE THREAD

**Issue by nreddipalle** [RedisLabsModules/RediSearch#97]
On testing with INKEYS option my results vary.
please see below.
![image](https://user-images.githubusercontent.com/28302399/28077455-cf885b6e-662f-11e7-9cbd-cade57799967.png)

Docker:0>ft.search Ticket (@title:redis|redis*) NOCONTENT

"5"
"179094"
"125158"
"141536"
"109642"
"108398"
WHEN passing the same values within INKEYS, the result is 0 always.
Please see below for the complete query: ( I checked atleast 4 of the them exist in the INKEYS values)

[redis query.txt](https://github.com/RedisLabsModules/RediSearch/files/1139494/redis.query.txt)
![image](https://user-images.githubusercontent.com/28302399/28077515-fecd17ac-662f-11e7-8133-70451d9ff248.png)
![image](https://user-images.githubusercontent.com/28302399/28077520-022bac1a-6630-11e7-8b06-5b9acc223689.png)

**Comment by dvirsky** [comment]
Thanks. Should be fixed in master. Please pull and verify - and I will release it as 0.19.2

**Comment by nreddipalle** [comment]
Thanks. I will check this. I am also working on writing a LUA script to intersect the results from FT.SEARCH (writing them to a SET) and UserAccessibleTicket SET and then returning the final TicketID's. Any sample code reflecting this?

**Comment by dvirsky** [comment]
It shouldn't be hard, but I seriously doubt it will be faster than INKEYS.

**Comment by nreddipalle** [comment]
My thought behind doing this is: it will be a single call to redis (passing the userID and searchkeyword) and script will get the search results into SET, get the useraccessible set, intersect them and then return the final result. with INKEYS, I need to first do a call and get the list from redis and then pass it on to INKEYS option and perform the search. so I thought it will be quicker with single call. anyways will do both and compare.

**Comment by nreddipalle** [comment]
I will check and close the defect.

**Comment by dvirsky** [comment]
So you are better off with a lua script that composes the INKEYS keys directly on the server. But all of those solutions are less than ideal. The best would be to be model it with the index.If you had a field called "allowedUsers" for each ticket and you would put the user ids there, and add to your query "@allowedUsers:12345" along with the query it would work best.

**Comment by nreddipalle** [comment]
ok. i will check that. if I could store the allowedUsers as a comma seperated for each Ticket (12345,56748,74793) may be i can make it even quicker. thanks for the suggestion.

**Comment by dvirsky** [comment]
yes, you can. if they are numbers, separating by comma or space does the same trick. it will work and be super fast. 
You can later update the ticket if you need to change the list - FT.ADD supports the REPLACE keyword which updates the document if it exists.

**Comment by nreddipalle** [comment]
the above fix is working fine when sending FT.SEARCH Ticket (@Title:redis*)
![image](https://user-images.githubusercontent.com/28302399/28092604-0b47d08a-6662-11e7-9262-03acdf9af114.png)

When sending the request like this FT.SEARCH Ticket (@Title:redis|redis*), it is not fetching any results. Ideally it should fetch the same as above (4).
![image](https://user-images.githubusercontent.com/28302399/28092676-50e65256-6662-11e7-9be7-3b9ef4c152dc.png)

**Comment by dvirsky** [comment]
I'm sorry but I cannot recreate it. If you could share your RDB I'l be able to test it. If not, please try to create a case where this happens from abstract data that I can recreate.

**Comment by nreddipalle** [comment]
I did a test with a small set today. Please see below for the results.
![image](https://user-images.githubusercontent.com/28302399/28119099-a1525d00-66e1-11e7-9b3e-4e1c2a0f360f.png)

**Comment by dvirsky** [comment]
I still cannot recreate it, but I'm sure I'll easily find the problem if you send me the rdb dump of your database. Thanks!

**Comment by nreddipalle** [comment]
I am not sure how to create an rdb dump when running from a docker recipe. I am providing the data within these records. let me know if it helps.
[Sample Data.txt](https://github.com/RedisLabsModules/RediSearch/files/1142098/Sample.Data.txt)

**Comment by dvirsky** [comment]
doesn't help me much, I need everything indexed exactly like you indexed it. 
You simply need to mound the redis working directory and map that to a local directory, then simply call SAVE and the rdb file will be created on the mapped local directory. Just upload that.

**Comment by dvirsky** [comment]
oh, another simple options would be this: 
run: `redis-cli -p {docker redis port} monitor > log.txt`
Then run the indexing code. 
This will put all the commands used to recreate the index into log.txt, which you can load here and I can replay.

**Comment by nreddipalle** [comment]
Its around 30MB. please download from this link.
https://www.dropbox.com/s/6mr659kdj9yxrj1/redislog.zip?dl=0

**Comment by dvirsky** [comment]
cool, will look into it shortly!

**Comment by dvirsky** [comment]
Ok, I'm able to recreate it, expect a fix later today or tomorrow morning GMT.

**Comment by nreddipalle** [comment]
when i am searching for redis*, will it only look for words starting with redis?? Is there a way to find words that end or contain redis??

**Comment by dvirsky** [comment]
No, there is no way to do that at the moment.

**Comment by dvirsky** [comment]
Works properly in current master:
```
127.0.0.1:6379> ft.search Ticket "@Title:(redis|redis*)" nocontent verbatim inkeys 12 196830 179094 149047 141536 125158 187587 191068 202071 166531 144636 108398 109642
1) (integer) 5
2) "179094"
3) "125158"
4) "141536"
5) "109642"
6) "108398"
```

**Comment by nreddipalle** [comment]
Redis is crashing with the latest redisearch master. this is the error in the log file.
![image](https://user-images.githubusercontent.com/28302399/28168934-b794a30c-67ae-11e7-9be0-aaf9fbf65bd5.png)

**Comment by dvirsky** [comment]
This is not a crash - read the message. The compiled module is invalid. Try pulling master again and run `make distclean all` if you are not pulling a fresh distribution of redis.

**Comment by nreddipalle** [comment]
Adding the distclean all to the recipe worked. thanks
RUN cd /usr/local/src && \
	git clone https://github.com/RedisLabsModules/RediSearch.git RediSearch && \
	cd RediSearch && \
	make && \
	make distclean all && \
	cp src/redisearch.so /usr/local/lib/redisearch.so && \
	cd /usr/local/src && \
	rm -rf /usr/local/src/RediSearch

**Comment by dvirsky** [comment]
I'm not sure it's needed for the long run, I just made some changes to the compiler flags and directory structure and wanted to make sure you are compiling the right objects. Thanks!

**Comment by nreddipalle** [comment]
the results looks consistent with the new build. A quick question. when i am searching across Title & Description in a single command, while creating index, I set the weight of Title to be 5.0 and Description is 4.0, i expect the result in the order of Title ticketIds followed by Description ticketIds. Is it correct assumption?

**Comment by dvirsky** [comment]
Not entirely. The results depend on the frequency in each field, the overall frequency of the terms in the "universe" of documents, and the distance between terms if multiple terms exist.

If you want more clear sorting between title and description, set the weights to something like 10 and 1 or 20 and 1. Because at 5 and 4, two appearances in the body are worth more than one in the title.

**Comment by nreddipalle** [comment]
One of my record contains **hires** within the sentence and when my search query contains @Description:hire, it should not fetch the record. I am hoping it will only fetch when I use @Description:hire*. But it is not the case. 
 
![image](https://user-images.githubusercontent.com/28302399/28224136-fb4a9b4a-689b-11e7-9a2a-e2396fe7ad49.png)

TicketId:202166 Description: |What type of idea are you submitting? Process Improvement<br><br>|What team should review your idea? Training<br><br>|What system does your idea impact? Other<br><br>|Enter your idea: I am currently in training and love that there is a B.I.G. rotation program that people can go through. I think it would be beneficial for new **hires** to go through a shorter/smaller version of B.I.G. (The LITTLE program)

**Comment by nreddipalle** [comment]
One more issue noticed: the total results count is not correct all the time:
The number of rows returned for the below query is 71967 but the count displayed is 72062.
![image](https://user-images.githubusercontent.com/28302399/28227401-bc7b90ac-68a7-11e7-8ded-cf24fe3c99ab.png)
![image](https://user-images.githubusercontent.com/28302399/28227432-dd14dada-68a7-11e7-9474-314d59c3aeb1.png)

The first query below displayed exactly 3188 records, but the second query only displayed 832 thought both are displaying the same value for No.of results.
![image](https://user-images.githubusercontent.com/28302399/28227576-9abaa9e8-68a8-11e7-8a19-3ebf2e1373b7.png)
