### ISSUE TITLE
FT.SEARCH is not fetching correct results.

### ISSUE THREAD

**Issue by nreddipalle** [RedisLabsModules/RediSearch#98]
please see my updated comments under #97

**Comment by nreddipalle** [comment]
Any difference with the syntax between two. the results count vary.
![image](https://user-images.githubusercontent.com/28302399/28228453-9ca4d766-68ac-11e7-92b2-7de08bc725fb.png)

**Comment by nreddipalle** [comment]
second query corrected:
![image](https://user-images.githubusercontent.com/28302399/28229517-1095c83e-68b1-11e7-96aa-99d48474da5a.png)

**Comment by nreddipalle** [comment]
More details:
![image](https://user-images.githubusercontent.com/28302399/28229677-a0f323b8-68b1-11e7-8bfe-cc7d7653577c.png)

![image](https://user-images.githubusercontent.com/28302399/28229684-acbf0ba8-68b1-11e7-8fe6-03467073adc2.png)

![image](https://user-images.githubusercontent.com/28302399/28229696-b7c289a8-68b1-11e7-850d-172b87d37b50.png)

**Comment by dvirsky** [comment]
The query fetching 3188 results above is not quoted, thus the allowed users part is not being processed. Both of the explain queries are quoted, thus they are identical. The `&` sign has no meaning at all. 

Also, a more optimized way of expressing the same thing would use the fact that you can specify multiple fields for the same expression, and get a much simpler parse tree:

```
FT.SEARACH Ticker "( (@Title:hire|hire*) | (@Description|Tag|Comment:(hire))) @AllowedUsers:10363"
```

**Comment by nreddipalle** [comment]
I still have this issue in some cases.
One more issue noticed: the total results count is not correct all the time:
The number of rows returned for the below query is 71967 but the count displayed is 72062.



The first query below displayed exactly 3188 records, but the second query only displayed 832 thought both are displaying the same value for No.of results.

**Comment by dvirsky** [comment]
There is a bug with the result count, the correct number is the number of actual rows.

**Comment by dvirsky** [comment]
@nreddipalle the counting bug has been fixed, should be okay with the current master. however if you see any weird results other than that do report.

**Comment by nreddipalle** [comment]
Thanks. will test and let know.
